// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

hic.wad
models/scmod/alab/svensci.mdl
models/scmod/alphaunit/clock_wall_static.mdl
models/scmod/alphaunit/construction.mdl
models/scmod/alphaunit/vance.mdl
models/scmod/alphaunit/vance_cleansuit.mdl
models/scmod/alphaunit/w_suit.mdl
models/scmod/barniel.mdl
models/scmod/npcs/massn/sniper.mdl
models/scmod/npcs/op4/depleur.mdl
models/scmod/npcs/op4/toyotafankk.mdl
models/scmod/npcs/op4torch/sv_bot.mdl
models/scmod/scientist_female.mdl
sound/scmod/alphaunit/dialogs/aunit1/0vance.ogg
sound/scmod/alphaunit/dialogs/aunit1/1vance.ogg
sound/scmod/alphaunit/dialogs/aunit1/2sven_r.ogg
sound/scmod/alphaunit/dialogs/aunit1/3radiosniper.ogg
sound/scmod/alphaunit/dialogs/aunit1/4vance.ogg
sound/scmod/alphaunit/dialogs/aunit1/5sniper.ogg
sound/scmod/alphaunit/dialogs/aunit1/6vance.ogg
sound/scmod/alphaunit/dialogs/aunit1/7sniper.ogg
sound/scmod/alphaunit/dialogs/aunit1b/pick2_depleur.ogg
sound/scmod/alphaunit/dialogs/aunit1b/pick6_depleur.ogg
sound/scmod/alphaunit/dialogs/aunit1b/pick7_sci.ogg
sound/scmod/alphaunit/dialogs/aunit1b/sci_portal.ogg
sound/scmod/alphaunit/dialogs/aunit1b/sci_supplies.ogg
sound/scmod/alphaunit/dialogs/aunit1b/scihint_info.ogg
sound/scmod/alphaunit/dialogs/aunit1b/scirant1.ogg
sound/scmod/alphaunit/dialogs/aunit2/1sniper.ogg
sound/scmod/alphaunit/dialogs/aunit2/2eli.ogg
sound/scmod/alphaunit/dialogs/aunit2/3sniper.ogg
sound/scmod/alphaunit/dialogs/quake2_reference.ogg
sound/scmod/alphaunit/fgrunt/pick3.ogg
sound/scmod/alphaunit/fgrunt/pick4.ogg
sound/scmod/alphaunit/fgrunt/pick5.ogg
sound/scmod/npcs/barniel/aimforhead.wav
sound/scmod/npcs/barniel/badfeeling.wav
sound/scmod/npcs/barniel/bn_another.wav
sound/scmod/npcs/barniel/bn_attack1.wav
sound/scmod/npcs/barniel/bn_becarefull.wav
sound/scmod/npcs/barniel/bn_bring.wav
sound/scmod/npcs/barniel/bn_carefull.wav
sound/scmod/npcs/barniel/bn_close.wav
sound/scmod/npcs/barniel/bn_die1.wav
sound/scmod/npcs/barniel/bn_dontdothat.wav
sound/scmod/npcs/barniel/bn_dontmake.wav
sound/scmod/npcs/barniel/bn_firepl.wav
sound/scmod/npcs/barniel/bn_friends.wav
sound/scmod/npcs/barniel/bn_gotone.wav
sound/scmod/npcs/barniel/bn_onelessh.wav
sound/scmod/npcs/barniel/bn_pain1.wav
sound/scmod/npcs/barniel/bn_pain2.wav
sound/scmod/npcs/barniel/bn_seethat.wav
sound/scmod/npcs/barniel/bn_stepoff.wav
sound/scmod/npcs/barniel/bn_whatyou.wav
sound/scmod/npcs/barniel/diegreenthing.wav
sound/scmod/npcs/barniel/dontagree.wav
sound/scmod/npcs/barniel/dontknow.wav
sound/scmod/npcs/barniel/drinktopside.wav
sound/scmod/npcs/barniel/hearsomething.wav
sound/scmod/npcs/barniel/hevno.wav
sound/scmod/npcs/barniel/hi.wav
sound/scmod/npcs/barniel/hitbad.wav
sound/scmod/npcs/barniel/imhit.wav
sound/scmod/npcs/barniel/movietv.wav
sound/scmod/npcs/barniel/nosir.wav
sound/scmod/npcs/barniel/openfire.wav
sound/scmod/npcs/barniel/rightway.wav
sound/scmod/npcs/barniel/seelater.wav
sound/scmod/npcs/barniel/seeya.wav
sound/scmod/npcs/barniel/seeyoulater.wav
sound/scmod/npcs/barniel/somethingmoves.wav
sound/scmod/npcs/barniel/teamup1.wav
sound/scmod/npcs/barniel/teamup2.wav
sound/scmod/npcs/barniel/thinking.wav
sound/scmod/npcs/barniel/whatsgoingon.wav
sound/scmod/npcs/barniel/yessir.wav
sound/scmod/npcs/barniel/youneedmedic.wav
sound/scmod/npcs/elivance/eli_fineidea01.ogg
sound/scmod/npcs/elivance/eli_launch_anotherattempt01.ogg
sound/scmod/npcs/elivance/eli_launch_bigpain04.ogg
sound/scmod/npcs/elivance/eli_launch_pain04.ogg
sound/scmod/npcs/elivance/eli_launch_pain05.ogg
sound/scmod/npcs/elivance/eli_launch_pain06.ogg
sound/scmod/npcs/elivance/eli_launch_pain09.ogg
sound/scmod/npcs/elivance/eli_launch_pain13.ogg
sound/scmod/npcs/elivance/eli_launch_portalyes02.ogg
sound/scmod/npcs/elivance/eli_letmethink03.ogg
sound/scmod/npcs/elivance/eli_micro01.ogg
sound/scmod/npcs/elivance/eli_notobreen.ogg
sound/scmod/npcs/elivance/eli_silo_catchingup01.ogg
sound/scmod/npcs/elivance/eli_silo_extracther01.ogg
sound/scmod/npcs/elivance/eli_silo_fineinaminute03.ogg
sound/scmod/npcs/elivance/eli_silo_hadalook01.ogg
sound/scmod/npcs/elivance/eli_silo_hurry.ogg
sound/scmod/npcs/elivance/eli_silo_ohbrother.ogg
sound/scmod/npcs/elivance/eli_silo_yousure01.ogg
sound/scmod/npcs/female_sci/absolutely.ogg
sound/scmod/npcs/female_sci/absolutelynot.ogg
sound/scmod/npcs/female_sci/administrator.ogg
sound/scmod/npcs/female_sci/afellowsci.ogg
sound/scmod/npcs/female_sci/alienappeal.ogg
sound/scmod/npcs/female_sci/alientrick.ogg
sound/scmod/npcs/female_sci/allnominal.ogg
sound/scmod/npcs/female_sci/alright.ogg
sound/scmod/npcs/female_sci/analysis.ogg
sound/scmod/npcs/female_sci/announcer.ogg
sound/scmod/npcs/female_sci/areyouthink.ogg
sound/scmod/npcs/female_sci/asexpected.ogg
sound/scmod/npcs/female_sci/beenaburden.ogg
sound/scmod/npcs/female_sci/beverage.ogg
sound/scmod/npcs/female_sci/bloodsample.ogg
sound/scmod/npcs/female_sci/c1a0_sci_bigday.ogg
sound/scmod/npcs/female_sci/c1a0_sci_crit1a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_crit2a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_crit3a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_ctrl1a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_ctrl2a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_ctrl3a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_ctrl4a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_getaway.ogg
sound/scmod/npcs/female_sci/c1a0_sci_gm.ogg
sound/scmod/npcs/female_sci/c1a0_sci_lock1a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_lock2a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_lock3a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_lock4a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_lock5a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_lock6a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_lock7a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_lock8a.ogg
sound/scmod/npcs/female_sci/c1a0_sci_samp.ogg
sound/scmod/npcs/female_sci/c1a1_sci_1scan.ogg
sound/scmod/npcs/female_sci/c1a1_sci_2scan.ogg
sound/scmod/npcs/female_sci/c1a1_sci_3scan.ogg
sound/scmod/npcs/female_sci/c1a1_sci_4scan.ogg
sound/scmod/npcs/female_sci/c1a1_sci_5scan.ogg
sound/scmod/npcs/female_sci/c1a2_sci_1zomb.ogg
sound/scmod/npcs/female_sci/c1a2_sci_3zomb.ogg
sound/scmod/npcs/female_sci/c1a2_sci_5zomb.ogg
sound/scmod/npcs/female_sci/c1a2_sci_6zomb.ogg
sound/scmod/npcs/female_sci/c1a2_sci_dangling.ogg
sound/scmod/npcs/female_sci/c1a2_sci_darkroom.ogg
sound/scmod/npcs/female_sci/c1a2_sci_elevator.ogg
sound/scmod/npcs/female_sci/c1a2_sci_lounge.ogg
sound/scmod/npcs/female_sci/c1a2_sci_transm.ogg
sound/scmod/npcs/female_sci/c1a3_sci_1man.ogg
sound/scmod/npcs/female_sci/c1a3_sci_atlast.ogg
sound/scmod/npcs/female_sci/c1a3_sci_rescued.ogg
sound/scmod/npcs/female_sci/c1a3_sci_silo1a.ogg
sound/scmod/npcs/female_sci/c1a3_sci_silo2a.ogg
sound/scmod/npcs/female_sci/c1a3_sci_team.ogg
sound/scmod/npcs/female_sci/c1a3_sci_thankgod.ogg
sound/scmod/npcs/female_sci/c1a4_sci_blind.ogg
sound/scmod/npcs/female_sci/c1a4_sci_gener.ogg
sound/scmod/npcs/female_sci/c1a4_sci_pwr.ogg
sound/scmod/npcs/female_sci/c1a4_sci_pwroff.ogg
sound/scmod/npcs/female_sci/c1a4_sci_rocket.ogg
sound/scmod/npcs/female_sci/c1a4_sci_tent.ogg
sound/scmod/npcs/female_sci/c1a4_sci_trainend.ogg
sound/scmod/npcs/female_sci/c1a4_sci_trust.ogg
sound/scmod/npcs/female_sci/c2a3_sci_icky.ogg
sound/scmod/npcs/female_sci/c2a3_sci_track.ogg
sound/scmod/npcs/female_sci/c2a4_sci_2tau.ogg
sound/scmod/npcs/female_sci/c2a4_sci_4tau.ogg
sound/scmod/npcs/female_sci/c2a4_sci_alldie.ogg
sound/scmod/npcs/female_sci/c2a4_sci_arg2a.ogg
sound/scmod/npcs/female_sci/c2a4_sci_arg4a.ogg
sound/scmod/npcs/female_sci/c2a4_sci_letout.ogg
sound/scmod/npcs/female_sci/c2a4_sci_scanner.ogg
sound/scmod/npcs/female_sci/c2a4_sci_sugicaloff.ogg
sound/scmod/npcs/female_sci/c2a4_sci_surgury.ogg
sound/scmod/npcs/female_sci/c2a5_sci_boobie.ogg
sound/scmod/npcs/female_sci/c2a5_sci_lebuz.ogg
sound/scmod/npcs/female_sci/c3a2_sci_1surv.ogg
sound/scmod/npcs/female_sci/c3a2_sci_2glu.ogg
sound/scmod/npcs/female_sci/c3a2_sci_3surv.ogg
sound/scmod/npcs/female_sci/c3a2_sci_5surv.ogg
sound/scmod/npcs/female_sci/c3a2_sci_7surv.ogg
sound/scmod/npcs/female_sci/c3a2_sci_flood.ogg
sound/scmod/npcs/female_sci/c3a2_sci_fool.ogg
sound/scmod/npcs/female_sci/c3a2_sci_forever.ogg
sound/scmod/npcs/female_sci/c3a2_sci_linger.ogg
sound/scmod/npcs/female_sci/c3a2_sci_ljump.ogg
sound/scmod/npcs/female_sci/c3a2_sci_notyet.ogg
sound/scmod/npcs/female_sci/c3a2_sci_portal.ogg
sound/scmod/npcs/female_sci/c3a2_sci_portopen.ogg
sound/scmod/npcs/female_sci/c3a2_sci_position.ogg
sound/scmod/npcs/female_sci/c3a2_sci_straws.ogg
sound/scmod/npcs/female_sci/c3a2_sci_uphere.ogg
sound/scmod/npcs/female_sci/cantbeserious.ogg
sound/scmod/npcs/female_sci/cantbeworse.ogg
sound/scmod/npcs/female_sci/canttakemore.ogg
sound/scmod/npcs/female_sci/cascade.ogg
sound/scmod/npcs/female_sci/catchone.ogg
sound/scmod/npcs/female_sci/chaostheory.ogg
sound/scmod/npcs/female_sci/checkatten.ogg
sound/scmod/npcs/female_sci/completelywrong.ogg
sound/scmod/npcs/female_sci/containfail.ogg
sound/scmod/npcs/female_sci/correcttheory.ogg
sound/scmod/npcs/female_sci/delayagain.ogg
sound/scmod/npcs/female_sci/didyouhear.ogg
sound/scmod/npcs/female_sci/dinner.ogg
sound/scmod/npcs/female_sci/dontgothere.ogg
sound/scmod/npcs/female_sci/dontknow.ogg
sound/scmod/npcs/female_sci/dontwantdie.ogg
sound/scmod/npcs/female_sci/donuteater.ogg
sound/scmod/npcs/female_sci/doyousmell.ogg
sound/scmod/npcs/female_sci/evergetout.ogg
sound/scmod/npcs/female_sci/everseen.ogg
sound/scmod/npcs/female_sci/excellentteam.ogg
sound/scmod/npcs/female_sci/fascinating.ogg
sound/scmod/npcs/female_sci/fellowscientist.ogg
sound/scmod/npcs/female_sci/fine.ogg
sound/scmod/npcs/female_sci/getoutalive.ogg
sound/scmod/npcs/female_sci/getoutofhere.ogg
sound/scmod/npcs/female_sci/goodpaper.ogg
sound/scmod/npcs/female_sci/goodtoseeyou.ogg
sound/scmod/npcs/female_sci/greetings.ogg
sound/scmod/npcs/female_sci/greetings2.ogg
sound/scmod/npcs/female_sci/headcrab.ogg
sound/scmod/npcs/female_sci/heal1.ogg
sound/scmod/npcs/female_sci/heal2.ogg
sound/scmod/npcs/female_sci/heal3.ogg
sound/scmod/npcs/female_sci/heal4.ogg
sound/scmod/npcs/female_sci/heal5.ogg
sound/scmod/npcs/female_sci/hearsomething.ogg
sound/scmod/npcs/female_sci/hello.ogg
sound/scmod/npcs/female_sci/hellofromlab.ogg
sound/scmod/npcs/female_sci/hellothere.ogg
sound/scmod/npcs/female_sci/hideglasses.ogg
sound/scmod/npcs/female_sci/holdstill.ogg
sound/scmod/npcs/female_sci/hopenominal.ogg
sound/scmod/npcs/female_sci/hopeyouknow.ogg
sound/scmod/npcs/female_sci/howinteresting.ogg
sound/scmod/npcs/female_sci/hungryyet.ogg
sound/scmod/npcs/female_sci/ibelieveso.ogg
sound/scmod/npcs/female_sci/idontthinkso.ogg
sound/scmod/npcs/female_sci/ihearsomething.ogg
sound/scmod/npcs/female_sci/illwait.ogg
sound/scmod/npcs/female_sci/illwaithere.ogg
sound/scmod/npcs/female_sci/importantspecies.ogg
sound/scmod/npcs/female_sci/improbable.ogg
sound/scmod/npcs/female_sci/imsure.ogg
sound/scmod/npcs/female_sci/inconclusive.ogg
sound/scmod/npcs/female_sci/inmesstoo.ogg
sound/scmod/npcs/female_sci/ipredictedthis.ogg
sound/scmod/npcs/female_sci/istay.ogg
sound/scmod/npcs/female_sci/iwounded.ogg
sound/scmod/npcs/female_sci/iwounded2.ogg
sound/scmod/npcs/female_sci/iwoundedbad.ogg
sound/scmod/npcs/female_sci/justasked.ogg
sound/scmod/npcs/female_sci/lambdalab.ogg
sound/scmod/npcs/female_sci/leadtheway.ogg
sound/scmod/npcs/female_sci/letsgo.ogg
sound/scmod/npcs/female_sci/letstrythis.ogg
sound/scmod/npcs/female_sci/letyouin.ogg
sound/scmod/npcs/female_sci/limitsok.ogg
sound/scmod/npcs/female_sci/lowervoice.ogg
sound/scmod/npcs/female_sci/luckwillchange.ogg
sound/scmod/npcs/female_sci/madness.ogg
sound/scmod/npcs/female_sci/needsleep.ogg
sound/scmod/npcs/female_sci/neverseen.ogg
sound/scmod/npcs/female_sci/newhevsuit.ogg
sound/scmod/npcs/female_sci/newsample.ogg
sound/scmod/npcs/female_sci/nodoubt.ogg
sound/scmod/npcs/female_sci/nogrant.ogg
sound/scmod/npcs/female_sci/noguess.ogg
sound/scmod/npcs/female_sci/noidea.ogg
sound/scmod/npcs/female_sci/noo.ogg
sound/scmod/npcs/female_sci/nooo.ogg
sound/scmod/npcs/female_sci/noplease.ogg
sound/scmod/npcs/female_sci/notcertain.ogg
sound/scmod/npcs/female_sci/nothostile.ogg
sound/scmod/npcs/female_sci/notsure.ogg
sound/scmod/npcs/female_sci/odorfromyou.ogg
sound/scmod/npcs/female_sci/ofcourse.ogg
sound/scmod/npcs/female_sci/ofcoursenot.ogg
sound/scmod/npcs/female_sci/organicmatter.ogg
sound/scmod/npcs/female_sci/overhere.ogg
sound/scmod/npcs/female_sci/peculiarmarks.ogg
sound/scmod/npcs/female_sci/peculiarodor.ogg
sound/scmod/npcs/female_sci/perfectday.ogg
sound/scmod/npcs/female_sci/perhaps.ogg
sound/scmod/npcs/female_sci/positively.ogg
sound/scmod/npcs/female_sci/purereadings.ogg
sound/scmod/npcs/female_sci/recalculate.ogg
sound/scmod/npcs/female_sci/reconsider.ogg
sound/scmod/npcs/female_sci/repeat.ogg
sound/scmod/npcs/female_sci/reportflux.ogg
sound/scmod/npcs/female_sci/rescueus.ogg
sound/scmod/npcs/female_sci/ridiculous.ogg
sound/scmod/npcs/female_sci/right.ogg
sound/scmod/npcs/female_sci/rightwayout.ogg
sound/scmod/npcs/female_sci/rumorclean.ogg
sound/scmod/npcs/female_sci/runtest.ogg
sound/scmod/npcs/female_sci/sci_aftertest.ogg
sound/scmod/npcs/female_sci/sci_alone.ogg
sound/scmod/npcs/female_sci/sci_bother.ogg
sound/scmod/npcs/female_sci/sci_busy.ogg
sound/scmod/npcs/female_sci/sci_die1.ogg
sound/scmod/npcs/female_sci/sci_die2.ogg
sound/scmod/npcs/female_sci/sci_die3.ogg
sound/scmod/npcs/female_sci/sci_die4.ogg
sound/scmod/npcs/female_sci/sci_fear1.ogg
sound/scmod/npcs/female_sci/sci_fear10.ogg
sound/scmod/npcs/female_sci/sci_fear11.ogg
sound/scmod/npcs/female_sci/sci_fear12.ogg
sound/scmod/npcs/female_sci/sci_fear13.ogg
sound/scmod/npcs/female_sci/sci_fear14.ogg
sound/scmod/npcs/female_sci/sci_fear15.ogg
sound/scmod/npcs/female_sci/sci_fear2.ogg
sound/scmod/npcs/female_sci/sci_fear3.ogg
sound/scmod/npcs/female_sci/sci_fear4.ogg
sound/scmod/npcs/female_sci/sci_fear5.ogg
sound/scmod/npcs/female_sci/sci_fear6.ogg
sound/scmod/npcs/female_sci/sci_fear7.ogg
sound/scmod/npcs/female_sci/sci_fear8.ogg
sound/scmod/npcs/female_sci/sci_fear9.ogg
sound/scmod/npcs/female_sci/sci_pain1.ogg
sound/scmod/npcs/female_sci/sci_pain10.ogg
sound/scmod/npcs/female_sci/sci_pain2.ogg
sound/scmod/npcs/female_sci/sci_pain3.ogg
sound/scmod/npcs/female_sci/sci_pain4.ogg
sound/scmod/npcs/female_sci/sci_pain5.ogg
sound/scmod/npcs/female_sci/sci_pain6.ogg
sound/scmod/npcs/female_sci/sci_pain7.ogg
sound/scmod/npcs/female_sci/sci_pain8.ogg
sound/scmod/npcs/female_sci/sci_pain9.ogg
sound/scmod/npcs/female_sci/sci_somewhere.ogg
sound/scmod/npcs/female_sci/scream01.ogg
sound/scmod/npcs/female_sci/scream02.ogg
sound/scmod/npcs/female_sci/scream03.ogg
sound/scmod/npcs/female_sci/scream04.ogg
sound/scmod/npcs/female_sci/scream05.ogg
sound/scmod/npcs/female_sci/scream06.ogg
sound/scmod/npcs/female_sci/scream07.ogg
sound/scmod/npcs/female_sci/scream1.ogg
sound/scmod/npcs/female_sci/scream10.ogg
sound/scmod/npcs/female_sci/scream11.ogg
sound/scmod/npcs/female_sci/scream12.ogg
sound/scmod/npcs/female_sci/scream13.ogg
sound/scmod/npcs/female_sci/scream14.ogg
sound/scmod/npcs/female_sci/scream15.ogg
sound/scmod/npcs/female_sci/scream16.ogg
sound/scmod/npcs/female_sci/scream17.ogg
sound/scmod/npcs/female_sci/scream18.ogg
sound/scmod/npcs/female_sci/scream19.ogg
sound/scmod/npcs/female_sci/scream2.ogg
sound/scmod/npcs/female_sci/scream20.ogg
sound/scmod/npcs/female_sci/scream21.ogg
sound/scmod/npcs/female_sci/scream22.ogg
sound/scmod/npcs/female_sci/scream23.ogg
sound/scmod/npcs/female_sci/scream24.ogg
sound/scmod/npcs/female_sci/scream25.ogg
sound/scmod/npcs/female_sci/scream3.ogg
sound/scmod/npcs/female_sci/scream4.ogg
sound/scmod/npcs/female_sci/scream5.ogg
sound/scmod/npcs/female_sci/scream6.ogg
sound/scmod/npcs/female_sci/scream7.ogg
sound/scmod/npcs/female_sci/seeheadcrab.ogg
sound/scmod/npcs/female_sci/seencup.ogg
sound/scmod/npcs/female_sci/shakeunification.ogg
sound/scmod/npcs/female_sci/shutdownchart.ogg
sound/scmod/npcs/female_sci/shutup.ogg
sound/scmod/npcs/female_sci/simulation.ogg
sound/scmod/npcs/female_sci/slowingyou.ogg
sound/scmod/npcs/female_sci/smellburn.ogg
sound/scmod/npcs/female_sci/softethics.ogg
sound/scmod/npcs/female_sci/somethingfoul.ogg
sound/scmod/npcs/female_sci/sorryimleaving.ogg
sound/scmod/npcs/female_sci/startle1.ogg
sound/scmod/npcs/female_sci/startle2.ogg
sound/scmod/npcs/female_sci/startle3.ogg
sound/scmod/npcs/female_sci/startle4.ogg
sound/scmod/npcs/female_sci/startle5.ogg
sound/scmod/npcs/female_sci/startle6.ogg
sound/scmod/npcs/female_sci/startle7.ogg
sound/scmod/npcs/female_sci/startle8.ogg
sound/scmod/npcs/female_sci/startle9.ogg
sound/scmod/npcs/female_sci/statusreport.ogg
sound/scmod/npcs/female_sci/stench.ogg
sound/scmod/npcs/female_sci/stimulating.ogg
sound/scmod/npcs/female_sci/stop1.ogg
sound/scmod/npcs/female_sci/stop2.ogg
sound/scmod/npcs/female_sci/stop3.ogg
sound/scmod/npcs/female_sci/stop4.ogg
sound/scmod/npcs/female_sci/stopasking.ogg
sound/scmod/npcs/female_sci/stopattacking.ogg
sound/scmod/npcs/female_sci/survival.ogg
sound/scmod/npcs/female_sci/thatsodd.ogg
sound/scmod/npcs/female_sci/theoretically.ogg
sound/scmod/npcs/female_sci/tunedtoday.ogg
sound/scmod/npcs/female_sci/tunnelcalc.ogg
sound/scmod/npcs/female_sci/uselessphd.ogg
sound/scmod/npcs/female_sci/waithere.ogg
sound/scmod/npcs/female_sci/weartie.ogg
sound/scmod/npcs/female_sci/whatissound.ogg
sound/scmod/npcs/female_sci/whatnext.ogg
sound/scmod/npcs/female_sci/whatyoudoing.ogg
sound/scmod/npcs/female_sci/whocansay.ogg
sound/scmod/npcs/female_sci/whoresponsible.ogg
sound/scmod/npcs/female_sci/whyaskme.ogg
sound/scmod/npcs/female_sci/whyleavehere.ogg
sound/scmod/npcs/female_sci/yees.ogg
sound/scmod/npcs/female_sci/yes.ogg
sound/scmod/npcs/female_sci/yes3.ogg
sound/scmod/npcs/female_sci/yesletsgo.ogg
sound/scmod/npcs/female_sci/youinsane.ogg
sound/scmod/npcs/female_sci/youlookbad.ogg
sound/scmod/npcs/female_sci/youlookbad2.ogg
sound/scmod/npcs/female_sci/youneedmedic.ogg
sound/scmod/npcs/female_sci/youwounded.ogg
