// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/arcticescape/padlock.mdl
models/echoes/gorepile.mdl
models/hotline/bulb.mdl
models/instinct/Geoffrey.mdl
models/instinct/Leonard.mdl
models/opfor/wire_black32.mdl
models/scmod/alab/sven_cleansuit.mdl
models/scmod/alphaunit/classic_scientist.mdl
models/scmod/alphaunit/classic_scientist_gun.mdl
models/scmod/alphaunit/collar_test.mdl
models/scmod/alphaunit/construction.mdl
models/scmod/alphaunit/cristal.mdl
models/scmod/alphaunit/geo_bodybag3.mdl
models/scmod/alphaunit/hevsci.mdl
models/scmod/alphaunit/item_sample.mdl
models/scmod/alphaunit/jaystelly.mdl
models/scmod/alphaunit/kleiner.mdl
models/scmod/alphaunit/main_portal.mdl
models/scmod/alphaunit/miniturret_portable.mdl
models/scmod/alphaunit/pitworm_young2.mdl
models/scmod/alphaunit/toilet.mdl
models/scmod/alphaunit/tool_box.mdl
models/scmod/alphaunit/vida.mdl
models/scmod/alphaunit/w_gfhelmet.mdl
models/scmod/alphaunit/w_isotopebox_old.mdl
models/scmod/alphaunit/zombie_hev.mdl
models/scmod/chungo/dead_headcrab.mdl
models/scmod/npcs/islave/islavef.mdl
models/scmod/npcs/islave/vortigauntjunior.mdl
models/scmod/npcs/massn/sniper.mdl
models/scmod/npcs/op4/depleur.mdl
models/scmod/npcs/op4/toyotafankk.mdl
models/scmod/npcs/op4torch/sv_bot.mdl
sound/scmod/alphaunit/anomalous_intro.ogg
sound/scmod/alphaunit/anomalous_outro.ogg
sound/scmod/alphaunit/anomaloustheme.ogg
sound/scmod/alphaunit/ascension_leggett_end.ogg
sound/scmod/alphaunit/ascension_leggett_intro1.ogg
sound/scmod/alphaunit/ascension_leggett_intro2.ogg
sound/scmod/alphaunit/ascension_leggett_loop1.ogg
sound/scmod/alphaunit/ascension_leggett_loop2.ogg
sound/scmod/alphaunit/bm_uc.ogg
sound/scmod/alphaunit/dialogs/aunit12/0sniper.ogg
sound/scmod/alphaunit/dialogs/aunit12/0sniperb.ogg
sound/scmod/alphaunit/dialogs/aunit12/1teasley.ogg
sound/scmod/alphaunit/dialogs/aunit12/2sniper.ogg
sound/scmod/alphaunit/dialogs/aunit12/mumble.ogg
sound/scmod/alphaunit/dialogs/aunit12/mumble2.ogg
sound/scmod/alphaunit/dialogs/aunit13/sci_gordondork.ogg
sound/scmod/alphaunit/dialogs/aunit14/sniper_stay.ogg
sound/scmod/alphaunit/dialogs/aunit15/10vorticough.ogg
sound/scmod/alphaunit/dialogs/aunit15/10vorticough_e.ogg
sound/scmod/alphaunit/dialogs/aunit15/11kleiner.ogg
sound/scmod/alphaunit/dialogs/aunit15/11kleiner_e.ogg
sound/scmod/alphaunit/dialogs/aunit15/12leonard.ogg
sound/scmod/alphaunit/dialogs/aunit15/14sniper.ogg
sound/scmod/alphaunit/dialogs/aunit15/14sniper_r.ogg
sound/scmod/alphaunit/dialogs/aunit15/15kleiner.ogg
sound/scmod/alphaunit/dialogs/aunit15/1kleiner.ogg
sound/scmod/alphaunit/dialogs/aunit15/2sniper.ogg
sound/scmod/alphaunit/dialogs/aunit15/3vortjunior.ogg
sound/scmod/alphaunit/dialogs/aunit15/4geoffrey.ogg
sound/scmod/alphaunit/dialogs/aunit15/5kleiner.ogg
sound/scmod/alphaunit/dialogs/aunit15/6sniper.ogg
sound/scmod/alphaunit/dialogs/aunit15/7kleiner.ogg
sound/scmod/alphaunit/dialogs/aunit15/8vortjunior.ogg
sound/scmod/alphaunit/dialogs/aunit15/9kleiner.ogg
sound/scmod/alphaunit/dialogs/aunit15/jaytest.ogg
sound/scmod/alphaunit/dialogs/aunit15/kleiner_boss.ogg
sound/scmod/alphaunit/dialogs/aunit15/kleiner_boss_s.ogg
sound/scmod/alphaunit/dialogs/aunit15/kleiner_dontshoot.ogg
sound/scmod/alphaunit/dialogs/aunit15/kleiner_inposition.ogg
sound/scmod/alphaunit/dialogs/aunit15/kleiner_lastrant.ogg
sound/scmod/alphaunit/dialogs/aunit15/kleiner_lastrant_e.ogg
sound/scmod/alphaunit/dialogs/aunit15/kleiner_start.ogg
sound/scmod/alphaunit/dialogs/aunit15/kleiner_start_s.ogg
sound/scmod/alphaunit/dialogs/aunit15/nil_slaves2.ogg
sound/scmod/alphaunit/dialogs/aunit15/slaveschant.ogg
sound/scmod/alphaunit/dialogs/quake2_reference.ogg
sound/scmod/alphaunit/internalconflict_dylanleggett.ogg
sound/scmod/alphaunit/triage_ewcars.ogg
sound/scmod/npcs/barniel/aimforhead.wav
sound/scmod/npcs/barniel/badfeeling.wav
sound/scmod/npcs/barniel/bn_another.wav
sound/scmod/npcs/barniel/bn_attack1.wav
sound/scmod/npcs/barniel/bn_becarefull.wav
sound/scmod/npcs/barniel/bn_bring.wav
sound/scmod/npcs/barniel/bn_carefull.wav
sound/scmod/npcs/barniel/bn_close.wav
sound/scmod/npcs/barniel/bn_die1.wav
sound/scmod/npcs/barniel/bn_dontdothat.wav
sound/scmod/npcs/barniel/bn_dontmake.wav
sound/scmod/npcs/barniel/bn_firepl.wav
sound/scmod/npcs/barniel/bn_friends.wav
sound/scmod/npcs/barniel/bn_gotone.wav
sound/scmod/npcs/barniel/bn_onelessh.wav
sound/scmod/npcs/barniel/bn_pain1.wav
sound/scmod/npcs/barniel/bn_pain2.wav
sound/scmod/npcs/barniel/bn_seethat.wav
sound/scmod/npcs/barniel/bn_stepoff.wav
sound/scmod/npcs/barniel/bn_whatyou.wav
sound/scmod/npcs/barniel/diegreenthing.wav
sound/scmod/npcs/barniel/dontagree.wav
sound/scmod/npcs/barniel/dontknow.wav
sound/scmod/npcs/barniel/drinktopside.wav
sound/scmod/npcs/barniel/hearsomething.wav
sound/scmod/npcs/barniel/hevno.wav
sound/scmod/npcs/barniel/hi.wav
sound/scmod/npcs/barniel/hitbad.wav
sound/scmod/npcs/barniel/imhit.wav
sound/scmod/npcs/barniel/movietv.wav
sound/scmod/npcs/barniel/nosir.wav
sound/scmod/npcs/barniel/openfire.wav
sound/scmod/npcs/barniel/rightway.wav
sound/scmod/npcs/barniel/seelater.wav
sound/scmod/npcs/barniel/seeya.wav
sound/scmod/npcs/barniel/seeyoulater.wav
sound/scmod/npcs/barniel/somethingmoves.wav
sound/scmod/npcs/barniel/teamup1.wav
sound/scmod/npcs/barniel/teamup2.wav
sound/scmod/npcs/barniel/thinking.wav
sound/scmod/npcs/barniel/whatsgoingon.wav
sound/scmod/npcs/barniel/yessir.wav
sound/scmod/npcs/barniel/youneedmedic.wav
