// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/opfor/svenhands/v_knife.mdl
models/opfor/wire_black32.mdl
models/opfor/wire_black8.mdl
models/opfor/wire_copper8.mdl
models/scmod/alphaunit/ae_pumper.mdl
models/scmod/alphaunit/cc_indistrial_pump_smol.mdl
models/scmod/alphaunit/clock_wall_static.mdl
models/scmod/alphaunit/construction.mdl
models/scmod/alphaunit/toilet.mdl
models/scmod/alphaunit/train.mdl
models/scmod/barniel.mdl
models/scmod/chungo/dead_islave.mdl
models/scmod/scientist_female.mdl
sound/scmod/alphaunit/battle_loop3.ogg
sound/scmod/alphaunit/dialogs/aunit3/1sci.ogg
sound/scmod/alphaunit/dialogs/aunit3/2sci.ogg
sound/scmod/alphaunit/dialogs/aunit3/gruntchat.ogg
sound/scmod/alphaunit/dialogs/aunit4/0sci.ogg
sound/scmod/alphaunit/dialogs/quake2_reference.ogg
sound/scmod/alphaunit/electrosmog_vandoorea.ogg
sound/scmod/npcs/barniel/aimforhead.wav
sound/scmod/npcs/barniel/badfeeling.wav
sound/scmod/npcs/barniel/bequiet.wav
sound/scmod/npcs/barniel/bn_another.wav
sound/scmod/npcs/barniel/bn_attack1.wav
sound/scmod/npcs/barniel/bn_becarefull.wav
sound/scmod/npcs/barniel/bn_bring.wav
sound/scmod/npcs/barniel/bn_carefull.wav
sound/scmod/npcs/barniel/bn_close.wav
sound/scmod/npcs/barniel/bn_die1.wav
sound/scmod/npcs/barniel/bn_dontdothat.wav
sound/scmod/npcs/barniel/bn_dontmake.wav
sound/scmod/npcs/barniel/bn_endline.wav
sound/scmod/npcs/barniel/bn_firepl.wav
sound/scmod/npcs/barniel/bn_friends.wav
sound/scmod/npcs/barniel/bn_gotone.wav
sound/scmod/npcs/barniel/bn_onelessh.wav
sound/scmod/npcs/barniel/bn_pain1.wav
sound/scmod/npcs/barniel/bn_pain2.wav
sound/scmod/npcs/barniel/bn_post.wav
sound/scmod/npcs/barniel/bn_seethat.wav
sound/scmod/npcs/barniel/bn_stepoff.wav
sound/scmod/npcs/barniel/bn_tomb.wav
sound/scmod/npcs/barniel/bn_whatyou.wav
sound/scmod/npcs/barniel/diegreenthing.wav
sound/scmod/npcs/barniel/dontagree.wav
sound/scmod/npcs/barniel/dontknow.wav
sound/scmod/npcs/barniel/drinktopside.wav
sound/scmod/npcs/barniel/hearsomething.wav
sound/scmod/npcs/barniel/hevno.wav
sound/scmod/npcs/barniel/hi.wav
sound/scmod/npcs/barniel/hitbad.wav
sound/scmod/npcs/barniel/hoyes.wav
sound/scmod/npcs/barniel/humm.wav
sound/scmod/npcs/barniel/imhit.wav
sound/scmod/npcs/barniel/movietv.wav
sound/scmod/npcs/barniel/nosir.wav
sound/scmod/npcs/barniel/notatall.wav
sound/scmod/npcs/barniel/openfire.wav
sound/scmod/npcs/barniel/rightway.wav
sound/scmod/npcs/barniel/seelater.wav
sound/scmod/npcs/barniel/seeya.wav
sound/scmod/npcs/barniel/seeyoulater.wav
sound/scmod/npcs/barniel/somethingmoves.wav
sound/scmod/npcs/barniel/stop1.wav
sound/scmod/npcs/barniel/teamup1.wav
sound/scmod/npcs/barniel/teamup2.wav
sound/scmod/npcs/barniel/thinking.wav
sound/scmod/npcs/barniel/waitin.wav
sound/scmod/npcs/barniel/whatsgoingon.wav
sound/scmod/npcs/barniel/yesbarn.wav
sound/scmod/npcs/barniel/yessir.wav
sound/scmod/npcs/barniel/youneedmedic.wav
sound/weapons/knife_deploy1.wav
