// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/ast/hwagrunt.mdl
models/hotline/bulb.mdl
models/props/light_bulb_red.mdl
models/scmod/alphaunit/agrunt.mdl
models/scmod/alphaunit/classic_scientist.mdl
models/scmod/alphaunit/construction.mdl
models/scmod/massn_fem_hd.mdl
models/scmod/npcs/massn/sniper.mdl
models/scmod/npcs/op4/depleur.mdl
models/scmod/npcs/op4/toyotafankk.mdl
models/scmod/npcs/op4torch/sv_bot.mdl
sound/scmod/alphaunit/alienfight.ogg
sound/scmod/alphaunit/battle_loop1.ogg
sound/scmod/alphaunit/battle_loop2.ogg
sound/scmod/alphaunit/battle_loop4.ogg
sound/scmod/alphaunit/dialogs/quake2_reference.ogg
sound/scmod/npcs/barniel/aimforhead.wav
sound/scmod/npcs/barniel/badfeeling.wav
sound/scmod/npcs/barniel/bn_another.wav
sound/scmod/npcs/barniel/bn_attack1.wav
sound/scmod/npcs/barniel/bn_becarefull.wav
sound/scmod/npcs/barniel/bn_bring.wav
sound/scmod/npcs/barniel/bn_carefull.wav
sound/scmod/npcs/barniel/bn_close.wav
sound/scmod/npcs/barniel/bn_die1.wav
sound/scmod/npcs/barniel/bn_dontdothat.wav
sound/scmod/npcs/barniel/bn_dontmake.wav
sound/scmod/npcs/barniel/bn_firepl.wav
sound/scmod/npcs/barniel/bn_friends.wav
sound/scmod/npcs/barniel/bn_gotone.wav
sound/scmod/npcs/barniel/bn_onelessh.wav
sound/scmod/npcs/barniel/bn_pain1.wav
sound/scmod/npcs/barniel/bn_pain2.wav
sound/scmod/npcs/barniel/bn_seethat.wav
sound/scmod/npcs/barniel/bn_stepoff.wav
sound/scmod/npcs/barniel/bn_whatyou.wav
sound/scmod/npcs/barniel/diegreenthing.wav
sound/scmod/npcs/barniel/dontagree.wav
sound/scmod/npcs/barniel/dontknow.wav
sound/scmod/npcs/barniel/drinktopside.wav
sound/scmod/npcs/barniel/hearsomething.wav
sound/scmod/npcs/barniel/hevno.wav
sound/scmod/npcs/barniel/hi.wav
sound/scmod/npcs/barniel/hitbad.wav
sound/scmod/npcs/barniel/imhit.wav
sound/scmod/npcs/barniel/movietv.wav
sound/scmod/npcs/barniel/nosir.wav
sound/scmod/npcs/barniel/openfire.wav
sound/scmod/npcs/barniel/rightway.wav
sound/scmod/npcs/barniel/seelater.wav
sound/scmod/npcs/barniel/seeya.wav
sound/scmod/npcs/barniel/seeyoulater.wav
sound/scmod/npcs/barniel/somethingmoves.wav
sound/scmod/npcs/barniel/teamup1.wav
sound/scmod/npcs/barniel/teamup2.wav
sound/scmod/npcs/barniel/thinking.wav
sound/scmod/npcs/barniel/whatsgoingon.wav
sound/scmod/npcs/barniel/yessir.wav
sound/scmod/npcs/barniel/youneedmedic.wav
sound/scmod/npcs/female_massn/of2a5_bo01.ogg
sound/scmod/npcs/female_massn/of2a5_bo02.ogg
sound/scmod/npcs/female_massn/of2a5_bo03.ogg
sound/scmod/npcs/female_massn/of6a2_bo01.ogg
sound/scmod/npcs/female_massn/of6a2_bo02.ogg
sound/scmod/npcs/female_massn/of6a2_bo03.ogg
