// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

autonomy_lost.wad
gfx/env/city_nitebk.tga
gfx/env/city_nitedn.tga
gfx/env/city_niteft.tga
gfx/env/city_nitelf.tga
gfx/env/city_nitert.tga
gfx/env/city_niteup.tga
models/autonomy_lost/AA_Breakroom_CoffeePot_KN_Smesh.mdl
models/autonomy_lost/AF_devices_radio_prl.mdl
models/autonomy_lost/AF_household_cup02.mdl
models/autonomy_lost/AF_pallete_pushcart.mdl
models/autonomy_lost/barney.mdl
models/autonomy_lost/bigbluetruck.mdl
models/autonomy_lost/com_telephone_desk.mdl
models/autonomy_lost/computer_mouse01.mdl
models/autonomy_lost/copy_machine.mdl
models/autonomy_lost/forklift01.mdl
models/autonomy_lost/gonome.mdl
models/autonomy_lost/hgrunt_opfor.mdl
models/autonomy_lost/hostage.mdl
models/autonomy_lost/hummer.mdl
models/autonomy_lost/s_truck2.mdl
models/autonomy_lost/v_357.mdl
models/autonomy_lost/v_9mmar.mdl
models/autonomy_lost/v_9mmhandgun.mdl
models/autonomy_lost/v_crossbow.mdl
models/autonomy_lost/v_crowbar.mdl
models/autonomy_lost/v_grenade.mdl
models/autonomy_lost/v_shotgun.mdl
models/autonomy_lost/vend3.mdl
models/autonomy_lost/vend5.mdl
models/autonomy_lost/zombie.mdl
models/autonomy_lost/zombie_soldier.mdl
nw_autonomylost.wad
poke646.wad
sound/autonomy_lost/ambience/annoying_elevator_music.wav
sound/autonomy_lost/ambience/exp2.wav
sound/autonomy_lost/ambience/hidden_button1.wav
sound/autonomy_lost/ambience/hidden_door_creak1.wav
sound/autonomy_lost/ambience/platmove1.wav
sound/autonomy_lost/ambience/scream11.wav
sound/autonomy_lost/ambience/tunnel_amb.wav
sound/autonomy_lost/gonome/gonome_death2.wav
sound/autonomy_lost/gonome/gonome_death3.wav
sound/autonomy_lost/gonome/gonome_death4.wav
sound/autonomy_lost/gonome/gonome_eat.wav
sound/autonomy_lost/gonome/gonome_idle1.wav
sound/autonomy_lost/gonome/gonome_idle2.wav
sound/autonomy_lost/gonome/gonome_idle3.wav
sound/autonomy_lost/gonome/gonome_jumpattack.wav
sound/autonomy_lost/gonome/gonome_melee1.wav
sound/autonomy_lost/gonome/gonome_melee2.wav
sound/autonomy_lost/gonome/gonome_pain1.wav
sound/autonomy_lost/gonome/gonome_pain2.wav
sound/autonomy_lost/gonome/gonome_pain3.wav
sound/autonomy_lost/gonome/gonome_pain4.wav
sound/autonomy_lost/gonome/gonome_run.wav
sound/autonomy_lost/materials.txt
sound/autonomy_lost/player/boots1.wav
sound/autonomy_lost/player/boots2.wav
sound/autonomy_lost/player/boots3.wav
sound/autonomy_lost/player/boots4.wav
sound/autonomy_lost/player/pl_organic1.wav
sound/autonomy_lost/player/pl_organic2.wav
sound/autonomy_lost/player/pl_organic3.wav
sound/autonomy_lost/player/pl_organic4.wav
sound/autonomy_lost/player/pl_snow1.wav
sound/autonomy_lost/player/pl_snow2.wav
sound/autonomy_lost/player/pl_snow3.wav
sound/autonomy_lost/player/pl_snow4.wav
sound/autonomy_lost/player/pl_step1.wav
sound/autonomy_lost/player/pl_step2.wav
sound/autonomy_lost/player/pl_step3.wav
sound/autonomy_lost/player/pl_step4.wav
sound/autonomy_lost/player/pl_tile1.wav
sound/autonomy_lost/player/pl_tile2.wav
sound/autonomy_lost/player/pl_tile3.wav
sound/autonomy_lost/player/pl_tile4.wav
sound/autonomy_lost/player/pl_tile5.wav
sound/autonomy_lost/player/pl_wood1.wav
sound/autonomy_lost/player/pl_wood2.wav
sound/autonomy_lost/player/pl_wood3.wav
sound/autonomy_lost/weapons/hks1.wav
sound/autonomy_lost/weapons/hks2.wav
sound/autonomy_lost/weapons/hks3.wav
sound/autonomy_lost/weapons/pl_gun3.wav
vendetta.wad

#server
models/cso_female_hands/black_glove/v_9mmar.mdl
models/cso_female_hands/black_glove/v_9mmhandgun.mdl
models/cso_female_hands/black_glove/v_357.mdl
models/cso_female_hands/black_glove/v_crossbow.mdl
models/cso_female_hands/black_glove/v_crowbar.mdl
models/cso_female_hands/black_glove/v_desert_eagle.mdl
models/cso_female_hands/black_glove/v_displacer.mdl
models/cso_female_hands/black_glove/v_egon.mdl
models/cso_female_hands/black_glove/v_gauss.mdl
models/cso_female_hands/black_glove/v_grenade.mdl
models/cso_female_hands/black_glove/v_m16a2.mdl
models/cso_female_hands/black_glove/v_m40a1.mdl
models/cso_female_hands/black_glove/v_medkit.mdl
models/cso_female_hands/black_glove/v_minigun.mdl
models/cso_female_hands/black_glove/v_pipe_wrench.mdl
models/cso_female_hands/black_glove/v_rpg.mdl
models/cso_female_hands/black_glove/v_satchel.mdl
models/cso_female_hands/black_glove/v_satchel_radio.mdl
models/cso_female_hands/black_glove/v_saw.mdl
models/cso_female_hands/black_glove/v_shotgun.mdl
models/cso_female_hands/black_glove/v_spore_launcher.mdl
models/cso_female_hands/black_glove/v_squeak.mdl
models/cso_female_hands/black_glove/v_tripmine.mdl
models/cso_female_hands/black_glove/v_uzi.mdl

// classic mode + knife
models/abeyance/v_knife.mdl
models/abeyance/v_desert_eagle.mdl
models/abeyance/v_saw.mdl

sprites/hl_weapons/weapon_hlpython.txt
sprites/hl_weapons/weapon_ofeagle.txt
sprites/hl_weapons/weapon_ofm249.txt
sprites/hl_weapons/weapon_ofshockrifle.txt

sound/hlclassic/weapons/desert_eagle_reload.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav