// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/2desertbk.bmp
gfx/env/2desertbk.tga
gfx/env/2desertdn.bmp
gfx/env/2desertdn.tga
gfx/env/2desertft.bmp
gfx/env/2desertft.tga
gfx/env/2desertlf.bmp
gfx/env/2desertlf.tga
gfx/env/2desertrt.bmp
gfx/env/2desertrt.tga
gfx/env/2desertup.bmp
gfx/env/2desertup.tga
gfx/env/alien1bk.bmp
gfx/env/alien1bk.tga
gfx/env/alien1dn.bmp
gfx/env/alien1dn.tga
gfx/env/alien1ft.bmp
gfx/env/alien1ft.tga
gfx/env/alien1lf.bmp
gfx/env/alien1lf.tga
gfx/env/alien1rt.bmp
gfx/env/alien1rt.tga
gfx/env/alien1up.bmp
gfx/env/alien1up.tga
gfx/env/blackbk.bmp
gfx/env/blackbk.tga
gfx/env/blackdn.bmp
gfx/env/blackdn.tga
gfx/env/blackft.bmp
gfx/env/blackft.tga
gfx/env/blacklf.bmp
gfx/env/blacklf.tga
gfx/env/blackrt.bmp
gfx/env/blackrt.tga
gfx/env/blackup.bmp
gfx/env/blackup.tga
gfx/env/desertbk.bmp
gfx/env/desertbk.tga
gfx/env/desertdn.bmp
gfx/env/desertdn.tga
gfx/env/desertft.bmp
gfx/env/desertft.tga
gfx/env/desertlf.bmp
gfx/env/desertlf.tga
gfx/env/desertrt.bmp
gfx/env/desertrt.tga
gfx/env/desertup.bmp
gfx/env/desertup.tga
gfx/env/duskbk.bmp
gfx/env/duskbk.tga
gfx/env/duskdn.bmp
gfx/env/duskdn.tga
gfx/env/duskft.bmp
gfx/env/duskft.tga
gfx/env/dusklf.bmp
gfx/env/dusklf.tga
gfx/env/duskrt.bmp
gfx/env/duskrt.tga
gfx/env/duskup.bmp
gfx/env/duskup.tga
gfx/env/morningbk.bmp
gfx/env/morningbk.tga
gfx/env/morningdn.bmp
gfx/env/morningdn.tga
gfx/env/morningft.bmp
gfx/env/morningft.tga
gfx/env/morninglf.bmp
gfx/env/morninglf.tga
gfx/env/morningrt.bmp
gfx/env/morningrt.tga
gfx/env/morningup.bmp
gfx/env/morningup.tga
gfx/env/sky_blu_bk.bmp
gfx/env/sky_blu_bk.tga
gfx/env/sky_blu_dn.bmp
gfx/env/sky_blu_dn.tga
gfx/env/sky_blu_ft.bmp
gfx/env/sky_blu_ft.tga
gfx/env/sky_blu_lf.bmp
gfx/env/sky_blu_lf.tga
gfx/env/sky_blu_rt.bmp
gfx/env/sky_blu_rt.tga
gfx/env/sky_blu_up.bmp
gfx/env/sky_blu_up.tga
gfx/env/xen10bk.tga
gfx/env/xen10dn.tga
gfx/env/xen10ft.tga
gfx/env/xen10lf.tga
gfx/env/xen10rt.tga
gfx/env/xen10up.tga
gfx/env/xen8bk.tga
gfx/env/xen8dn.tga
gfx/env/xen8ft.tga
gfx/env/xen8lf.tga
gfx/env/xen8rt.tga
gfx/env/xen8up.tga
gfx/env/xen9bk.bmp
gfx/env/xen9bk.tga
gfx/env/xen9dn.bmp
gfx/env/xen9dn.tga
gfx/env/xen9ft.bmp
gfx/env/xen9ft.tga
gfx/env/xen9lf.bmp
gfx/env/xen9lf.tga
gfx/env/xen9rt.bmp
gfx/env/xen9rt.tga
gfx/env/xen9up.bmp
gfx/env/xen9up.tga