// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/2desertbk.bmp
gfx/env/2desertbk.tga
gfx/env/2desertdn.bmp
gfx/env/2desertdn.tga
gfx/env/2desertft.bmp
gfx/env/2desertft.tga
gfx/env/2desertlf.bmp
gfx/env/2desertlf.tga
gfx/env/2desertrt.bmp
gfx/env/2desertrt.tga
gfx/env/2desertup.bmp
gfx/env/2desertup.tga
gfx/env/alien1bk.bmp
gfx/env/alien1bk.tga
gfx/env/alien1dn.bmp
gfx/env/alien1dn.tga
gfx/env/alien1ft.bmp
gfx/env/alien1ft.tga
gfx/env/alien1lf.bmp
gfx/env/alien1lf.tga
gfx/env/alien1rt.bmp
gfx/env/alien1rt.tga
gfx/env/alien1up.bmp
gfx/env/alien1up.tga
gfx/env/blackbk.bmp
gfx/env/blackbk.tga
gfx/env/blackdn.bmp
gfx/env/blackdn.tga
gfx/env/blackft.bmp
gfx/env/blackft.tga
gfx/env/blacklf.bmp
gfx/env/blacklf.tga
gfx/env/blackrt.bmp
gfx/env/blackrt.tga
gfx/env/blackup.bmp
gfx/env/blackup.tga
gfx/env/desertbk.bmp
gfx/env/desertbk.tga
gfx/env/desertdn.bmp
gfx/env/desertdn.tga
gfx/env/desertft.bmp
gfx/env/desertft.tga
gfx/env/desertlf.bmp
gfx/env/desertlf.tga
gfx/env/desertrt.bmp
gfx/env/desertrt.tga
gfx/env/desertup.bmp
gfx/env/desertup.tga
gfx/env/duskbk.bmp
gfx/env/duskbk.tga
gfx/env/duskdn.bmp
gfx/env/duskdn.tga
gfx/env/duskft.bmp
gfx/env/duskft.tga
gfx/env/dusklf.bmp
gfx/env/dusklf.tga
gfx/env/duskrt.bmp
gfx/env/duskrt.tga
gfx/env/duskup.bmp
gfx/env/duskup.tga
gfx/env/morningbk.bmp
gfx/env/morningbk.tga
gfx/env/morningdn.bmp
gfx/env/morningdn.tga
gfx/env/morningft.bmp
gfx/env/morningft.tga
gfx/env/morninglf.bmp
gfx/env/morninglf.tga
gfx/env/morningrt.bmp
gfx/env/morningrt.tga
gfx/env/morningup.bmp
gfx/env/morningup.tga
gfx/env/sky_blu_bk.bmp
gfx/env/sky_blu_bk.tga
gfx/env/sky_blu_dn.bmp
gfx/env/sky_blu_dn.tga
gfx/env/sky_blu_ft.bmp
gfx/env/sky_blu_ft.tga
gfx/env/sky_blu_lf.bmp
gfx/env/sky_blu_lf.tga
gfx/env/sky_blu_rt.bmp
gfx/env/sky_blu_rt.tga
gfx/env/sky_blu_up.bmp
gfx/env/sky_blu_up.tga
gfx/env/xen10bk.tga
gfx/env/xen10dn.tga
gfx/env/xen10ft.tga
gfx/env/xen10lf.tga
gfx/env/xen10rt.tga
gfx/env/xen10up.tga
gfx/env/xen8bk.tga
gfx/env/xen8dn.tga
gfx/env/xen8ft.tga
gfx/env/xen8lf.tga
gfx/env/xen8rt.tga
gfx/env/xen8up.tga
gfx/env/xen9bk.bmp
gfx/env/xen9bk.tga
gfx/env/xen9dn.bmp
gfx/env/xen9dn.tga
gfx/env/xen9ft.bmp
gfx/env/xen9ft.tga
gfx/env/xen9lf.bmp
gfx/env/xen9lf.tga
gfx/env/xen9rt.bmp
gfx/env/xen9rt.tga
gfx/env/xen9up.bmp
gfx/env/xen9up.tga

//server
models/barneyhands/v_9mmar.mdl
models/barneyhands/v_9mmhandgun.mdl
models/barneyhands/v_357.mdl
models/barneyhands/v_crossbow.mdl
models/barneyhands/v_crowbar.mdl
models/barneyhands/v_egon.mdl
models/barneyhands/v_gauss.mdl
models/barneyhands/v_grenade.mdl
models/barneyhands/v_rpg.mdl
models/barneyhands/v_satchel.mdl
models/barneyhands/v_satchel_radio.mdl
models/barneyhands/v_shotgun.mdl
models/barneyhands/v_squeak.mdl
models/barneyhands/v_tripmine.mdl
models/barneyhands/v_desert_eagle.mdl
models/barneyhands/v_displacer.mdl
models/barneyhands/v_m16a2.mdl
models/barneyhands/v_m40a1.mdl
models/barneyhands/v_medkit.mdl
models/barneyhands/v_pipe_wrench.mdl
models/barneyhands/v_saw.mdl
models/barneyhands/v_spore_launcher.mdl
models/barneyhands/v_uzi.mdl

models/bshift/sd/barney.mdl
models/bshift/sd/gman.mdl
models/bshift/sd/hgrunt.mdl
models/bshift/sd/houndeye.mdl
models/bshift/sd/scientist.mdl
models/bshift/sd/zombie.mdl

models/bshift/sd/v_9mmar.mdl
models/bshift/sd/v_9mmhandgun.mdl
models/bshift/sd/v_357.mdl
models/bshift/sd/v_crossbow.mdl
models/bshift/sd/v_crowbar.mdl
models/bshift/sd/v_egon.mdl
models/bshift/sd/v_gauss.mdl
models/bshift/sd/v_grenade.mdl
models/bshift/sd/v_hgun.mdl
models/bshift/sd/v_medkit.mdl
models/bshift/sd/v_rpg.mdl
models/bshift/sd/v_satchel.mdl
models/bshift/sd/v_satchel_radio.mdl
models/bshift/sd/v_shotgun.mdl
models/bshift/sd/v_squeak.mdl
models/bshift/sd/v_tripmine.mdl

//opfor + svencoop classic weapons plugins

models/valve/sd/p_desert_eagle.mdl
models/valve/sd/p_m40a1.mdl
models/valve/sd/p_saw.mdl
models/valve/sd/p_shock.mdl

models/bshift/sd/v_desert_eagle.mdl
models/bshift/sd/v_m40a1.mdl
models/bshift/sd/v_saw.mdl
models/valve/sd/v_shock.mdl

models/valve/sd/w_desert_eagle.mdl
models/valve/sd/w_m40a1.mdl
models/valve/sd/w_m40a1clip.mdl
models/valve/sd/w_saw.mdl
models/valve/sd/w_saw_clip.mdl
models/valve/sd/w_shock.mdl
models/valve/sd/w_shock_rifle.mdl

models/valve/sd/saw_shell.mdl
models/valve/sd/shell.mdl

sprites/opfor/weapon_knife.spr
sprites/opfor/weapon_knife.txt
sprites/opfor/weapon_penguin.spr
sprites/opfor/weapon_penguin.txt

sprites/hl_weapons/weapon_hlpython.txt
sprites/hl_weapons/weapon_ofeagle.txt
sprites/hl_weapons/weapon_ofm249.txt
sprites/hl_weapons/weapon_ofshockrifle.txt
sprites/hl_weapons/weapon_ofsniperrifle.txt

sound/hlclassic/weapons/desert_eagle_reload.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav