// back_whispers_3.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (68):
back_whispers.wad
barney.wad
CHANGELEVEL.wad
decals.wad
decay.wad
dmc.wad
gfx/env/cobblebk.tga
gfx/env/cobbledn.tga
gfx/env/cobbleft.tga
gfx/env/cobblelf.tga
gfx/env/cobblert.tga
gfx/env/cobbleup.tga
halflife.wad
liquids.wad
models/back_whsp/cars/2_cheap_delivery_truck_white.mdl
models/back_whsp/cars/2_euro_sedan_bluegrey.mdl
models/back_whsp/cars/2_humvee_camo.mdl
models/back_whsp/flora/bush.mdl
models/back_whsp/flora/k_bush1.mdl
models/back_whsp/furnitures/leather_couch_brown.mdl
models/back_whsp/furnitures/wb_seat.mdl
models/back_whsp/others/electric_wire1.mdl
models/back_whsp/others/gonome.mdl
models/back_whsp/others/hgrunt.mdl
models/back_whsp/others/massn.mdl
models/back_whsp/others/shoes_s.mdl
models/osprey.mdl
op4ctf.wad
Opfor.wad
sound/ambience/des_wind2.wav
sound/ambience/des_wind3.wav
sound/ambience/distantmortar2.wav
sound/ambience/distantmortar3.wav
sound/ambience/fluorescent.wav
sound/ambience/water_flowing3.wav
sound/ambience/waterfall2.wav
sound/apache/ap_rotor4.wav
sound/back_whsp/time/c4_plant.wav
sound/buttons/bell1.wav
sound/buttons/button2.wav
sound/buttons/button6.wav
sound/buttons/latchlocked1.wav
sound/buttons/latchunlocked1.wav
sound/common/nuke_explode.wav
sound/debris/wood1.wav
sound/debris/wood2.wav
sound/debris/wood3.wav
sound/doors/doormove10.wav
sound/doors/doormove6.wav
sound/doors/doormove8.wav
sound/doors/doorstop6.wav
sound/doors/doorstop8.wav
sound/fgrunt/hellout.wav
sound/misc/secret.wav
sound/plats/squeekstop1.wav
sound/thunder.wav
sound/vox/access.wav
sound/vox/denied.wav
sound/back_whsp/ambient/ambientinsiderain.ogg
sound/back_whsp/ambient/ambientoutsidecrickets.ogg
sound/back_whsp/ambient/lv0br.ogg
sound/back_whsp/ambient/pz_ambientoutsiderain.ogg
sound/back_whsp/music/regenesis_title.ogg
sound/back_whsp/music/tpwt.ogg
sound/back_whsp/music/vlbiitsm64.ogg
sound/back_whsp/others/garage_open_1.ogg
sound/back_whsp/others/garage_open_2.ogg
sound/back_whsp/others/mc_close.ogg
sound/back_whsp/others/mc_open.ogg
sound/back_whsp/others/superholy.ogg
sound/back_whsp/time/c4_beep1.ogg
sound/back_whsp/time/c4_beep2.ogg
sound/back_whsp/time/c4_beep3.ogg
sound/back_whsp/time/c4_beep4.ogg
sound/back_whsp/time/c4_beep5.ogg
sound/back_whsp/voice/outro.ogg
sprites/adamr/pointers/pointer-use.spr
sprites/back_whsp/bw_ripples.spr
sprites/fire.spr
sprites/flare2.spr
sprites/glow04.spr
sprites/laserbeam.spr
sprites/xsmoke1.spr
tfc.WAD
tfc2.wad
xeno.wad
