// back_whispers_1.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (97):
back_whispers.wad
barney.wad
CHANGELEVEL.wad
decals.wad
decay.wad
dmc.wad
gfx/env/cobblebk.tga
gfx/env/cobbledn.tga
gfx/env/cobbleft.tga
gfx/env/cobblelf.tga
gfx/env/cobblert.tga
gfx/env/cobbleup.tga
halflife.wad
liquids.wad
models/back_whsp/cars/2_cheap_delivery_truck_white.mdl
models/back_whsp/cars/2_factory_handtruck2.mdl
models/back_whsp/cars/2_generator_yellow.mdl
models/back_whsp/cars/2_humvee_camo.mdl
models/back_whsp/cars/2_humvee_camo_gun.mdl
models/back_whsp/cars/2_military_flac_cannon.mdl
models/back_whsp/furnitures/chair_1.mdl
models/back_whsp/furnitures/chair_2_cp.mdl
models/back_whsp/furnitures/curtains.mdl
models/back_whsp/furnitures/Desk_1.mdl
models/back_whsp/furnitures/group-hotel01.mdl
models/back_whsp/furnitures/leather_couch_brown.mdl
models/back_whsp/furnitures/table_1.mdl
models/back_whsp/furnitures/wb_seat.mdl
models/back_whsp/others/by_boat_metal_idle.mdl
models/back_whsp/others/electric_wire1.mdl
models/back_whsp/others/idlemortarshell.mdl
models/back_whsp/weapons/p_goldpipe_wrench.mdl
models/back_whsp/weapons/v_goldpipe_wrench.mdl
models/back_whsp/weapons/w_goldpipe_wrench.mdl
models/osprey.mdl
models/skeleton.mdl
op4ctf.wad
Opfor.wad
sound/ambience/alien_beacon.wav
sound/ambience/alien_squit.wav
sound/ambience/aliencave1.wav
sound/ambience/biggun3.wav
sound/ambience/bigwarning.wav
sound/ambience/des_wind3.wav
sound/ambience/distantmortar1.wav
sound/ambience/distantmortar2.wav
sound/ambience/drips.wav
sound/ambience/flies.wav
sound/ambience/fluorescent.wav
sound/ambience/industrial4.wav
sound/ambience/jetflyby1.wav
sound/ambience/mgun_burst3.wav
sound/ambience/rifle1.wav
sound/ambience/rifle2.wav
sound/ambience/steamjet1.wav
sound/ambience/water_flowing2.wav
sound/ambience/water_flowing3.wav
sound/ambience/waterfall2.wav
sound/ambience/wind2.wav
sound/apache/ap_rotor4.wav
sound/buttons/bell1.wav
sound/buttons/button2.wav
sound/buttons/button4.wav
sound/buttons/button6.wav
sound/buttons/latchlocked1.wav
sound/buttons/latchlocked2.wav
sound/debris/bustmetal2.wav
sound/doors/doormove10.wav
sound/doors/doormove6.wav
sound/doors/doormove8.wav
sound/doors/doorstop6.wav
sound/doors/doorstop8.wav
sound/fgrunt/secure.wav
sound/fgrunt/stand.wav
sound/fgrunt/takecover.wav
sound/misc/ear_ringing.wav
sound/misc/secret.wav
sound/misc/wind2.wav
sound/thunder.wav
sound/vox/access.wav
sound/vox/denied.wav
sound/back_whsp/ambient/ambientinsiderain.ogg
sound/back_whsp/ambient/ambientoutsidecrickets.ogg
sound/back_whsp/ambient/pz_ambientoutsiderain.ogg
sound/back_whsp/music/tpwt.ogg
sound/back_whsp/time/5s_etqw.ogg
sound/back_whsp/time/10s_etqw.ogg
sound/back_whsp/time/30s_etqw.ogg
sound/back_whsp/voice/intro.ogg
sprites/adamr/pointers/pointer-blast.spr
sprites/ba_gun2.spr
sprites/ballsmoke.spr
sprites/fire.spr
sprites/fire01.spr
sprites/flare2.spr
sprites/glow01.spr
sprites/glow02.spr
sprites/glow03.spr
sprites/glow04.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/xsmoke1.spr
tfc.WAD
tfc2.wad
xeno.wad
