// back_whispers_2.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (61):
back_whispers.wad
barney.wad
CHANGELEVEL.wad
decals.wad
decay.wad
dmc.wad
gfx/env/cobblebk.tga
gfx/env/cobbledn.tga
gfx/env/cobbleft.tga
gfx/env/cobblelf.tga
gfx/env/cobblert.tga
gfx/env/cobbleup.tga
halflife.wad
liquids.wad
models/back_whsp/cars/2_cheap_delivery_truck_white.mdl
models/back_whsp/cars/2_cheap_delivery_truck_whiteb.mdl
models/back_whsp/cars/2_euro_sedan_bluegrey.mdl
models/back_whsp/cars/2_flatbed_covered_blue.mdl
models/back_whsp/cars/2_humvee_camo.mdl
models/back_whsp/cars/2_military_flac_cannon.mdl
models/back_whsp/flora/bush.mdl
models/back_whsp/flora/pi_tree3.mdl
models/back_whsp/furnitures/bench3.mdl
models/back_whsp/furnitures/chair_1.mdl
models/back_whsp/furnitures/chair_2_cp.mdl
models/back_whsp/furnitures/curtains.mdl
models/back_whsp/furnitures/group-hotel01.mdl
models/back_whsp/furnitures/leather_couch_brown.mdl
models/back_whsp/others/pz_chips.mdl
models/back_whsp/others/star_s.mdl
models/back_whsp/weapons/p_pz_crowbar.mdl
models/back_whsp/weapons/v_pz_crowbar.mdl
models/back_whsp/weapons/w_pz_crowbar.mdl
op4ctf.wad
Opfor.wad
sound/ambience/biggun3.wav
sound/ambience/fluorescent.wav
sound/ambience/turretrot1.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall2.wav
sound/back_whsp/others/pz_eating.wav
sound/buttons/button2.wav
sound/buttons/button6.wav
sound/buttons/latchlocked1.wav
sound/doors/doormove10.wav
sound/doors/doormove6.wav
sound/doors/doorstop6.wav
sound/misc/doors_shut.wav
sound/misc/secret.wav
sound/back_whsp/ambient/ambientinsiderain.ogg
sound/back_whsp/ambient/ambientoutsidecrickets.ogg
sound/back_whsp/ambient/lv0br.ogg
sound/back_whsp/ambient/pz_ambientoutsiderain.ogg
sound/back_whsp/music/regenesis_title.ogg
sound/back_whsp/music/tpwt.ogg
sound/back_whsp/music/vlbiitsm64.ogg
sound/back_whsp/others/garage_open_1.ogg
sound/back_whsp/others/garage_open_2.ogg
sound/back_whsp/others/mc_close.ogg
sound/back_whsp/others/mc_open.ogg
sound/back_whsp/others/superholy.ogg
sprites/back_whsp/bw_ripples.spr
sprites/black_smoke3.spr
sprites/fire.spr
sprites/flare2.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/wep_smoke_01.spr
sprites/xsmoke1.spr
tfc.WAD
tfc2.wad
xeno.wad
