// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/blkops/v_357.mdl
models/blkops/v_9mmar.mdl
models/blkops/v_9mmhandgun.mdl
models/blkops/v_chub.mdl
models/blkops/v_crossbow.mdl
models/blkops/v_crowbar.mdl
models/blkops/v_desert_eagle.mdl
models/blkops/v_displacer.mdl
models/blkops/v_egon.mdl
models/blkops/v_gauss.mdl
models/blkops/v_grenade.mdl
models/blkops/v_m16a2.mdl
models/blkops/v_m40a1.mdl
models/blkops/v_medkit.mdl
models/blkops/v_pipe_wrench.mdl
models/blkops/v_rpg.mdl
models/blkops/v_satchel.mdl
models/blkops/v_satchel_radio.mdl
models/blkops/v_saw.mdl
models/blkops/v_shotgun.mdl
models/blkops/v_spore_launcher.mdl
models/blkops/v_squeak.mdl
models/blkops/v_tripmine.mdl
models/blkops/v_uzi.mdl
models/player/aswatblack/aswatblack.bmp
models/player/aswatblack/aswatblack.mdl
models/player/bodyguard/bodyguard.bmp
models/player/bodyguard/bodyguard.mdl
models/player/bodyguard2/bodyguard2.bmp
models/player/bodyguard2/bodyguard2.mdl
models/player/massn_black/massn_black.bmp
models/player/massn_black/massn_black.mdl
models/player/splintercell/splintercell.bmp
models/player/splintercell/splintercell.mdl
models/player/splintercell_red/splintercell_red.bmp
models/player/splintercell_red/splintercell_red.mdl

//server
models/blkops/sd/v_9mmar.mdl
models/blkops/sd/v_9mmhandgun.mdl
models/blkops/sd/v_357.mdl
models/blkops/sd/v_chub.mdl
models/blkops/sd/v_crossbow.mdl
models/blkops/sd/v_crowbar.mdl
models/blkops/sd/v_desert_eagle.mdl
models/blkops/sd/v_displacer.mdl
models/blkops/sd/v_egon.mdl
models/blkops/sd/v_gauss.mdl
models/blkops/sd/v_grenade.mdl
models/blkops/sd/v_knife.mdl
models/blkops/sd/v_m40a1.mdl
models/blkops/sd/v_medkit.mdl
models/blkops/sd/v_minigun.mdl
models/blkops/sd/v_pipe_wrench.mdl
models/blkops/sd/v_rpg.mdl
models/blkops/sd/v_satchel.mdl
models/blkops/sd/v_satchel_radio.mdl
models/blkops/sd/v_saw.mdl
models/blkops/sd/v_shotgun.mdl
models/blkops/sd/v_spore_launcher.mdl
models/blkops/sd/v_squeak.mdl
models/blkops/sd/v_tripmine.mdl
models/blkops/sd/v_uzi.mdl

models/valve/sd/saw_shell.mdl
models/valve/sd/shell.mdl

sprites/hl_weapons/weapon_hlpython.txt
sprites/hl_weapons/weapon_ofeagle.txt
sprites/hl_weapons/weapon_ofm249.txt
sprites/hl_weapons/weapon_ofshockrifle.txt
sprites/hl_weapons/weapon_ofsniperrifle.txt

sound/hlclassic/weapons/desert_eagle_reload.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav