// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

bopfor.wad
sound/bootsquad/pcv_vest.wav
sound/scmod/bs/dialogs/bootlegsquad_a1/1sniper_r.ogg
sprites/opfor/weapon_knife.spr
sprites/opfor/weapon_knife.txt

//sound sentences spanish
sound/sentences/beep.wav
sound/sentences/bell.wav
sound/sentences/bizwarn.wav
sound/sentences/blip.wav
sound/sentences/bloop.wav
sound/sentences/boop.wav
sound/sentences/buzwarn.wav
sound/sentences/c1a0_0.wav
sound/sentences/c1a0_1.wav
sound/sentences/c1a0_2.wav
sound/sentences/c1a0_3.wav
sound/sentences/c1a0_4.wav
sound/sentences/c1a0_5.wav
sound/sentences/c1a0_6.wav
sound/sentences/c1a0_7.wav
sound/sentences/c1a0_8.wav
sound/sentences/c1a0_9.wav
sound/sentences/c1a0_10.wav
sound/sentences/c1a0_11.wav
sound/sentences/c1a0_12.wav
sound/sentences/c1a0_13.wav
sound/sentences/c1a0_14.wav
sound/sentences/c1a0_15.wav
sound/sentences/c1a0_16.wav
sound/sentences/c1a0_17.wav
sound/sentences/c1a0_18.wav
sound/sentences/c1a0_19.wav
sound/sentences/c1a0_20.wav
sound/sentences/c1a0_21.wav
sound/sentences/c1a0_22.wav
sound/sentences/c1a1_0.wav
sound/sentences/c1a1_1.wav
sound/sentences/c1a1_2.wav
sound/sentences/c1a1_3.wav
sound/sentences/c1a1_4.wav
sound/sentences/c1a1_5.wav
sound/sentences/c1a1_6.wav
sound/sentences/c1a1_7.wav
sound/sentences/c1a1_8.wav
sound/sentences/c1a1_9.wav
sound/sentences/c1a1_10.wav
sound/sentences/c1a1_11.wav
sound/sentences/c1a2_0.wav
sound/sentences/c1a2_1.wav
sound/sentences/c1a2_2.wav
sound/sentences/c1a2_3.wav
sound/sentences/c1a2_4.wav
sound/sentences/c1a2_5.wav
sound/sentences/c1a2_6.wav
sound/sentences/c1a2_7.wav
sound/sentences/c1a2_8.wav
sound/sentences/c1a2_9.wav
sound/sentences/c1a2_10.wav
sound/sentences/c1a2_11.wav
sound/sentences/c1a3_0.wav
sound/sentences/c1a3_1.wav
sound/sentences/c1a3_2.wav
sound/sentences/c1a3_3.wav
sound/sentences/c1a3_4.wav
sound/sentences/c1a3_5.wav
sound/sentences/c1a3_6.wav
sound/sentences/c1a3_7.wav
sound/sentences/c1a3_8.wav
sound/sentences/c1a3_9.wav
sound/sentences/c1a3_10.wav
sound/sentences/c1a3_lock.wav
sound/sentences/c1a3_warn.wav
sound/sentences/c1a4_0.wav
sound/sentences/c1a4_1.wav
sound/sentences/c1a4_2.wav
sound/sentences/c1a4_3.wav
sound/sentences/c1a4_4.wav
sound/sentences/c1a4_5.wav
sound/sentences/c1a4_6.wav
sound/sentences/c1a4_7.wav
sound/sentences/c1a4_8.wav
sound/sentences/c2a1_0.wav
sound/sentences/c2a1_1.wav
sound/sentences/c2a1_2.wav
sound/sentences/c2a1_3.wav
sound/sentences/c2a1_4.wav
sound/sentences/c2a1_5.wav
sound/sentences/c2a1_6.wav
sound/sentences/c2a1_7.wav
sound/sentences/c2a1_8.wav
sound/sentences/c2a2_0.wav
sound/sentences/c2a2_1.wav
sound/sentences/c2a2_2.wav
sound/sentences/c2a2_3.wav
sound/sentences/c2a2_4.wav
sound/sentences/c2a2_5.wav
sound/sentences/c2a2_6.wav
sound/sentences/c2a2_7.wav
sound/sentences/c2a2_8.wav
sound/sentences/c2a2_launch.wav
sound/sentences/c2a4_0.wav
sound/sentences/c2a4_1.wav
sound/sentences/c2a4_2.wav
sound/sentences/c2a4_3.wav
sound/sentences/c2a4_4.wav
sound/sentences/c2a4_5.wav
sound/sentences/c2a4_6.wav
sound/sentences/c2a4_7.wav
sound/sentences/c2a4_8.wav
sound/sentences/c2a4_9.wav
sound/sentences/c2a4_10.wav
sound/sentences/c2a4_11.wav
sound/sentences/c2a4_12.wav
sound/sentences/c2a4_ster.wav
sound/sentences/c3a1_0.wav
sound/sentences/c3a1_1.wav
sound/sentences/c3a1_2.wav
sound/sentences/c3a1_3.wav
sound/sentences/c3a1_4.wav
sound/sentences/c3a1_5.wav
sound/sentences/c3a1_6.wav
sound/sentences/c3a1_7.wav
sound/sentences/c3a1_8.wav
sound/sentences/c3a1_9.wav
sound/sentences/c3a2_0.wav
sound/sentences/c3a2_1.wav
sound/sentences/c3a2_2.wav
sound/sentences/c3a2_3.wav
sound/sentences/c3a2_4.wav
sound/sentences/c3a2_5.wav
sound/sentences/c3a2_6.wav
sound/sentences/c3a2_7.wav
sound/sentences/c3a2_core.wav
sound/sentences/c3a2_target.wav
sound/sentences/crossdoor.wav
sound/sentences/ctr0.wav
sound/sentences/ctr1.wav
sound/sentences/ctr2.wav
sound/sentences/ctr3.wav
sound/sentences/ctr4.wav
sound/sentences/ctr5.wav
sound/sentences/ctr6.wav
sound/sentences/ctr7.wav
sound/sentences/ctr8.wav
sound/sentences/ctr9.wav
sound/sentences/ctr10.wav
sound/sentences/ctr11.wav
sound/sentences/ctr12.wav
sound/sentences/ctr13.wav
sound/sentences/ctr14.wav
sound/sentences/ctr15.wav
sound/sentences/ctr16.wav
sound/sentences/ctr17.wav
sound/sentences/ctr18.wav
sound/sentences/ctr19.wav
sound/sentences/ctr20.wav
sound/sentences/dadeda.wav
sound/sentences/db0.wav
sound/sentences/db1.wav
sound/sentences/db2.wav
sound/sentences/db3.wav
sound/sentences/dc0.wav
sound/sentences/dc1.wav
sound/sentences/dc2.wav
sound/sentences/dc3.wav
sound/sentences/dc4.wav
sound/sentences/deeoo.wav
sound/sentences/doop.wav
sound/sentences/dr0.wav
sound/sentences/dr1.wav
sound/sentences/dr2.wav
sound/sentences/dr3.wav
sound/sentences/dr4.wav
sound/sentences/ea0.wav
sound/sentences/ea1.wav
sound/sentences/ea2.wav
sound/sentences/ea3.wav
sound/sentences/ea4.wav
sound/sentences/ea5.wav
sound/sentences/ea6.wav
sound/sentences/ea7.wav
sound/sentences/ea8.wav
sound/sentences/echem0.wav
sound/sentences/econ0.wav
sound/sentences/ed0.wav
sound/sentences/ed1.wav
sound/sentences/ed2.wav
sound/sentences/ed3.wav
sound/sentences/ed4.wav
sound/sentences/ed5.wav
sound/sentences/ed6.wav
sound/sentences/ef0.wav
sound/sentences/ef1.wav
sound/sentences/ef3.wav
sound/sentences/efire0.wav
sound/sentences/eh0.wav
sound/sentences/eh1.wav
sound/sentences/erad0.wav
sound/sentences/fuel_off.wav
sound/sentences/fuzz.wav
sound/sentences/greendoor.wav
sound/sentences/greendoor2.wav
sound/sentences/hev_0p.wav
sound/sentences/hev_1p.wav
sound/sentences/hev_2p.wav
sound/sentences/hev_3p.wav
sound/sentences/hev_4p.wav
sound/sentences/hev_5p.wav
sound/sentences/hev_6p.wav
sound/sentences/hev_7p.wav
sound/sentences/hev_8p.wav
sound/sentences/hev_9mm.wav
sound/sentences/hev_9p.wav
sound/sentences/hev_10p.wav
sound/sentences/hev_11p.wav
sound/sentences/hev_12p.wav
sound/sentences/hev_13p.wav
sound/sentences/hev_14p.wav
sound/sentences/hev_15p.wav
sound/sentences/hev_16p.wav
sound/sentences/hev_17p.wav
sound/sentences/hev_18p.wav
sound/sentences/hev_19p.wav
sound/sentences/hev_44ammo.wav
sound/sentences/hev_44pistol.wav
sound/sentences/hev_a0.wav
sound/sentences/hev_a1.wav
sound/sentences/hev_a2.wav
sound/sentences/hev_a3.wav
sound/sentences/hev_a4.wav
sound/sentences/hev_a5.wav
sound/sentences/hev_a6.wav
sound/sentences/hev_a7.wav
sound/sentences/hev_a8.wav
sound/sentences/hev_a9.wav
sound/sentences/hev_a10.wav
sound/sentences/hev_agrenade.wav
sound/sentences/hev_aim_off.wav
sound/sentences/hev_aim_on.wav
sound/sentences/hev_amo0.wav
sound/sentences/hev_assault.wav
sound/sentences/hev_battery.wav
sound/sentences/hev_bolts.wav
sound/sentences/hev_buckshot.wav
sound/sentences/hev_c1.wav
sound/sentences/hev_c1t.wav
sound/sentences/hev_c2.wav
sound/sentences/hev_c3.wav
sound/sentences/hev_c4.wav
sound/sentences/hev_c5.wav
sound/sentences/hev_c6.wav
sound/sentences/hev_c7.wav
sound/sentences/hev_c8.wav
sound/sentences/hev_c9.wav
sound/sentences/hev_c10.wav
sound/sentences/hev_c11.wav
sound/sentences/hev_c12.wav
sound/sentences/hev_c13t.wav
sound/sentences/hev_c17.wav
sound/sentences/hev_c18.wav
sound/sentences/hev_c19.wav
sound/sentences/hev_c20.wav
sound/sentences/hev_c21.wav
sound/sentences/hev_c22.wav
sound/sentences/hev_c23.wav
sound/sentences/hev_c24.wav
sound/sentences/hev_det0.wav
sound/sentences/hev_det1.wav
sound/sentences/hev_det2.wav
sound/sentences/hev_det3.wav
sound/sentences/hev_det4.wav
sound/sentences/hev_det5.wav
sound/sentences/hev_dmg0.wav
sound/sentences/hev_dmg1.wav
sound/sentences/hev_dmg2.wav
sound/sentences/hev_dmg3.wav
sound/sentences/hev_dmg4.wav
sound/sentences/hev_dmg5.wav
sound/sentences/hev_dmg6.wav
sound/sentences/hev_dmg7.wav
sound/sentences/hev_e0.wav
sound/sentences/hev_e1.wav
sound/sentences/hev_e2.wav
sound/sentences/hev_e3.wav
sound/sentences/hev_e4.wav
sound/sentences/hev_e5.wav
sound/sentences/hev_egon.wav
sound/sentences/hev_egonpower.wav
sound/sentences/hev_f1.wav
sound/sentences/hev_f2.wav
sound/sentences/hev_f3.wav
sound/sentences/hev_f4.wav
sound/sentences/hev_f5.wav
sound/sentences/hev_f6.wav
sound/sentences/hev_f7.wav
sound/sentences/hev_f8.wav
sound/sentences/hev_f9.wav
sound/sentences/hev_f10.wav
sound/sentences/hev_f15.wav
sound/sentences/hev_f20.wav
sound/sentences/hev_f30.wav
sound/sentences/hev_fire.wav
sound/sentences/hev_gauss.wav
sound/sentences/hev_gr0.wav
sound/sentences/hev_gr1.wav
sound/sentences/hev_gr2.wav
sound/sentences/hev_gr3.wav
sound/sentences/hev_gr4.wav
sound/sentences/hev_gr5.wav
sound/sentences/hev_gr6.wav
sound/sentences/hev_gr7.wav
sound/sentences/hev_gr8.wav
sound/sentences/hev_gr9.wav
sound/sentences/hev_gr10.wav
sound/sentences/hev_gr11.wav
sound/sentences/hev_gr12.wav
sound/sentences/hev_gr13.wav
sound/sentences/hev_gr14.wav
sound/sentences/hev_gr15.wav
sound/sentences/hev_gr16.wav
sound/sentences/hev_gr17.wav
sound/sentences/hev_gr18.wav
sound/sentences/hev_grenade.wav
sound/sentences/hev_heal0.wav
sound/sentences/hev_heal1.wav
sound/sentences/hev_heal2.wav
sound/sentences/hev_heal3.wav
sound/sentences/hev_heal4.wav
sound/sentences/hev_heal5.wav
sound/sentences/hev_heal6.wav
sound/sentences/hev_heal7.wav
sound/sentences/hev_heal8.wav
sound/sentences/hev_hlth0.wav
sound/sentences/hev_hlth1.wav
sound/sentences/hev_hlth2.wav
sound/sentences/hev_hlth3.wav
sound/sentences/hev_hlth4.wav
sound/sentences/hev_hlth5.wav
sound/sentences/hev_hlth6.wav
sound/sentences/hev_hornet.wav
sound/sentences/hev_med0.wav
sound/sentences/hev_med1.wav
sound/sentences/hev_med2.wav
sound/sentences/hev_medkit.wav
sound/sentences/hev_pistol.wav
sound/sentences/hev_rpg.wav
sound/sentences/hev_rpgammo.wav
sound/sentences/hev_satchel.wav
sound/sentences/hev_shock.wav
sound/sentences/hev_shotgun.wav
sound/sentences/hev_squeek.wav
sound/sentences/hev_tripmine.wav
sound/sentences/hev_v0.wav
sound/sentences/hev_v1.wav
sound/sentences/hev_xbow.wav
sound/sentences/hg_alert0.wav
sound/sentences/hg_alert1.wav
sound/sentences/hg_alert2.wav
sound/sentences/hg_alert3.wav
sound/sentences/hg_alert4.wav
sound/sentences/hg_alert5.wav
sound/sentences/hg_alert6.wav
sound/sentences/hg_answer0.wav
sound/sentences/hg_answer1.wav
sound/sentences/hg_answer2.wav
sound/sentences/hg_answer3.wav
sound/sentences/hg_answer4.wav
sound/sentences/hg_answer5.wav
sound/sentences/hg_answer6.wav
sound/sentences/hg_charge0.wav
sound/sentences/hg_charge1.wav
sound/sentences/hg_charge2.wav
sound/sentences/hg_charge3.wav
sound/sentences/hg_check0.wav
sound/sentences/hg_check1.wav
sound/sentences/hg_check2.wav
sound/sentences/hg_check3.wav
sound/sentences/hg_check4.wav
sound/sentences/hg_check5.wav
sound/sentences/hg_check6.wav
sound/sentences/hg_check7.wav
sound/sentences/hg_clear0.wav
sound/sentences/hg_clear1.wav
sound/sentences/hg_clear2.wav
sound/sentences/hg_clear3.wav
sound/sentences/hg_clear4.wav
sound/sentences/hg_clear5.wav
sound/sentences/hg_clear6.wav
sound/sentences/hg_clear7.wav
sound/sentences/hg_clear8.wav
sound/sentences/hg_clear9.wav
sound/sentences/hg_clear10.wav
sound/sentences/hg_clear11.wav
sound/sentences/hg_clear12.wav
sound/sentences/hg_cover0.wav
sound/sentences/hg_cover1.wav
sound/sentences/hg_cover2.wav
sound/sentences/hg_cover3.wav
sound/sentences/hg_cover4.wav
sound/sentences/hg_cover5.wav
sound/sentences/hg_cover6.wav
sound/sentences/hg_cover7.wav
sound/sentences/hg_gren0.wav
sound/sentences/hg_gren1.wav
sound/sentences/hg_gren2.wav
sound/sentences/hg_gren3.wav
sound/sentences/hg_gren4.wav
sound/sentences/hg_gren5.wav
sound/sentences/hg_gren6.wav
sound/sentences/hg_idle0.wav
sound/sentences/hg_idle1.wav
sound/sentences/hg_idle2.wav
sound/sentences/hg_idle3.wav
sound/sentences/hg_monst1.wav
sound/sentences/hg_monst2.wav
sound/sentences/hg_monst3.wav
sound/sentences/hg_quest0.wav
sound/sentences/hg_quest1.wav
sound/sentences/hg_quest2.wav
sound/sentences/hg_quest3.wav
sound/sentences/hg_quest4.wav
sound/sentences/hg_quest5.wav
sound/sentences/hg_quest6.wav
sound/sentences/hg_quest7.wav
sound/sentences/hg_quest8.wav
sound/sentences/hg_quest9.wav
sound/sentences/hg_quest10.wav
sound/sentences/hg_quest11.wav
sound/sentences/hg_taunt0.wav
sound/sentences/hg_taunt1.wav
sound/sentences/hg_taunt2.wav
sound/sentences/hg_taunt3.wav
sound/sentences/hg_taunt4.wav
sound/sentences/hg_taunt5.wav
sound/sentences/hg_throw0.wav
sound/sentences/hg_throw1.wav
sound/sentences/hg_throw2.wav
sound/sentences/hg_throw3.wav
sound/sentences/ht01_0.wav
sound/sentences/ht01_1.wav
sound/sentences/ht01_2.wav
sound/sentences/ht01_3.wav
sound/sentences/ht01_4.wav
sound/sentences/ht01_5.wav
sound/sentences/ht01_6.wav
sound/sentences/ht01_7.wav
sound/sentences/ht01_8.wav
sound/sentences/ht01_9.wav
sound/sentences/ht05_0.wav
sound/sentences/ht05_1.wav
sound/sentences/ht05_2.wav
sound/sentences/ht05_3.wav
sound/sentences/ht05_4.wav
sound/sentences/ht05_5.wav
sound/sentences/ht05_6.wav
sound/sentences/ht05_7.wav
sound/sentences/ht05_8.wav
sound/sentences/na0.wav
sound/sentences/na1.wav
sound/sentences/na2.wav
sound/sentences/na3.wav
sound/sentences/na4.wav
sound/sentences/na5.wav
sound/sentences/na6.wav
sound/sentences/na7.wav
sound/sentences/na8.wav
sound/sentences/na9.wav
sound/sentences/na10.wav
sound/sentences/na11.wav
sound/sentences/na12.wav
sound/sentences/na13.wav
sound/sentences/na14.wav
sound/sentences/na15.wav
sound/sentences/na16.wav
sound/sentences/na17.wav
sound/sentences/na18.wav
sound/sentences/nchem0.wav
sound/sentences/ncon0.wav
sound/sentences/nd0.wav
sound/sentences/nd1.wav
sound/sentences/nd2.wav
sound/sentences/nd3.wav
sound/sentences/nd4.wav
sound/sentences/nd5.wav
sound/sentences/nd6.wav
sound/sentences/nd7.wav
sound/sentences/nf0.wav
sound/sentences/nf1.wav
sound/sentences/nf3.wav
sound/sentences/nfire0.wav
sound/sentences/ng0.wav
sound/sentences/ng1.wav
sound/sentences/ng2.wav
sound/sentences/nh0.wav
sound/sentences/nh1.wav
sound/sentences/nrad0.wav
sound/sentences/pmhev_shock.wav
sound/sentences/power_off.wav
sound/sentences/power_on.wav
sound/sentences/t0.wav
sound/sentences/t1.wav
sound/sentences/t2.wav
sound/sentences/t3.wav
sound/sentences/t4.wav
sound/sentences/t5.wav
sound/sentences/tr_a.wav
sound/sentences/tr_b.wav
sound/sentences/we0.wav
sound/sentences/we1.wav
sound/sentences/we2.wav
sound/sentences/we3.wav