// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/mars2bk.tga
gfx/env/mars2dn.tga
gfx/env/mars2ft.tga
gfx/env/mars2lf.tga
gfx/env/mars2rt.tga
gfx/env/mars2up.tga
neilm.wad
sound/magnus/barney_shit.wav
sound/magnus/bug1.wav
sound/magnus/bug2.wav
sound/magnus/captain.wav
sound/magnus/caugh.wav
sound/magnus/dsamb2.wav
sound/magnus/dsmove2.wav
sound/magnus/elev_hurt1.wav
sound/magnus/forcefield_a.wav
sound/magnus/forcefield_b.wav
sound/magnus/gravy3_a.wav
sound/magnus/gravy3_b.wav
sound/magnus/gravy3_c.wav
sound/magnus/hascold.wav
sound/magnus/lazer3.wav
sound/magnus/letsgo.wav
sound/magnus/onlyhope.wav
sound/magnus/rumble12.wav
sound/magnus/rumble6.wav
sound/magnus/toolate.wav
sound/magnus/toscared.wav
sound/magnus/whatthe.wav
sound/magnus/whoa.wav
sound/vox/alien_vox.wav
sound/vox/electrical.wav
sound/vox/gravity.wav
sound/vox/ship.wav
sound/vox/static.wav
sound/vox/wait.wav
sound/vox/zoological.wav
