// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

escape.wad
models/hlescape/barney.mdl
models/hlescape/barney01.mdl
models/hlescape/barney02.mdl
models/hlescape/barney03.mdl
models/hlescape/barney04.mdl
models/hlescape/barney05.mdl
models/hlescape/barney06.mdl
models/hlescape/barney07.mdl
models/hlescape/barneyt.mdl
models/hlescape/hgrunt.mdl
models/hlescape/hgrunt01.mdl
models/hlescape/hgrunt02.mdl
models/hlescape/otis.mdl
models/hlescape/otis01.mdl
models/hlescape/otis02.mdl
models/hlescape/otis03.mdl
models/hlescape/rgrunt.mdl
models/hlescape/rgruntt.mdl
models/hlescape/scientist.mdl
models/hlescape/scientist01.mdl
models/hlescape/scientist02.mdl
models/hlescape/scientist03.mdl
models/hlescape/scientist04.mdl
models/hlescape/scientist05.mdl
models/hlescape/scientist06.mdl
models/hlescape/scientist07.mdl
models/hlescape/scientist08.mdl
models/hlescape/scientist09.mdl
models/hlescape/scientist10.mdl
models/hlescape/scientist11.mdl
models/hlescape/scientist_cower.mdl
models/hlescape/scientist_cower01.mdl
models/hlescape/tool_box.mdl
models/hlescape/weapons/v_9mmAR.mdl
models/hlescape/weapons/v_9mmhandgun.mdl
models/hlescape/weapons/v_crowbar.mdl
models/hlescape/weapons/v_grenade.mdl
models/hlescape/weapons/v_satchel.mdl
models/hlescape/weapons/v_satchel_radio.mdl
models/hlescape/weapons/v_shotgun.mdl
models/hlescape/zombie.mdl
models/hlescape/zombie01.mdl
models/hlescape/zombie02.mdl
models/hlescape/zombie03.mdl
models/hlescape/zombie04.mdl
models/hlescape/zombie_barney.mdl
models/hlescape/zombie_barney01.mdl
models/hlescape/zombie_barney02.mdl
models/hlescape/zombie_barney03.mdl
models/hlescape/zombie_soldier.mdl
sound/hlescape/ambience/blip.wav
sound/hlescape/ambience/teleport.wav
sound/hlescape/speak/barney1.wav
sound/hlescape/speak/barney2.wav
sound/hlescape/speak/barney3.wav
sound/hlescape/speak/barney4.wav
sound/hlescape/speak/rosenberg1.wav
sound/hlescape/speak/rosenberg2.wav
sound/hlescape/speak/rosenberg3.wav
sound/hlescape/speak/scientist1.wav
sound/hlescape/speak/scientist2.wav
sound/hlescape/speak/smith2.wav
