// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/decay/suv.mdl
models/scmod/alab/w_suitmk1.mdl
models/scmod/esw/af_container_close_new.mdl
models/scmod/esw/bkjeep_empty.mdl
models/scmod/esw/calhoun.mdl
models/scmod/esw/calhoun_unarmed.mdl
models/scmod/esw/carjeep2.mdl
models/scmod/esw/dead_barney.mdl
models/scmod/esw/justbarn.mdl
models/scmod/esw/kate.mdl
models/scmod/esw/rosenberg.mdl
models/scmod/esw/xonxt.mdl
models/scmod/item_gausspack_classic.mdl
models/scmod/npcs/massn/sniper.mdl
models/scmod/zubben/w_suit.mdl
models/scmod/zubben/w_suit_recolor.mdl
new.wad
sound/decay/rosenberg/ro_plfear3.wav
sound/scmod/alphaunit/dialogs/quake2_reference.ogg
sound/scmod/esw/bshift_trailertheme.ogg
sound/scmod/esw/civflagcapture_agrastios.ogg
sound/scmod/esw/dialogs/e2l1a/1carlingford.ogg
sound/scmod/esw/dialogs/e2l1a/1grunt.ogg
sound/scmod/esw/dialogs/e2l1b/10rosenberg.ogg
sound/scmod/esw/dialogs/e2l1b/11barney.ogg
sound/scmod/esw/dialogs/e2l1b/12sniper.ogg
sound/scmod/esw/dialogs/e2l1b/13carlingford.ogg
sound/scmod/esw/dialogs/e2l1b/15sniper.ogg
sound/scmod/esw/dialogs/e2l1b/16barney.ogg
sound/scmod/esw/dialogs/e2l1b/1sci.ogg
sound/scmod/esw/dialogs/e2l1b/2barney.ogg
sound/scmod/esw/dialogs/e2l1b/3walter.ogg
sound/scmod/esw/dialogs/e2l1b/4rosenberg.ogg
sound/scmod/esw/dialogs/e2l1b/5sci.ogg
sound/scmod/esw/dialogs/e2l1b/6carlingford.ogg
sound/scmod/esw/dialogs/e2l1b/7barney.ogg
sound/scmod/esw/dialogs/e2l1b/9sniper.ogg
sound/scmod/esw/dialogs/e2l1b/barney_nodoor.ogg
sound/scmod/npcs/kate/anotherdown.ogg
sound/scmod/npcs/kate/badfeeling.ogg
sound/scmod/npcs/kate/becarefull.ogg
sound/scmod/npcs/kate/bequiet.ogg
sound/scmod/npcs/kate/bringitone.ogg
sound/scmod/npcs/kate/close.ogg
sound/scmod/npcs/kate/cupoftea.ogg
sound/scmod/npcs/kate/didseeshot.ogg
sound/scmod/npcs/kate/dinnerend.ogg
sound/scmod/npcs/kate/dontagree.ogg
sound/scmod/npcs/kate/dontdothat.ogg
sound/scmod/npcs/kate/dontdothis.ogg
sound/scmod/npcs/kate/dontknow.ogg
sound/scmod/npcs/kate/friendslikeyou.ogg
sound/scmod/npcs/kate/gotone.ogg
sound/scmod/npcs/kate/hearsomething.ogg
sound/scmod/npcs/kate/hevno.ogg
sound/scmod/npcs/kate/hi.ogg
sound/scmod/npcs/kate/hitbad.ogg
sound/scmod/npcs/kate/hitbad2.ogg
sound/scmod/npcs/kate/hummm.ogg
sound/scmod/npcs/kate/ka_attack1.ogg
sound/scmod/npcs/kate/ka_die1.ogg
sound/scmod/npcs/kate/ka_pain1.ogg
sound/scmod/npcs/kate/ka_pain2.ogg
sound/scmod/npcs/kate/notatall.ogg
sound/scmod/npcs/kate/ohyes.ogg
sound/scmod/npcs/kate/oneless.ogg
sound/scmod/npcs/kate/openfire.ogg
sound/scmod/npcs/kate/seeyoulater.ogg
sound/scmod/npcs/kate/somethingmove.ogg
sound/scmod/npcs/kate/stepoff.ogg
sound/scmod/npcs/kate/teamup1.ogg
sound/scmod/npcs/kate/teamup2.ogg
sound/scmod/npcs/kate/thinking.ogg
sound/scmod/npcs/kate/waithere.ogg
sound/scmod/npcs/kate/waithere2.ogg
sound/scmod/npcs/kate/whatsgoingon.ogg
sound/scmod/npcs/kate/whatsgoingon2.ogg
sound/scmod/npcs/kate/whatyoudoing.ogg
sound/scmod/npcs/kate/yesbarn.ogg
sound/scmod/npcs/kate/youneedmedic.ogg
