// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
cs_747.wad
cs_assault.wad
cs_office.wad
cs_siege.wad
hs.wad
hs2.wad
hs3.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/alienslave/darkgaunt.mdl
models/custom_monsters/alienslave/mage.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/bullsquid/mistakesquid.mdl
models/custom_monsters/gonome/gonome_tyrant.mdl
models/custom_monsters/headcrab/baby_panther.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/pitdrone/killerdrone.mdl
models/custom_monsters/shocktrooper/mutant_repeater.mdl
models/custom_monsters/zombie/darkzombie.mdl
models/custom_monsters/zombie/elite_slasher.mdl
models/custom_monsters/zombie/nimblezombie.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie.mdl
models/st_allies/dead_hev.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/item_key.mdl
models/st_mission1/props/AA_Cable1_SM.mdl
models/st_mission1/props/cc_building10.mdl
models/st_mission1/props/cc_building11.mdl
models/st_mission1/props/cc_building5.mdl
models/st_mission1/props/DOM_KV_1.mdl
models/st_mission1/props/ifO_cardBottlesWd.mdl
models/st_mission1/props/walkytalky.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/baby_panther/bp_alert1.ogg
sound/custom_monsters/baby_panther/bp_alert2.ogg
sound/custom_monsters/baby_panther/bp_attack1.ogg
sound/custom_monsters/baby_panther/bp_attack2.ogg
sound/custom_monsters/baby_panther/bp_attack3.ogg
sound/custom_monsters/baby_panther/bp_die1.ogg
sound/custom_monsters/baby_panther/bp_die2.ogg
sound/custom_monsters/baby_panther/bp_headbite.ogg
sound/custom_monsters/baby_panther/bp_idle1.ogg
sound/custom_monsters/baby_panther/bp_idle2.ogg
sound/custom_monsters/baby_panther/bp_idle3.ogg
sound/custom_monsters/baby_panther/bp_idle4.ogg
sound/custom_monsters/baby_panther/bp_idle5.ogg
sound/custom_monsters/baby_panther/bp_pain1.ogg
sound/custom_monsters/baby_panther/bp_pain2.ogg
sound/custom_monsters/baby_panther/bp_pain3.ogg
sound/custom_monsters/ghost/con_alert1.ogg
sound/custom_monsters/ghost/con_alert2.ogg
sound/custom_monsters/ghost/con_alert3.ogg
sound/custom_monsters/ghost/con_attack1.ogg
sound/custom_monsters/ghost/con_attack2.ogg
sound/custom_monsters/ghost/con_attack3.ogg
sound/custom_monsters/ghost/con_die1.ogg
sound/custom_monsters/ghost/con_die2.ogg
sound/custom_monsters/ghost/con_idle1.ogg
sound/custom_monsters/ghost/con_idle2.ogg
sound/custom_monsters/ghost/con_idle3.ogg
sound/custom_monsters/ghost/con_idle4.ogg
sound/custom_monsters/ghost/con_idle5.ogg
sound/custom_monsters/ghost/con_pain1.ogg
sound/custom_monsters/ghost/con_pain2.ogg
sound/custom_monsters/ghost/con_pain3.ogg
sound/custom_monsters/necroscasm/claw_miss1.ogg
sound/custom_monsters/necroscasm/claw_miss2.ogg
sound/custom_monsters/necroscasm/claw_strike1.ogg
sound/custom_monsters/necroscasm/claw_strike2.ogg
sound/custom_monsters/necroscasm/claw_strike3.ogg
sound/custom_monsters/necroscasm/zo_alert10.ogg
sound/custom_monsters/necroscasm/zo_alert20.ogg
sound/custom_monsters/necroscasm/zo_alert30.ogg
sound/custom_monsters/necroscasm/zo_attack1.ogg
sound/custom_monsters/necroscasm/zo_attack2.ogg
sound/custom_monsters/necroscasm/zo_idle1.ogg
sound/custom_monsters/necroscasm/zo_idle2.ogg
sound/custom_monsters/necroscasm/zo_idle3.ogg
sound/custom_monsters/necroscasm/zo_idle4.ogg
sound/custom_monsters/necroscasm/zo_pain1.ogg
sound/custom_monsters/necroscasm/zo_pain2.ogg
sound/custom_monsters/slasherghost/sg_alert1.ogg
sound/custom_monsters/slasherghost/sg_alert2.ogg
sound/custom_monsters/slasherghost/sg_alert3.ogg
sound/custom_monsters/slasherghost/sg_miss1.ogg
sound/custom_monsters/slasherghost/sg_miss2.ogg
sound/custom_monsters/slasherghost/sg_pain1.ogg
sound/custom_monsters/slasherghost/sg_pain2.ogg
sound/custom_monsters/slasherghost/sg_slash1.ogg
sound/custom_monsters/slasherghost/sg_slash2.ogg
sound/custom_monsters/slasherghost/sg_slash3.ogg
sound/custom_monsters/slasherghost/sg_voice1.ogg
sound/custom_monsters/slasherghost/sg_voice2.ogg
sound/custom_monsters/slasherghost/sg_voice3.ogg
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/st_mission/distantfirefight.ogg
sound/st_mission/music/ambience01.ogg
sound/st_mission/night.ogg
sound/st_mission/radio/hs_b6_respond.ogg
sound/st_mission/radio/hs_b6_ryan.ogg
sound/st_mission/radio/rodney_recording01.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sprites/st_mission/item_key.spr
