// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/custom_monsters/agrunt/slavegrunt.mdl
models/custom_monsters/alienslave/gandalf.mdl
models/custom_monsters/bullsquid/kimohakase.mdl
models/custom_monsters/bullsquid/twitchersquid.mdl
models/custom_monsters/gonome/heavy_zombie.mdl
models/custom_monsters/gonome/licker.mdl
models/custom_monsters/headcrab/baby_panther.mdl
models/custom_monsters/pitdrone/bluedrone.mdl
models/custom_monsters/stukabat/lostsoul.mdl
models/custom_monsters/zombie/corpse.mdl
models/custom_monsters/zombie/zombie_scguard.mdl
models/custom_monsters/zombie/zombie_sci.mdl
models/custom_monsters/zombie/zombie_sven.mdl
models/st_allies/brad.mdl
models/st_allies/dead_hev.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_allies/sobrobo.mdl
models/st_allies/svenhelmet_helmet.mdl
models/st_allies/svenhelmet_shotgun.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/trash3.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_radiation.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/rare/p_m40a1_rare01.mdl
models/st_mission1/weapons_classic/rare/v_m40a1_rare01.mdl
models/st_mission1/weapons_classic/rare/w_m40a1_rare01.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
models/st_mission1/weapons_classic/w_suit.mdl
sound/custom_monsters/baby_panther/bp_alert1.ogg
sound/custom_monsters/baby_panther/bp_alert2.ogg
sound/custom_monsters/baby_panther/bp_attack1.ogg
sound/custom_monsters/baby_panther/bp_attack2.ogg
sound/custom_monsters/baby_panther/bp_attack3.ogg
sound/custom_monsters/baby_panther/bp_die1.ogg
sound/custom_monsters/baby_panther/bp_die2.ogg
sound/custom_monsters/baby_panther/bp_headbite.ogg
sound/custom_monsters/baby_panther/bp_idle1.ogg
sound/custom_monsters/baby_panther/bp_idle2.ogg
sound/custom_monsters/baby_panther/bp_idle3.ogg
sound/custom_monsters/baby_panther/bp_idle4.ogg
sound/custom_monsters/baby_panther/bp_idle5.ogg
sound/custom_monsters/baby_panther/bp_pain1.ogg
sound/custom_monsters/baby_panther/bp_pain2.ogg
sound/custom_monsters/baby_panther/bp_pain3.ogg
sound/custom_monsters/evilsci_boss/es_scream01.ogg
sound/custom_monsters/portal.ogg
sound/custom_monsters/sgrunt/ag_alert1.ogg
sound/custom_monsters/sgrunt/ag_alert2.ogg
sound/custom_monsters/sgrunt/ag_alert3.ogg
sound/custom_monsters/sgrunt/ag_alert4.ogg
sound/custom_monsters/sgrunt/ag_alert5.ogg
sound/custom_monsters/sgrunt/ag_attack1.ogg
sound/custom_monsters/sgrunt/ag_attack2.ogg
sound/custom_monsters/sgrunt/ag_attack3.ogg
sound/custom_monsters/sgrunt/ag_die1.ogg
sound/custom_monsters/sgrunt/ag_die2.ogg
sound/custom_monsters/sgrunt/ag_die3.ogg
sound/custom_monsters/sgrunt/ag_die4.ogg
sound/custom_monsters/sgrunt/ag_die5.ogg
sound/custom_monsters/sgrunt/ag_idle1.ogg
sound/custom_monsters/sgrunt/ag_idle2.ogg
sound/custom_monsters/sgrunt/ag_idle3.ogg
sound/custom_monsters/sgrunt/ag_idle4.ogg
sound/custom_monsters/sgrunt/ag_idle5.ogg
sound/custom_monsters/sgrunt/ag_pain1.ogg
sound/custom_monsters/sgrunt/ag_pain2.ogg
sound/custom_monsters/sgrunt/ag_pain3.ogg
sound/custom_monsters/sgrunt/ag_pain4.ogg
sound/custom_monsters/sgrunt/ag_pain5.ogg
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/hs/weapons/dbarrel1.ogg
sound/hs/weapons/sbarrel1.ogg
sound/hs/weapons/scock1.ogg
sound/st_allies/sobrobo/sr_a1_disabled.ogg
sound/st_allies/sobrobo/sr_a1_hello.ogg
sound/st_allies/sobrobo/sr_a1_info.ogg
sound/st_allies/sobrobo/sr_a1_portalroom.ogg
sound/st_allies/sobrobo/sr_a1_sparkle.ogg
sound/st_allies/sobrobo/sr_a1_suits.ogg
sound/st_allies/sobrobo/sr_a1_themission.ogg
sound/st_allies/sobrobo/sr_a1_wizard.ogg
sound/st_mission/announcements/sector19/announcement01.ogg
sound/st_mission/announcements/sector19/announcement02.ogg
sound/st_mission/announcements/sector19/announcement03.ogg
sound/st_mission/announcements/sector19/announcement04.ogg
sound/st_mission/announcements/sector19/announcement05.ogg
sound/st_mission/announcements/sector19/announcement06.ogg
sound/st_mission/announcements/sector19/announcement07.ogg
sound/st_mission/announcements/sector19/announcement08.ogg
sound/st_mission/announcements/sector19/announcement09.ogg
sound/st_mission/announcements/sector19/announcement10.ogg
sound/st_mission/announcements/sector19/announcement11.ogg
sound/st_mission/music/ambience01.ogg
sound/st_mission/plats/flyingspark.ogg
