// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
cs_747.wad
cs_siege.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/alienslave/darkgaunt.mdl
models/custom_monsters/alienslave/mage.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/bullsquid/demonsquid.mdl
models/custom_monsters/gonome/heavy_zombie.mdl
models/custom_monsters/headcrab/baby_panther.mdl
models/custom_monsters/hgrunt/haunted_ngrunt.mdl
models/custom_monsters/hgrunt/haunted_ngrunt3.mdl
models/custom_monsters/hgrunt/haunted_security_ar.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_helmet.mdl
models/custom_monsters/hgrunt/infected_sgrunt.mdl
models/custom_monsters/hgrunt/security_infected.mdl
models/custom_monsters/houndeye/hyperhoundeye.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/shocktrooper/bloodlurker.mdl
models/custom_monsters/shocktrooper/mutant_repeater.mdl
models/custom_monsters/tor/overlord_wizard.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/zombie.mdl
models/st_allies/cyrex_armed.mdl
models/st_allies/darkwing.mdl
models/st_allies/dead_hev.mdl
models/st_allies/lowell.mdl
models/st_allies/miles.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/plinky_armed.mdl
models/st_allies/security_ar.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_allies/sobrobo_armed.mdl
models/st_mission1/props/w_lasergun.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/baby_panther/bp_alert1.ogg
sound/custom_monsters/baby_panther/bp_alert2.ogg
sound/custom_monsters/baby_panther/bp_attack1.ogg
sound/custom_monsters/baby_panther/bp_attack2.ogg
sound/custom_monsters/baby_panther/bp_attack3.ogg
sound/custom_monsters/baby_panther/bp_die1.ogg
sound/custom_monsters/baby_panther/bp_die2.ogg
sound/custom_monsters/baby_panther/bp_headbite.ogg
sound/custom_monsters/baby_panther/bp_idle1.ogg
sound/custom_monsters/baby_panther/bp_idle2.ogg
sound/custom_monsters/baby_panther/bp_idle3.ogg
sound/custom_monsters/baby_panther/bp_idle4.ogg
sound/custom_monsters/baby_panther/bp_idle5.ogg
sound/custom_monsters/baby_panther/bp_pain1.ogg
sound/custom_monsters/baby_panther/bp_pain2.ogg
sound/custom_monsters/baby_panther/bp_pain3.ogg
sound/custom_monsters/ghost/con_alert1.ogg
sound/custom_monsters/ghost/con_alert2.ogg
sound/custom_monsters/ghost/con_alert3.ogg
sound/custom_monsters/ghost/con_attack1.ogg
sound/custom_monsters/ghost/con_attack2.ogg
sound/custom_monsters/ghost/con_attack3.ogg
sound/custom_monsters/ghost/con_die1.ogg
sound/custom_monsters/ghost/con_die2.ogg
sound/custom_monsters/ghost/con_idle1.ogg
sound/custom_monsters/ghost/con_idle2.ogg
sound/custom_monsters/ghost/con_idle3.ogg
sound/custom_monsters/ghost/con_idle4.ogg
sound/custom_monsters/ghost/con_idle5.ogg
sound/custom_monsters/ghost/con_pain1.ogg
sound/custom_monsters/ghost/con_pain2.ogg
sound/custom_monsters/ghost/con_pain3.ogg
sound/custom_monsters/guns/aomshotgun/sbarrel1.ogg
sound/custom_monsters/guns/g3/g3_fire.ogg
sound/custom_monsters/guns/m3/m3-1.ogg
sound/custom_monsters/guns/msg90/sniper_fire.ogg
sound/custom_monsters/guns/p90/p90-1.ogg
sound/custom_monsters/guns/smg/hks1.ogg
sound/custom_monsters/guns/smg/hks2.ogg
sound/custom_monsters/guns/taurus/tau_fire.ogg
sound/custom_monsters/overlordwizard/ow_alert1.ogg
sound/custom_monsters/overlordwizard/ow_alert2.ogg
sound/custom_monsters/overlordwizard/ow_attack1.ogg
sound/custom_monsters/overlordwizard/ow_attack2.ogg
sound/custom_monsters/overlordwizard/ow_die1.ogg
sound/custom_monsters/overlordwizard/ow_die2.ogg
sound/custom_monsters/overlordwizard/ow_idle1.ogg
sound/custom_monsters/overlordwizard/ow_idle2.ogg
sound/custom_monsters/overlordwizard/ow_idle3.ogg
sound/custom_monsters/overlordwizard/ow_impact.ogg
sound/custom_monsters/overlordwizard/ow_pain.ogg
sound/custom_monsters/overlordwizard/ow_summon.ogg
sound/custom_monsters/slasherghost/sg_alert1.ogg
sound/custom_monsters/slasherghost/sg_alert2.ogg
sound/custom_monsters/slasherghost/sg_alert3.ogg
sound/custom_monsters/slasherghost/sg_miss1.ogg
sound/custom_monsters/slasherghost/sg_miss2.ogg
sound/custom_monsters/slasherghost/sg_pain1.ogg
sound/custom_monsters/slasherghost/sg_pain2.ogg
sound/custom_monsters/slasherghost/sg_slash1.ogg
sound/custom_monsters/slasherghost/sg_slash2.ogg
sound/custom_monsters/slasherghost/sg_slash3.ogg
sound/custom_monsters/slasherghost/sg_voice1.ogg
sound/custom_monsters/slasherghost/sg_voice2.ogg
sound/custom_monsters/slasherghost/sg_voice3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/st_allies/cyrex/cy_b9_radio.ogg
sound/st_allies/cyrex/cy_b9_where.ogg
sound/st_allies/cyrex/cy_idle1.ogg
sound/st_allies/cyrex/cy_idle3.ogg
sound/st_allies/cyrex/cy_idle4.ogg
sound/st_allies/cyrex/cy_idle5.ogg
sound/st_allies/darkwing/dw_b9_chopper.ogg
sound/st_allies/darkwing/dw_b9_friends.ogg
sound/st_allies/darkwing/dw_b9_get.ogg
sound/st_allies/darkwing/dw_b9_traitor.ogg
sound/st_allies/lowell/lw_alert1.ogg
sound/st_allies/lowell/lw_alert2.ogg
sound/st_allies/lowell/lw_alert3.ogg
sound/st_allies/lowell/lw_b9_back.ogg
sound/st_allies/lowell/lw_b9_demon.ogg
sound/st_allies/lowell/lw_b9_rodney.ogg
sound/st_allies/lowell/lw_b9_rooftop.ogg
sound/st_allies/lowell/lw_pain1.ogg
sound/st_allies/lowell/lw_pain2.ogg
sound/st_allies/lowell/lw_pain3.ogg
sound/st_allies/lowell/lw_portal_in.ogg
sound/st_allies/lowell/lw_portal_out.ogg
sound/st_allies/lowell/lw_seeker1.ogg
sound/st_allies/miles/ml_b9_chopper.ogg
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/plinky/pl_b9_lockandload.ogg
sound/st_allies/plinky/pl_idle1.ogg
sound/st_allies/plinky/pl_idle3.ogg
sound/st_allies/plinky/pl_idle4.ogg
sound/st_allies/plinky/pl_idle5.ogg
sound/st_allies/plinky/py_b9_safe.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_allies/sobrobo/sr_hs_b9_brad.ogg
sound/st_allies/sobrobo/sr_hs_b9_catch.ogg
sound/st_allies/sobrobo/sr_hs_b9_demons.ogg
sound/st_allies/sobrobo/sr_hs_b9_negative.ogg
sound/st_allies/sobrobo/sr_hs_b9_osprey.ogg
sound/st_allies/sobrobo/sr_idle1.ogg
sound/st_allies/sobrobo/sr_idle2.ogg
sound/st_allies/sobrobo/sr_idle3.ogg
sound/st_allies/sobrobo/sr_idle4.ogg
sound/st_allies/sobrobo/sr_idle5.ogg
sound/st_mission/22noice2.ogg
sound/st_mission/announcements/soiz/announcement01.ogg
sound/st_mission/announcements/soiz/announcement02.ogg
sound/st_mission/announcements/soiz/announcement03.ogg
sound/st_mission/announcements/soiz/announcement04.ogg
sound/st_mission/announcements/soiz/announcement05.ogg
sound/st_mission/announcements/soiz/announcement06.ogg
sound/st_mission/announcements/soiz/announcement07.ogg
sound/st_mission/announcements/soiz/announcement08.ogg
sound/st_mission/announcements/soiz/announcement09.ogg
sound/st_mission/announcements/soiz/announcement10.ogg
sound/st_mission/announcements/soiz/announcement11.ogg
sound/st_mission/distantfirefight.ogg
sound/st_mission/easteregg.ogg
sound/st_mission/elev_shaft1.ogg
sound/st_mission/flareidle.ogg
sound/st_mission/music/ambience01.ogg
sound/st_mission/music/hs_b9_rooftop.ogg
sound/st_mission/night.ogg
sound/st_mission/radio/hs_b9_fifteen.ogg
sound/st_mission/radio/hs_b9_goose9grid.ogg
sound/st_mission/radio/hs_b9_goose9osprey.ogg
sound/st_mission/radio/hs_b9_you.ogg
sound/st_mission/weapons/de_shot1.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m41a_hks1.ogg
sound/st_mission/weapons/m41a_hks2.ogg
sound/st_mission/weapons/m41a_hks3.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/sniper_fire.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/xm8-fire.ogg
