// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

9.wad
aomreal.wad
cs_747.wad
cs_assault.wad
cs_siege.wad
hs.wad
hs2.wad
kz-kargo.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/slavegrunt.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/bullsquid/twitchersquid.mdl
models/custom_monsters/gonome/gonome_boss.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/stukabat/lostsoul.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/darkzombie.mdl
models/custom_monsters/zombie/elite_slasher.mdl
models/custom_monsters/zombie/nimblezombie.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie_scguard.mdl
models/custom_monsters/zombie/zombie_sven.mdl
models/st_allies/dead_hev.mdl
models/st_allies/miles.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/nimblegrunt/ngrunt_opfor2.mdl
models/st_allies/nimblegrunt/ngrunt_opfor3.mdl
models/st_allies/security_ar.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_allies/svenhelmet_helmet.mdl
models/st_allies/svenhelmet_shotgun.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
shl.wad
sound/custom_monsters/ghost/con_alert1.ogg
sound/custom_monsters/ghost/con_alert2.ogg
sound/custom_monsters/ghost/con_alert3.ogg
sound/custom_monsters/ghost/con_attack1.ogg
sound/custom_monsters/ghost/con_attack2.ogg
sound/custom_monsters/ghost/con_attack3.ogg
sound/custom_monsters/ghost/con_die1.ogg
sound/custom_monsters/ghost/con_die2.ogg
sound/custom_monsters/ghost/con_idle1.ogg
sound/custom_monsters/ghost/con_idle2.ogg
sound/custom_monsters/ghost/con_idle3.ogg
sound/custom_monsters/ghost/con_idle4.ogg
sound/custom_monsters/ghost/con_idle5.ogg
sound/custom_monsters/ghost/con_pain1.ogg
sound/custom_monsters/ghost/con_pain2.ogg
sound/custom_monsters/ghost/con_pain3.ogg
sound/custom_monsters/guns/g3/g3_fire.ogg
sound/custom_monsters/guns/shotgun/sbarrel1.ogg
sound/custom_monsters/guns/smg/hks1.ogg
sound/custom_monsters/guns/smg/hks2.ogg
sound/custom_monsters/guns/smg/hks3.ogg
sound/custom_monsters/necroscasm/claw_miss1.ogg
sound/custom_monsters/necroscasm/claw_miss2.ogg
sound/custom_monsters/necroscasm/claw_strike1.ogg
sound/custom_monsters/necroscasm/claw_strike2.ogg
sound/custom_monsters/necroscasm/claw_strike3.ogg
sound/custom_monsters/necroscasm/zo_alert10.ogg
sound/custom_monsters/necroscasm/zo_alert20.ogg
sound/custom_monsters/necroscasm/zo_alert30.ogg
sound/custom_monsters/necroscasm/zo_attack1.ogg
sound/custom_monsters/necroscasm/zo_attack2.ogg
sound/custom_monsters/necroscasm/zo_idle1.ogg
sound/custom_monsters/necroscasm/zo_idle2.ogg
sound/custom_monsters/necroscasm/zo_idle3.ogg
sound/custom_monsters/necroscasm/zo_idle4.ogg
sound/custom_monsters/necroscasm/zo_pain1.ogg
sound/custom_monsters/necroscasm/zo_pain2.ogg
sound/custom_monsters/portal.ogg
sound/custom_monsters/sgrunt/ag_alert1.ogg
sound/custom_monsters/sgrunt/ag_alert2.ogg
sound/custom_monsters/sgrunt/ag_alert3.ogg
sound/custom_monsters/sgrunt/ag_alert4.ogg
sound/custom_monsters/sgrunt/ag_alert5.ogg
sound/custom_monsters/sgrunt/ag_attack1.ogg
sound/custom_monsters/sgrunt/ag_attack2.ogg
sound/custom_monsters/sgrunt/ag_attack3.ogg
sound/custom_monsters/sgrunt/ag_die1.ogg
sound/custom_monsters/sgrunt/ag_die2.ogg
sound/custom_monsters/sgrunt/ag_die3.ogg
sound/custom_monsters/sgrunt/ag_die4.ogg
sound/custom_monsters/sgrunt/ag_die5.ogg
sound/custom_monsters/sgrunt/ag_idle1.ogg
sound/custom_monsters/sgrunt/ag_idle2.ogg
sound/custom_monsters/sgrunt/ag_idle3.ogg
sound/custom_monsters/sgrunt/ag_idle4.ogg
sound/custom_monsters/sgrunt/ag_idle5.ogg
sound/custom_monsters/sgrunt/ag_pain1.ogg
sound/custom_monsters/sgrunt/ag_pain2.ogg
sound/custom_monsters/sgrunt/ag_pain3.ogg
sound/custom_monsters/sgrunt/ag_pain4.ogg
sound/custom_monsters/sgrunt/ag_pain5.ogg
sound/custom_monsters/slasherghost/sg_alert1.ogg
sound/custom_monsters/slasherghost/sg_alert2.ogg
sound/custom_monsters/slasherghost/sg_alert3.ogg
sound/custom_monsters/slasherghost/sg_miss1.ogg
sound/custom_monsters/slasherghost/sg_miss2.ogg
sound/custom_monsters/slasherghost/sg_pain1.ogg
sound/custom_monsters/slasherghost/sg_pain2.ogg
sound/custom_monsters/slasherghost/sg_slash1.ogg
sound/custom_monsters/slasherghost/sg_slash2.ogg
sound/custom_monsters/slasherghost/sg_slash3.ogg
sound/custom_monsters/slasherghost/sg_voice1.ogg
sound/custom_monsters/slasherghost/sg_voice2.ogg
sound/custom_monsters/slasherghost/sg_voice3.ogg
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/st_allies/miles/ml_b07_answer.ogg
sound/st_allies/miles/ml_b07_darkwing.ogg
sound/st_allies/miles/ml_b07_ghosts.ogg
sound/st_allies/miles/ml_b07_night.ogg
sound/st_allies/miles/ml_b07_notsuprised.ogg
sound/st_allies/miles/ml_b07_poorguy.ogg
sound/st_allies/miles/ml_b07_roger.ogg
sound/st_allies/miles/ml_b07_sewer.ogg
sound/st_allies/miles/ml_b07_there.ogg
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/plinky/pl_b7_breach.ogg
sound/st_allies/plinky/pl_b7_miles.ogg
sound/st_mission/night.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/xm8-fire.ogg
