// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
cs_assault.wad
cs_office.wad
cs_siege.wad
hs.wad
kz-kargo.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/hgrunt/haunted_ngrunt.mdl
models/custom_monsters/hgrunt/haunted_ngrunt2.mdl
models/custom_monsters/hgrunt/haunted_ngrunt3.mdl
models/custom_monsters/hgrunt/haunted_ngrunt4.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_helmet.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_shotgun.mdl
models/custom_monsters/hgrunt/infected_sgrunt.mdl
models/custom_monsters/hgrunt/security_infected.mdl
models/custom_monsters/shocktrooper/bloodlurker.mdl
models/custom_monsters/tor/overlord_wizard.mdl
models/st_allies/brad.mdl
models/st_allies/crimsoncommando/crimson2.mdl
models/st_allies/crimsoncommando/crimson3.mdl
models/st_allies/crimsoncommando/crimson_hev.mdl
models/st_allies/cyrex_armed.mdl
models/st_allies/darkwing.mdl
models/st_allies/huey_apache.mdl
models/st_allies/lowell.mdl
models/st_allies/miles.mdl
models/st_allies/plinky_armed.mdl
models/st_allies/sgrunt.mdl
models/st_allies/sobrobo_armed.mdl
models/st_mission1/crystal_green.mdl
models/st_mission1/props/cc_building3.mdl
models/st_mission1/props/tracking_device.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/tree2.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/guns/aomshotgun/sbarrel1.ogg
sound/custom_monsters/guns/g3/g3_fire.ogg
sound/custom_monsters/guns/m3/m3-1.ogg
sound/custom_monsters/guns/msg90/sniper_fire.ogg
sound/custom_monsters/guns/p90/p90-1.ogg
sound/custom_monsters/guns/smg/hks1.ogg
sound/custom_monsters/guns/smg/hks2.ogg
sound/custom_monsters/guns/taurus/tau_fire.ogg
sound/custom_monsters/overlordwizard/ow_alert1.ogg
sound/custom_monsters/overlordwizard/ow_alert2.ogg
sound/custom_monsters/overlordwizard/ow_attack1.ogg
sound/custom_monsters/overlordwizard/ow_attack2.ogg
sound/custom_monsters/overlordwizard/ow_die1.ogg
sound/custom_monsters/overlordwizard/ow_die2.ogg
sound/custom_monsters/overlordwizard/ow_idle1.ogg
sound/custom_monsters/overlordwizard/ow_idle2.ogg
sound/custom_monsters/overlordwizard/ow_idle3.ogg
sound/custom_monsters/overlordwizard/ow_impact.ogg
sound/custom_monsters/overlordwizard/ow_pain.ogg
sound/custom_monsters/overlordwizard/ow_summon.ogg
sound/st_allies/crimson_commando/alert.ogg
sound/st_allies/crimson_commando/area.ogg
sound/st_allies/crimson_commando/ass.ogg
sound/st_allies/crimson_commando/babysitting.ogg
sound/st_allies/crimson_commando/backup.ogg
sound/st_allies/crimson_commando/bfeeling.ogg
sound/st_allies/crimson_commando/bogies.ogg
sound/st_allies/crimson_commando/charge.ogg
sound/st_allies/crimson_commando/check.ogg
sound/st_allies/crimson_commando/checkrecon.ogg
sound/st_allies/crimson_commando/chicken.ogg
sound/st_allies/crimson_commando/clear.ogg
sound/st_allies/crimson_commando/command.ogg
sound/st_allies/crimson_commando/corners.ogg
sound/st_allies/crimson_commando/corporal.ogg
sound/st_allies/crimson_commando/corporal_01.ogg
sound/st_allies/crimson_commando/cover.ogg
sound/st_allies/crimson_commando/covering.ogg
sound/st_allies/crimson_commando/coverup.ogg
sound/st_allies/crimson_commando/current.ogg
sound/st_allies/crimson_commando/damage.ogg
sound/st_allies/crimson_commando/death1.ogg
sound/st_allies/crimson_commando/death2.ogg
sound/st_allies/crimson_commando/death3.ogg
sound/st_allies/crimson_commando/disney.ogg
sound/st_allies/crimson_commando/dogs.ogg
sound/st_allies/crimson_commando/down.ogg
sound/st_allies/crimson_commando/flank.ogg
sound/st_allies/crimson_commando/freaks.ogg
sound/st_allies/crimson_commando/friendly.ogg
sound/st_allies/crimson_commando/fubar.ogg
sound/st_allies/crimson_commando/getsome.ogg
sound/st_allies/crimson_commando/go.ogg
sound/st_allies/crimson_commando/gotit.ogg
sound/st_allies/crimson_commando/gr_pain1.ogg
sound/st_allies/crimson_commando/gr_pain2.ogg
sound/st_allies/crimson_commando/gr_pain3.ogg
sound/st_allies/crimson_commando/gr_pain4.ogg
sound/st_allies/crimson_commando/grenade.ogg
sound/st_allies/crimson_commando/guard.ogg
sound/st_allies/crimson_commando/guardduty.ogg
sound/st_allies/crimson_commando/hellosir.ogg
sound/st_allies/crimson_commando/hellout.ogg
sound/st_allies/crimson_commando/hitbad.ogg
sound/st_allies/crimson_commando/hostiles.ogg
sound/st_allies/crimson_commando/imhit.ogg
sound/st_allies/crimson_commando/incoming.ogg
sound/st_allies/crimson_commando/lost.ogg
sound/st_allies/crimson_commando/marines.ogg
sound/st_allies/crimson_commando/mission.ogg
sound/st_allies/crimson_commando/mister.ogg
sound/st_allies/crimson_commando/move.ogg
sound/st_allies/crimson_commando/moveup.ogg
sound/st_allies/crimson_commando/moving.ogg
sound/st_allies/crimson_commando/no.ogg
sound/st_allies/crimson_commando/notfail.ogg
sound/st_allies/crimson_commando/now.ogg
sound/st_allies/crimson_commando/oneshot.ogg
sound/st_allies/crimson_commando/orders.ogg
sound/st_allies/crimson_commando/outof.ogg
sound/st_allies/crimson_commando/pain1.ogg
sound/st_allies/crimson_commando/pain2.ogg
sound/st_allies/crimson_commando/pain3.ogg
sound/st_allies/crimson_commando/pain4.ogg
sound/st_allies/crimson_commando/quiet.ogg
sound/st_allies/crimson_commando/rapidfire.ogg
sound/st_allies/crimson_commando/recon.ogg
sound/st_allies/crimson_commando/right.ogg
sound/st_allies/crimson_commando/roger.ogg
sound/st_allies/crimson_commando/scout.ogg
sound/st_allies/crimson_commando/secure.ogg
sound/st_allies/crimson_commando/seensquad.ogg
sound/st_allies/crimson_commando/short.ogg
sound/st_allies/crimson_commando/six.ogg
sound/st_allies/crimson_commando/sniper.ogg
sound/st_allies/crimson_commando/suppressing.ogg
sound/st_allies/crimson_commando/sweep.ogg
sound/st_allies/crimson_commando/tag.ogg
sound/st_allies/crimson_commando/take.ogg
sound/st_allies/crimson_commando/talking.ogg
sound/st_allies/crimson_commando/wantsome.ogg
sound/st_allies/crimson_commando/watchfire.ogg
sound/st_allies/crimson_commando/watchit.ogg
sound/st_allies/crimson_commando/yes.ogg
sound/st_allies/crimson_commando/zone.ogg
sound/st_allies/cyrex/cy_idle1.ogg
sound/st_allies/cyrex/cy_idle3.ogg
sound/st_allies/cyrex/cy_idle4.ogg
sound/st_allies/cyrex/cy_idle5.ogg
sound/st_allies/darkwing/dw_b10_hit.ogg
sound/st_allies/darkwing/dw_b10_idk.ogg
sound/st_allies/darkwing/dw_b10_scream.ogg
sound/st_allies/lowell/lw_alert1.ogg
sound/st_allies/lowell/lw_alert2.ogg
sound/st_allies/lowell/lw_alert3.ogg
sound/st_allies/lowell/lw_b10_portal.ogg
sound/st_allies/lowell/lw_b10_second.ogg
sound/st_allies/lowell/lw_pain1.ogg
sound/st_allies/lowell/lw_pain2.ogg
sound/st_allies/lowell/lw_pain3.ogg
sound/st_allies/lowell/lw_portal_in.ogg
sound/st_allies/lowell/lw_portal_out.ogg
sound/st_allies/lowell/lw_seeker1.ogg
sound/st_allies/miles/ml_b10_crystals.ogg
sound/st_allies/miles/ml_b10_whats.ogg
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/plinky/pl_idle1.ogg
sound/st_allies/plinky/pl_idle3.ogg
sound/st_allies/plinky/pl_idle4.ogg
sound/st_allies/plinky/pl_idle5.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_allies/sobrobo/sr_idle1.ogg
sound/st_allies/sobrobo/sr_idle2.ogg
sound/st_allies/sobrobo/sr_idle3.ogg
sound/st_allies/sobrobo/sr_idle4.ogg
sound/st_allies/sobrobo/sr_idle5.ogg
sound/st_mission/music/hs_b10_final.ogg
sound/st_mission/music/hs_b10_osprey.ogg
sound/st_mission/radio/hs_b10_1min.ogg
sound/st_mission/radio/hs_b10_air.ogg
sound/st_mission/radio/hs_b10_applied.ogg
sound/st_mission/radio/hs_b10_brl.ogg
sound/st_mission/radio/hs_b10_crystal.ogg
sound/st_mission/radio/hs_b10_getit.ogg
sound/st_mission/radio/hs_b10_mortar.ogg
sound/st_mission/radio/hs_b10_secure.ogg
sound/st_mission/truck3.ogg
sound/st_mission/weapons/de_shot1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/m41a_hks1.ogg
sound/st_mission/weapons/m41a_hks2.ogg
sound/st_mission/weapons/m41a_hks3.ogg
sound/st_mission/weapons/m4a1-fire.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/scar-fire.ogg
sound/st_mission/weapons/sniper_fire.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/wa2000_shoot1.ogg
sound/st_mission/weapons/xm8-fire.ogg
