// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
cs_office.wad
hs.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_guardian.mdl
models/custom_monsters/aliencontroller/controllersci.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/bigmom/skull_big_mom.mdl
models/custom_monsters/bullsquid/bullsquidgreen.mdl
models/custom_monsters/bullsquid/darksquid.mdl
models/custom_monsters/gargantua/overlord_flame.mdl
models/custom_monsters/headcrab/darkcrab.mdl
models/custom_monsters/headcrab/skullcrab.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/shocktrooper/bloodlurker.mdl
models/custom_monsters/shocktrooper/strooper_commander.mdl
models/custom_monsters/stukabat/lostsoul.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie_sci.mdl
models/st_allies/civilian.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_allies/sobrobo_armed.mdl
models/st_allies/svenhelmet_helmet.mdl
models/st_allies/svenhelmet_shotgun.mdl
models/st_mission1/crystal_purple.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_radiation.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/ghost/con_alert1.ogg
sound/custom_monsters/ghost/con_alert2.ogg
sound/custom_monsters/ghost/con_alert3.ogg
sound/custom_monsters/ghost/con_attack1.ogg
sound/custom_monsters/ghost/con_attack2.ogg
sound/custom_monsters/ghost/con_attack3.ogg
sound/custom_monsters/ghost/con_die1.ogg
sound/custom_monsters/ghost/con_die2.ogg
sound/custom_monsters/ghost/con_idle1.ogg
sound/custom_monsters/ghost/con_idle2.ogg
sound/custom_monsters/ghost/con_idle3.ogg
sound/custom_monsters/ghost/con_idle4.ogg
sound/custom_monsters/ghost/con_idle5.ogg
sound/custom_monsters/ghost/con_pain1.ogg
sound/custom_monsters/ghost/con_pain2.ogg
sound/custom_monsters/ghost/con_pain3.ogg
sound/custom_monsters/guns/aomshotgun/sbarrel1.ogg
sound/custom_monsters/guns/p90/p90-1.ogg
sound/custom_monsters/guns/taurus/tau_fire.ogg
sound/custom_monsters/overlord_flame/of_alert1.ogg
sound/custom_monsters/overlord_flame/of_attack1.ogg
sound/custom_monsters/overlord_flame/of_attack2.ogg
sound/custom_monsters/overlord_flame/of_die1.ogg
sound/custom_monsters/overlord_flame/of_flameoff1.ogg
sound/custom_monsters/overlord_flame/of_flameon1.ogg
sound/custom_monsters/overlord_flame/of_idle1.ogg
sound/custom_monsters/overlord_flame/of_idle2.ogg
sound/custom_monsters/overlord_flame/of_idle3.ogg
sound/custom_monsters/overlord_flame/of_pain1.ogg
sound/custom_monsters/overlord_flame/of_pain2.ogg
sound/custom_monsters/overlord_flame/of_pain3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/hs/weapons/dbarrel1.ogg
sound/hs/weapons/sbarrel1.ogg
sound/hs/weapons/scock1.ogg
sound/st_allies/sobrobo/sr_a2_attacking.ogg
sound/st_allies/sobrobo/sr_a2_complete.ogg
sound/st_allies/sobrobo/sr_a2_crystal.ogg
sound/st_allies/sobrobo/sr_a2_get.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_allies/sobrobo/sr_idle1.ogg
sound/st_allies/sobrobo/sr_idle2.ogg
sound/st_allies/sobrobo/sr_idle3.ogg
sound/st_allies/sobrobo/sr_idle4.ogg
sound/st_allies/sobrobo/sr_idle5.ogg
sound/st_mission/bigshadowsounds.ogg
sound/st_mission/cagesound.ogg
sound/st_mission/cry2.ogg
sound/st_mission/hellambient.ogg
sound/st_mission/kaos.ogg
sound/st_mission/music/hs_a2_boss.ogg
