// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

halfrats.wad
maps/hr_dream11.res
models/hrafd/barney.mdl
models/hrafd/garg.mdl
models/hrafd/gman.mdl
models/hrafd/hassassin.mdl
models/hrafd/headcrab.mdl
models/hrafd/hell.mdl
models/hrafd/houndeye.mdl
models/hrafd/hrafd.gmr
models/hrafd/icky.mdl
models/hrafd/islave.mdl
models/hrafd/p_357.mdl
models/hrafd/p_crowbar.mdl
models/hrafd/scientist.mdl
models/hrafd/v_357.mdl
models/hrafd/v_crowbar.mdl
models/hrafd/w_357.mdl
models/hrafd/w_357ammobox.mdl
models/hrafd/w_battery.mdl
models/hrafd/w_crowbar.mdl
models/hrafd/w_grenade.mdl
models/hrafd/w_medkit.mdl
models/hrafd/zombie.mdl
scripts/maps/hrafd/hrafd.as
scripts/maps/hrafd/weapons/weapon_hrcrowbar.as
scripts/maps/hrafd/weapons/weapon_hrpython.as
sound/hrafd/ambience/agueposingasbabalon.wav
sound/hrafd/ambience/biggun3.wav
sound/hrafd/ambience/geneworm_final_pain3.wav
sound/hrafd/ambience/hrak47.wav
sound/hrafd/ambience/hrcallout.wav
sound/hrafd/ambience/hrcsuck.wav
sound/hrafd/ambience/hrexclaim.wav
sound/hrafd/ambience/hrhangerson.wav
sound/hrafd/ambience/hrtrainride.wav
sound/hrafd/ambience/Locomotive.wav
sound/hrafd/ambience/locomotivecar.wav
sound/hrafd/ambience/particle_suck2.wav
sound/hrafd/ambience/the_horror4.wav
sound/hrafd/aslave/slv_alert1.wav
sound/hrafd/aslave/slv_alert3.wav
sound/hrafd/aslave/slv_alert4.wav
sound/hrafd/aslave/slv_die1.wav
sound/hrafd/aslave/slv_die2.wav
sound/hrafd/aslave/slv_pain1.wav
sound/hrafd/aslave/slv_pain2.wav
sound/hrafd/aslave/slv_word1.wav
sound/hrafd/aslave/slv_word2.wav
sound/hrafd/aslave/slv_word3.wav
sound/hrafd/aslave/slv_word4.wav
sound/hrafd/aslave/slv_word5.wav
sound/hrafd/aslave/slv_word6.wav
sound/hrafd/aslave/slv_word7.wav
sound/hrafd/aslave/slv_word8.wav
sound/hrafd/barney/ba_die1.wav
sound/hrafd/barney/ba_die2.wav
sound/hrafd/barney/ba_die3.wav
sound/hrafd/barney/barnaby1.wav
sound/hrafd/barney/barnaby10.wav
sound/hrafd/barney/barnaby11.wav
sound/hrafd/barney/barnaby12.wav
sound/hrafd/barney/barnaby13.wav
sound/hrafd/barney/barnaby2.wav
sound/hrafd/barney/barnaby3.wav
sound/hrafd/barney/barnaby4.wav
sound/hrafd/barney/barnaby5.wav
sound/hrafd/barney/barnaby6.wav
sound/hrafd/barney/barnaby7.wav
sound/hrafd/barney/barnaby8.wav
sound/hrafd/barney/barnaby9.wav
sound/hrafd/barney/barnabyang1.wav
sound/hrafd/barney/barnabyang2.wav
sound/hrafd/barney/barnabyang3.wav
sound/hrafd/barney/barnabyans1.wav
sound/hrafd/barney/barnabyans2.wav
sound/hrafd/barney/barnabyans3.wav
sound/hrafd/barney/barnabyans4.wav
sound/hrafd/barney/barnabyattk1.wav
sound/hrafd/barney/barnabyattk2.wav
sound/hrafd/barney/barnabyattk3.wav
sound/hrafd/barney/barnabycheckwound.wav
sound/hrafd/barney/barnabyfollow1.wav
sound/hrafd/barney/barnabyfollow2.wav
sound/hrafd/barney/barnabyfollow3.wav
sound/hrafd/barney/barnabyhear1.wav
sound/hrafd/barney/barnabyhear2.wav
sound/hrafd/barney/barnabyidle1.wav
sound/hrafd/barney/barnabyidle2.wav
sound/hrafd/barney/barnabykill1.wav
sound/hrafd/barney/barnabykill2.wav
sound/hrafd/barney/barnabykill3.wav
sound/hrafd/barney/barnabypissed.wav
sound/hrafd/barney/barnabyq1.wav
sound/hrafd/barney/barnabyq2.wav
sound/hrafd/barney/barnabyq3.wav
sound/hrafd/barney/barnabyq4.wav
sound/hrafd/barney/barnabyscare1.wav
sound/hrafd/barney/barnabysmell1.wav
sound/hrafd/barney/barnabysmell2.wav
sound/hrafd/barney/barnabystay1.wav
sound/hrafd/barney/barnabystay2.wav
sound/hrafd/barney/barnabystay3.wav
sound/hrafd/barney/barnabywounded1.wav
sound/hrafd/barney/barnabywounded2.wav
sound/hrafd/barney/barnabywounded3.wav
sound/hrafd/barney/barncom1.wav
sound/hrafd/barney/barncom2.wav
sound/hrafd/barney/barncom3.wav
sound/hrafd/barney/bs1.wav
sound/hrafd/barney/bs2.wav
sound/hrafd/barney/bs3.wav
sound/hrafd/barney/bs4.wav
sound/hrafd/barney/bs5.wav
sound/hrafd/barney/bs6.wav
sound/hrafd/barney/bs7.wav
sound/hrafd/garg/gar_alert1.wav
sound/hrafd/garg/gar_alert2.wav
sound/hrafd/garg/gar_breathe1.wav
sound/hrafd/garg/gar_breathe2.wav
sound/hrafd/garg/gar_breathe3.wav
sound/hrafd/garg/gar_idle1.wav
sound/hrafd/garg/gar_idle2.wav
sound/hrafd/garg/gar_idle3.wav
sound/hrafd/houndeye/he_alert1.wav
sound/hrafd/houndeye/he_attack1.wav
sound/hrafd/houndeye/he_die2.wav
sound/hrafd/houndeye/he_hunt1.wav
sound/hrafd/houndeye/he_hunt2.wav
sound/hrafd/houndeye/he_hunt4.wav
sound/hrafd/houndeye/he_idle1.wav
sound/hrafd/houndeye/he_idle2.wav
sound/hrafd/houndeye/he_idle3.wav
sound/hrafd/houndeye/he_idle4.wav
sound/hrafd/houndeye/he_pain1.wav
sound/hrafd/houndeye/he_pain2.wav
sound/hrafd/hrafd.gsr
sound/hrafd/hrafd_sentences.txt
sound/hrafd/items/flashlight1.wav
sound/hrafd/items/smallmedkit1.wav
sound/hrafd/materials.txt
sound/hrafd/null/null.wav
sound/hrafd/player/dead0.wav
sound/hrafd/player/dead1.wav
sound/hrafd/scientist/traskans1.wav
sound/hrafd/scientist/traskans2.wav
sound/hrafd/scientist/traskans3.wav
sound/hrafd/scientist/traskans4.wav
sound/hrafd/scientist/traskcom1.wav
sound/hrafd/scientist/traskcom2.wav
sound/hrafd/scientist/traskcom3.wav
sound/hrafd/scientist/traskcom4.wav
sound/hrafd/scientist/traskfollow1.wav
sound/hrafd/scientist/traskfollow2.wav
sound/hrafd/scientist/traskfollow3.wav
sound/hrafd/scientist/traskheal1.wav
sound/hrafd/scientist/traskheal2.wav
sound/hrafd/scientist/traskhear1.wav
sound/hrafd/scientist/traskhear2.wav
sound/hrafd/scientist/traskhear3.wav
sound/hrafd/scientist/traskhurt1.wav
sound/hrafd/scientist/traskhurt2.wav
sound/hrafd/scientist/traskhurtbad1.wav
sound/hrafd/scientist/traskhurtbad2.wav
sound/hrafd/scientist/traskidle1.wav
sound/hrafd/scientist/traskidle2.wav
sound/hrafd/scientist/traskidle3.wav
sound/hrafd/scientist/traskidle4.wav
sound/hrafd/scientist/traskline1.wav
sound/hrafd/scientist/traskline10.wav
sound/hrafd/scientist/traskline11.wav
sound/hrafd/scientist/traskline12.wav
sound/hrafd/scientist/traskline13.wav
sound/hrafd/scientist/traskline2.wav
sound/hrafd/scientist/traskline3.wav
sound/hrafd/scientist/traskline4.wav
sound/hrafd/scientist/traskline5.wav
sound/hrafd/scientist/traskline6.wav
sound/hrafd/scientist/traskline7.wav
sound/hrafd/scientist/traskline8.wav
sound/hrafd/scientist/traskline9.wav
sound/hrafd/scientist/traskmonster1.wav
sound/hrafd/scientist/traskmonster2.wav
sound/hrafd/scientist/traskq1.wav
sound/hrafd/scientist/traskq2.wav
sound/hrafd/scientist/traskq3.wav
sound/hrafd/scientist/traskq4.wav
sound/hrafd/scientist/traskscared1.wav
sound/hrafd/scientist/traskscared2.wav
sound/hrafd/scientist/traskseewound1.wav
sound/hrafd/scientist/traskseewound2.wav
sound/hrafd/scientist/traskseewound3.wav
sound/hrafd/scientist/trasksmell1.wav
sound/hrafd/scientist/trasksmell2.wav
sound/hrafd/scientist/traskstay1.wav
sound/hrafd/scientist/traskstay2.wav
sound/hrafd/scientist/traskstay3.wav
sound/hrafd/weapons/pl_gun1.wav
sound/hrafd/weapons/pl_gun2.wav
sound/hrafd/weapons/revolver1.wav
sound/hrafd/weapons/revolver2.wav
sound/hrafd/weapons/rocket1.wav
sound/hrafd/zombie/zo_alert10.wav
sound/hrafd/zombie/zo_alert20.wav
sound/hrafd/zombie/zo_alert30.wav
sound/hrafd/zombie/zo_attack1.wav
sound/hrafd/zombie/zo_attack2.wav
sound/hrafd/zombie/zo_idle1.wav
sound/hrafd/zombie/zo_idle2.wav
sound/hrafd/zombie/zo_idle3.wav
sound/hrafd/zombie/zo_idle4.wav
sound/hrafd/zombie/zo_pain1.wav
sound/hrafd/zombie/zo_pain2.wav
sprites/hrafd/640hud1.spr
sprites/hrafd/640hud12.spr
sprites/hrafd/640hud4.spr
sprites/hrafd/640hud42.spr
sprites/hrafd/640hud7.spr
sprites/hrafd/crosshairs.spr
sprites/hrafd/hr-null.spr
sprites/hrafd/weapon_hrcrowbar.txt
sprites/hrafd/weapon_hrpython.txt
