// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

lastunicfull.wad
models/lastunic/agrunt.mdl
models/lastunic/agruntf.mdl
models/lastunic/babygargunic.mdl
models/lastunic/biggarg.mdl
models/lastunic/bullngs.mdl
models/lastunic/grandgevaudanunic.mdl
models/lastunic/hwdesertunic.mdl
models/lastunic/hwdesertunic3.mdl
models/lastunic/hwsku.mdl
models/lastunic/hwzomb.mdl
models/lastunic/islave4.mdl
models/lastunic/islavemodify.mdl
models/lastunic/rbotgrunt.mdl
models/lastunic/strooper.mdl
models/lastunic/stroopertec.mdl
models/lastunic/stukabatunic.mdl
models/lastunic/voltigore.mdl
models/lastunic/weapons/357old/p_357.mdl
models/lastunic/weapons/357old/v_357.mdl
models/lastunic/weapons/357old/w_357.mdl
models/lastunic/weapons/awpcamo/p_m40a1.mdl
models/lastunic/weapons/awpcamo/v_m40a1.mdl
models/lastunic/weapons/awpcamo/w_m40a1.mdl
models/lastunic/weapons/blueegon/p_egon.mdl
models/lastunic/weapons/blueegon/v_egon.mdl
models/lastunic/weapons/blueegon/w_egon.mdl
models/lastunic/weapons/deaglegold/p_desert_eagle.mdl
models/lastunic/weapons/deaglegold/v_desert_eagle.mdl
models/lastunic/weapons/deaglegold/w_desert_eagle.mdl
models/lastunic/weapons/glock19/p_9mmhandgun.mdl
models/lastunic/weapons/glock19/v_9mmhandgun.mdl
models/lastunic/weapons/glock19/w_9mmhandgun.mdl
models/lastunic/weapons/grenadem61/p_grenade.mdl
models/lastunic/weapons/grenadem61/v_grenade.mdl
models/lastunic/weapons/grenadem61/w_grenade.mdl
models/lastunic/weapons/m16camo/p_m16.mdl
models/lastunic/weapons/m16camo/v_m16a2.mdl
models/lastunic/weapons/m16camo/w_m16.mdl
models/lastunic/weapons/minigunblack/p_minigunidle.mdl
models/lastunic/weapons/minigunblack/p_minigunspin.mdl
models/lastunic/weapons/minigunblack/v_minigun.mdl
models/lastunic/weapons/minigunblack/w_minigun.mdl
models/lastunic/weapons/mp5camo/p_9mmar.mdl
models/lastunic/weapons/mp5camo/v_9mmar.mdl
models/lastunic/weapons/mp5camo/w_9mmar.mdl
models/lastunic/weapons/pkm/p_saw.mdl
models/lastunic/weapons/pkm/v_saw.mdl
models/lastunic/weapons/pkm/w_saw.mdl
models/lastunic/weapons/pkm/w_saw_clip.mdl
models/lastunic/weapons/satchelcamo/p_satchel.mdl
models/lastunic/weapons/satchelcamo/p_satchel_radio.mdl
models/lastunic/weapons/satchelcamo/v_satchel.mdl
models/lastunic/weapons/satchelcamo/v_satchel_radio.mdl
models/lastunic/weapons/satchelcamo/w_satchel.mdl
models/lastunic/weapons/shock/p_shock.mdl
models/lastunic/weapons/shock/v_shock.mdl
models/lastunic/weapons/shock/w_shock.mdl
models/lastunic/weapons/shock/w_shock_rifle.mdl
models/lastunic/weapons/snarkblack/p_squeak.mdl
models/lastunic/weapons/snarkblack/v_squeak.mdl
models/lastunic/weapons/snarkblack/w_sqknest.mdl
models/lastunic/weapons/snarkblack/w_squeak.mdl
models/lastunic/weapons/w_357ammobox.mdl
models/lastunic/weapons/w_chainammo.mdl
models/lastunic/weapons/w_gaussammo.mdl
models/lastunic/weapons/w_shotboxbig.mdl
models/sa13/big_mom.mdl
models/sa13/elite.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/ng_boys.mdl
models/sa13/ngt_boys.mdl
models/sa13/p_akimbotmp.mdl
models/sa13/p_akimbotmpg.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_laser.mdl
models/sa13/p_med.mdl
models/sa13/p_mine.mdl
models/sa13/p_pancor.mdl
models/sa13/p_scythe.mdl
models/sa13/p_shlrpg.mdl
models/sa13/p_tmp.mdl
models/sa13/pit_drone.mdl
models/sa13/strooper.mdl
models/sa13/v_akimbomp5k.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_laser.mdl
models/sa13/v_med.mdl
models/sa13/v_mine.mdl
models/sa13/v_pancor.mdl
models/sa13/v_scythe.mdl
models/sa13/v_shlrpg.mdl
models/sa13/w_akimbotmp.mdl
models/sa13/w_akimbotmpg.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_laser.mdl
models/sa13/w_med.mdl
models/sa13/w_mine.mdl
models/sa13/w_pancor.mdl
models/sa13/w_scythe.mdl
models/sa13/w_shlrpg.mdl
models/sa13/w_tmp.mdl
models/sa13/zombie.mdl
sa13full.wad
sound/lastunic/ambience/alarmex1.ogg
sound/lastunic/ambience/alienalarme.ogg
sound/lastunic/ambience/aliencom.ogg
sound/lastunic/ambience/aliencom1.ogg
sound/lastunic/ambience/aliencom10.ogg
sound/lastunic/ambience/aliencom11.ogg
sound/lastunic/ambience/aliencom12.ogg
sound/lastunic/ambience/aliencom13.ogg
sound/lastunic/ambience/aliencom14.ogg
sound/lastunic/ambience/aliencom15.ogg
sound/lastunic/ambience/aliencom16.ogg
sound/lastunic/ambience/aliencom17.ogg
sound/lastunic/ambience/aliencom18.ogg
sound/lastunic/ambience/aliencom2.ogg
sound/lastunic/ambience/aliencom20.ogg
sound/lastunic/ambience/aliencom21.ogg
sound/lastunic/ambience/aliencom22.ogg
sound/lastunic/ambience/aliencom23.ogg
sound/lastunic/ambience/aliencom24.ogg
sound/lastunic/ambience/aliencom26.ogg
sound/lastunic/ambience/aliencom27.ogg
sound/lastunic/ambience/aliencom3.ogg
sound/lastunic/ambience/aliencom4.ogg
sound/lastunic/ambience/aliencom5.ogg
sound/lastunic/ambience/aliencom6.ogg
sound/lastunic/ambience/aliencom7.ogg
sound/lastunic/ambience/aliencom8.ogg
sound/lastunic/ambience/aliencom9.ogg
sound/lastunic/ambience/alieneffet1.ogg
sound/lastunic/ambience/alieneffet3.ogg
sound/lastunic/ambience/bip.ogg
sound/lastunic/ambience/bip3.ogg
sound/lastunic/ambience/generique8.ogg
sound/lastunic/ambience/generique9.ogg
sound/lastunic/ambience/mg_10.ogg
sound/lastunic/ambience/mg_9.ogg
sound/lastunic/ambience/rocketfire1.ogg
sound/lastunic/zombie/claw_miss1.ogg
sound/lastunic/zombie/claw_miss2.ogg
sound/lastunic/zombie/claw_strike1.ogg
sound/lastunic/zombie/claw_strike2.ogg
sound/lastunic/zombie/claw_strike3.ogg
sound/sa13/ambience/pvision.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scmod/lastunic/dialogs/lastunic_7/d1.ogg
sound/scmod/lastunic/dialogs/lastunic_7/d2.ogg
sound/scmod/lastunic/dialogs/lastunic_7/d3.ogg
sound/scmod/lastunic/dialogs/lastunic_7/watertxt.ogg
sound/weapons/de_deploy.wav
sound/weapons/egon_draw.wav
sound/weapons/foley_grabmag.wav
sound/weapons/lastunic/357/357_fire2.wav
sound/weapons/lastunic/357/357_shot1.wav
sound/weapons/lastunic/ak47/ak47-1.wav
sound/weapons/lastunic/awp/awp1.wav
sound/weapons/lastunic/deagle/deagle-1.wav
sound/weapons/lastunic/elite/elite-1.wav
sound/weapons/lastunic/shotgun/shotgun_dbl_fire7.wav
sound/weapons/lastunic/shotgun/shotgun_fire6.wav
sound/weapons/lastunic/uzi/shoot1.wav
sound/weapons/mp5_safety.wav
sound/weapons/mp5k_boltback.wav
sound/weapons/mp5k_boltslap.wav
sound/weapons/mp5k_magin.wav
sound/weapons/mp5k_magout.wav
sound/weapons/mp5k_slamtogether.wav
sound/weapons/mp5k_toakimbo.wav
sound/weapons/python/clipin.wav
sound/weapons/python/clipout.wav
sound/weapons/python/draw.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
