// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/cult2bk.tga
gfx/env/cult2dn.tga
gfx/env/cult2ft.tga
gfx/env/cult2lf.tga
gfx/env/cult2rt.tga
gfx/env/cult2up.tga
lastunicfull.wad
models/lastunic/adjoint.mdl
models/lastunic/agrunt.mdl
models/lastunic/agruntf.mdl
models/lastunic/babygargunic.mdl
models/lastunic/biggevaudan.mdl
models/lastunic/bullngs.mdl
models/lastunic/chambellan.mdl
models/lastunic/gal_kamalaucul.mdl
models/lastunic/grandgevaudanunic.mdl
models/lastunic/hgruntfriend.mdl
models/lastunic/hgruntmedicfr.mdl
models/lastunic/hwdesertunic3.mdl
models/lastunic/islave4.mdl
models/lastunic/islavemodify.mdl
models/lastunic/massndesert.mdl
models/lastunic/petgal.mdl
models/lastunic/piranha.mdl
models/lastunic/props/antsat.mdl
models/lastunic/props/antsatpied.mdl
models/lastunic/props/avionreco.mdl
models/lastunic/props/brasero.mdl
models/lastunic/props/consolecentrale.mdl
models/lastunic/props/consolecentrale2.mdl
models/lastunic/props/exit_sign.mdl
models/lastunic/props/fontaineouvrag.mdl
models/lastunic/props/generateur.mdl
models/lastunic/props/generatormob2.mdl
models/lastunic/props/genratormob.mdl
models/lastunic/props/grandgenerateur.mdl
models/lastunic/props/groupprojo.mdl
models/lastunic/props/hammer01_gun.mdl
models/lastunic/props/helicopter.mdl
models/lastunic/props/palmier8.mdl
models/lastunic/props/plante.mdl
models/lastunic/props/plante2.mdl
models/lastunic/props/plante3.mdl
models/lastunic/props/plante4.mdl
models/lastunic/props/plante5.mdl
models/lastunic/props/plotsign.mdl
models/lastunic/props/portier.mdl
models/lastunic/props/portiersecu.mdl
models/lastunic/props/radar01.mdl
models/lastunic/props/radioancienne.mdl
models/lastunic/props/radiomil.mdl
models/lastunic/props/redstart.mdl
models/lastunic/props/reservoirciterne.mdl
models/lastunic/props/rocher1.mdl
models/lastunic/props/rocher2.mdl
models/lastunic/props/rocher4.mdl
models/lastunic/props/rocher5.mdl
models/lastunic/props/rpgbox.mdl
models/lastunic/props/russesign.mdl
models/lastunic/props/sattrepied.mdl
models/lastunic/props/serveur5.mdl
models/lastunic/props/serveur6.mdl
models/lastunic/props/serveurs2.mdl
models/lastunic/props/ursslogoaero.mdl
models/lastunic/rbotgrunt.mdl
models/lastunic/robotchien.mdl
models/lastunic/sentry_0.mdl
models/lastunic/strooper.mdl
models/lastunic/stroopertec.mdl
models/lastunic/tordu.mdl
models/lastunic/unicgold.mdl
models/lastunic/voltigore.mdl
models/lastunic/weapons/357large/p_357.mdl
models/lastunic/weapons/357large/v_357.mdl
models/lastunic/weapons/357large/w_357.mdl
models/lastunic/weapons/ak47/p_9mmar.mdl
models/lastunic/weapons/ak47/v_9mmar.mdl
models/lastunic/weapons/ak47/w_9mmar.mdl
models/lastunic/weapons/ak47/w_mp5_clip.mdl
models/lastunic/weapons/barrett/p_m40a1.mdl
models/lastunic/weapons/barrett/v_m40a1.mdl
models/lastunic/weapons/barrett/w_m40a1.mdl
models/lastunic/weapons/barrett/w_m40a1clip.mdl
models/lastunic/weapons/blueegon/p_egon.mdl
models/lastunic/weapons/blueegon/v_egon.mdl
models/lastunic/weapons/blueegon/w_egon.mdl
models/lastunic/weapons/deaglegold/p_desert_eagle.mdl
models/lastunic/weapons/deaglegold/v_desert_eagle.mdl
models/lastunic/weapons/deaglegold/w_desert_eagle.mdl
models/lastunic/weapons/glock19/p_9mmhandgun.mdl
models/lastunic/weapons/glock19/v_9mmhandgun.mdl
models/lastunic/weapons/glock19/w_9mmhandgun.mdl
models/lastunic/weapons/grenadergd/p_grenade.mdl
models/lastunic/weapons/grenadergd/v_grenade.mdl
models/lastunic/weapons/grenadergd/w_grenade.mdl
models/lastunic/weapons/m16camo/p_m16.mdl
models/lastunic/weapons/m16camo/v_m16a2.mdl
models/lastunic/weapons/m16camo/w_m16.mdl
models/lastunic/weapons/minigunblack/p_minigunidle.mdl
models/lastunic/weapons/minigunblack/p_minigunspin.mdl
models/lastunic/weapons/minigunblack/v_minigun.mdl
models/lastunic/weapons/minigunblack/w_minigun.mdl
models/lastunic/weapons/rpg/p_rpg.mdl
models/lastunic/weapons/rpg/rpgrocket.mdl
models/lastunic/weapons/rpg/v_rpg.mdl
models/lastunic/weapons/rpg/w_rpg.mdl
models/lastunic/weapons/rpg/w_rpgammo.mdl
models/lastunic/weapons/satchelcamo/p_satchel.mdl
models/lastunic/weapons/satchelcamo/p_satchel_radio.mdl
models/lastunic/weapons/satchelcamo/v_satchel.mdl
models/lastunic/weapons/satchelcamo/v_satchel_radio.mdl
models/lastunic/weapons/satchelcamo/w_satchel.mdl
models/lastunic/weapons/sawcamo/p_saw.mdl
models/lastunic/weapons/sawcamo/v_saw.mdl
models/lastunic/weapons/sawcamo/w_saw.mdl
models/lastunic/weapons/sawcamo/w_saw_clip.mdl
models/lastunic/weapons/shock/p_shock.mdl
models/lastunic/weapons/shock/v_shock.mdl
models/lastunic/weapons/shock/w_shock.mdl
models/lastunic/weapons/shock/w_shock_rifle.mdl
models/lastunic/weapons/snarkblack/p_squeak.mdl
models/lastunic/weapons/snarkblack/v_squeak.mdl
models/lastunic/weapons/snarkblack/w_sqknest.mdl
models/lastunic/weapons/snarkblack/w_squeak.mdl
models/lastunic/weapons/w_chainammo.mdl
models/lastunic/weapons/w_deagle_ammo.mdl
models/lastunic/weapons/w_gaussammo.mdl
models/lastunic/weapons/w_shotboxbig.mdl
models/lastunic/zombie18.mdl
models/lastunic/zombiecoupe.mdl
models/lastunic/zombiegirlcuite.mdl
models/lastunic/zombiegmhl2.mdl
models/lastunic/zombiegrunt.mdl
models/lastunic/zombiehl2b.mdl
models/sa13/apache.mdl
models/sa13/big_mom.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/p_akimbotmp.mdl
models/sa13/p_akimbotmpg.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_laser.mdl
models/sa13/p_med.mdl
models/sa13/p_mine.mdl
models/sa13/p_pancor.mdl
models/sa13/p_scythe.mdl
models/sa13/p_tmp.mdl
models/sa13/pit_drone.mdl
models/sa13/sas.mdl
models/sa13/strooper.mdl
models/sa13/theunicgold.mdl
models/sa13/v_akimbomp5k.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_laser.mdl
models/sa13/v_med.mdl
models/sa13/v_mine.mdl
models/sa13/v_pancor.mdl
models/sa13/v_scythe.mdl
models/sa13/w_akimbotmp.mdl
models/sa13/w_akimbotmpg.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_laser.mdl
models/sa13/w_med.mdl
models/sa13/w_mine.mdl
models/sa13/w_pancor.mdl
models/sa13/w_scythe.mdl
models/sa13/w_tmp.mdl
models/sa13/zombie.mdl
models/scmod/npcs/hgrunt/beanhad.mdl
models/scmod/npcs/hgrunt/garompa2.mdl
models/scmod/scientist_female.mdl
sa13full.wad
sound/lastunic/ambience/alarma.ogg
sound/lastunic/ambience/alarmex1.ogg
sound/lastunic/ambience/alienalarme.ogg
sound/lastunic/ambience/aliencom.ogg
sound/lastunic/ambience/aliencom1.ogg
sound/lastunic/ambience/aliencom11.ogg
sound/lastunic/ambience/aliencom13.ogg
sound/lastunic/ambience/aliencom14.ogg
sound/lastunic/ambience/aliencom15.ogg
sound/lastunic/ambience/aliencom17.ogg
sound/lastunic/ambience/aliencom18.ogg
sound/lastunic/ambience/aliencom2.ogg
sound/lastunic/ambience/aliencom21.ogg
sound/lastunic/ambience/aliencom23.ogg
sound/lastunic/ambience/aliencom27.ogg
sound/lastunic/ambience/aliencom3.ogg
sound/lastunic/ambience/aliencom4.ogg
sound/lastunic/ambience/aliencom5.ogg
sound/lastunic/ambience/aliencom6.ogg
sound/lastunic/ambience/aliencom7.ogg
sound/lastunic/ambience/aliencom8.ogg
sound/lastunic/ambience/aliencom9.ogg
sound/lastunic/ambience/bip1.ogg
sound/lastunic/ambience/bip3.ogg
sound/lastunic/ambience/canon.ogg
sound/lastunic/ambience/chien.ogg
sound/lastunic/ambience/eau3.ogg
sound/lastunic/ambience/egout.ogg
sound/lastunic/ambience/enalien.ogg
sound/lastunic/ambience/explosion1.ogg
sound/lastunic/ambience/fly.ogg
sound/lastunic/ambience/generique11.ogg
sound/lastunic/ambience/generique12.ogg
sound/lastunic/ambience/genfin.ogg
sound/lastunic/ambience/goutes_grotte.ogg
sound/lastunic/ambience/grince.ogg
sound/lastunic/ambience/heldamag.ogg
sound/lastunic/ambience/helico4.ogg
sound/lastunic/ambience/machine13.ogg
sound/lastunic/ambience/machine14.ogg
sound/lastunic/ambience/machinex.ogg
sound/lastunic/ambience/mg_10.ogg
sound/lastunic/ambience/mg_9.ogg
sound/lastunic/ambience/pc.ogg
sound/lastunic/ambience/pc1.ogg
sound/lastunic/ambience/pc2.ogg
sound/lastunic/ambience/pc3.ogg
sound/lastunic/ambience/rocketfire1.ogg
sound/lastunic/ambience/vent2.ogg
sound/lastunic/ambience/vente.ogg
sound/lastunic/ambience/ventf.ogg
sound/lastunic/ambience/ventg.ogg
sound/lastunic/ambience/venth.ogg
sound/lastunic/ambience/ventr.ogg
sound/lastunic/ambience/wind1.ogg
sound/lastunic/zombie/claw_miss1.ogg
sound/lastunic/zombie/claw_miss2.ogg
sound/lastunic/zombie/claw_strike1.ogg
sound/lastunic/zombie/claw_strike2.ogg
sound/lastunic/zombie/claw_strike3.ogg
sound/sa13/ambience/birds10.ogg
sound/sa13/ambience/birds11.ogg
sound/sa13/ambience/birds5.ogg
sound/sa13/ambience/birds6.ogg
sound/sa13/ambience/birds7.ogg
sound/sa13/ambience/birds8.ogg
sound/sa13/ambience/blinde.ogg
sound/sa13/ambience/diesel.ogg
sound/sa13/ambience/eau1.ogg
sound/sa13/ambience/frog.ogg
sound/sa13/ambience/frog2.ogg
sound/sa13/ambience/goutte1.ogg
sound/sa13/ambience/grillons.ogg
sound/sa13/ambience/machines2.ogg
sound/sa13/ambience/machines3.ogg
sound/sa13/ambience/pvision.ogg
sound/sa13/ambience/rebip.ogg
sound/sa13/ambience/turbine.ogg
sound/sa13/ambience/vag.ogg
sound/sa13/ambience/venta.ogg
sound/sa13/ambience/ventd.ogg
sound/sa13/ambience/xlmflap.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scientist_female/absolutely.ogg
sound/scientist_female/ahmygod.ogg
sound/scientist_female/anotherone.ogg
sound/scientist_female/anyworkatall.ogg
sound/scientist_female/arewelost.ogg
sound/scientist_female/arewewaiting.ogg
sound/scientist_female/bah.ogg
sound/scientist_female/becareful.ogg
sound/scientist_female/begpardon.ogg
sound/scientist_female/cantbebothered.ogg
sound/scientist_female/cantbeserious.ogg
sound/scientist_female/canthiswait.ogg
sound/scientist_female/caretomoveit.ogg
sound/scientist_female/coffeecup.ogg
sound/scientist_female/controlyourself.ogg
sound/scientist_female/dilidaling.ogg
sound/scientist_female/doctor.ogg
sound/scientist_female/doingsomething.ogg
sound/scientist_female/dontberidiculous.ogg
sound/scientist_female/dontknow.ogg
sound/scientist_female/enoughexcite.ogg
sound/scientist_female/excuseme.ogg
sound/scientist_female/excuseme2.ogg
sound/scientist_female/fear.ogg
sound/scientist_female/fear1.ogg
sound/scientist_female/fear2.ogg
sound/scientist_female/fear3.ogg
sound/scientist_female/fear4.ogg
sound/scientist_female/friendlyfire.ogg
sound/scientist_female/friendlyfire1.ogg
sound/scientist_female/friendlyfire3.ogg
sound/scientist_female/friendlyfire4.ogg
sound/scientist_female/gasp.ogg
sound/scientist_female/gasp2.ogg
sound/scientist_female/gasp3.ogg
sound/scientist_female/gasp4.ogg
sound/scientist_female/goingtostay.ogg
sound/scientist_female/goodshow.ogg
sound/scientist_female/goon.ogg
sound/scientist_female/goon2.ogg
sound/scientist_female/gotcontrol.ogg
sound/scientist_female/greetings.ogg
sound/scientist_female/hello.ogg
sound/scientist_female/hello2.ogg
sound/scientist_female/help.ogg
sound/scientist_female/holdstill.ogg
sound/scientist_female/idnever.ogg
sound/scientist_female/illstay.ogg
sound/scientist_female/illwatchback.ogg
sound/scientist_female/imbusy.ogg
sound/scientist_female/imhit.ogg
sound/scientist_female/imnotsure.ogg
sound/scientist_female/inconclusive.ogg
sound/scientist_female/justholdon.ogg
sound/scientist_female/later.ogg
sound/scientist_female/leadtheway.ogg
sound/scientist_female/leadtheway2.ogg
sound/scientist_female/leadtheway3.ogg
sound/scientist_female/leavemealone.ogg
sound/scientist_female/leavemehere.ogg
sound/scientist_female/letmehelp.ogg
sound/scientist_female/letsgetmoving.ogg
sound/scientist_female/letsgo.ogg
sound/scientist_female/letstrythis.ogg
sound/scientist_female/littlecorner.ogg
sound/scientist_female/lookinto.ogg
sound/scientist_female/lookout.ogg
sound/scientist_female/moreless.ogg
sound/scientist_female/no.ogg
sound/scientist_female/ofcoursenot.ogg
sound/scientist_female/ohdear.ogg
sound/scientist_female/ohmy.ogg
sound/scientist_female/ohthankgod.ogg
sound/scientist_female/pacemaker.ogg
sound/scientist_female/pain.ogg
sound/scientist_female/pain1.ogg
sound/scientist_female/pain2.ogg
sound/scientist_female/pain3.ogg
sound/scientist_female/pain4.ogg
sound/scientist_female/pain5.ogg
sound/scientist_female/pain6.ogg
sound/scientist_female/positively.ogg
sound/scientist_female/precisely.ogg
sound/scientist_female/probablysafer.ogg
sound/scientist_female/quiteimpressive.ogg
sound/scientist_female/rant.ogg
sound/scientist_female/rant1.ogg
sound/scientist_female/rant2.ogg
sound/scientist_female/rant3.ogg
sound/scientist_female/rant4.ogg
sound/scientist_female/reload.ogg
sound/scientist_female/reload1.ogg
sound/scientist_female/reload2.ogg
sound/scientist_female/reload3.ogg
sound/scientist_female/reload4.ogg
sound/scientist_female/reload5.ogg
sound/scientist_female/reload6.ogg
sound/scientist_female/scouton.ogg
sound/scientist_female/seenyourdegree.ogg
sound/scientist_female/shouldgetgoing.ogg
sound/scientist_female/shouldpresson.ogg
sound/scientist_female/shouldwego.ogg
sound/scientist_female/shutup.ogg
sound/scientist_female/smell.ogg
sound/scientist_female/someforpain.ogg
sound/scientist_female/someoneasking.ogg
sound/scientist_female/sonowwhat.ogg
sound/scientist_female/testchamber2.ogg
sound/scientist_female/thathurt.ogg
sound/scientist_female/thinkingwhat.ogg
sound/scientist_female/thisway.ogg
sound/scientist_female/waituntiltest.ogg
sound/scientist_female/watchout2.ogg
sound/scientist_female/wellplayed.ogg
sound/scientist_female/whatareyoudoing.ogg
sound/scientist_female/whatareyouwaiting.ogg
sound/scientist_female/whatnext.ogg
sound/scientist_female/whattothink.ogg
sound/scientist_female/whenpresson.ogg
sound/scientist_female/whyaskingme.ogg
sound/scientist_female/willweleave.ogg
sound/scientist_female/yes.ogg
sound/scientist_female/yes2.ogg
sound/scientist_female/youknowwhere.ogg
sound/scientist_female/youneverknow.ogg
sound/scientist_female/yourepeat.ogg
sound/scmod/lastunic/dialogs/lastunic_8/aloha.ogg
sound/scmod/lastunic/dialogs/lastunic_8/dog.ogg
sound/scmod/lastunic/dialogs/lastunic_8/garompa1.ogg
sound/scmod/lastunic/dialogs/lastunic_8/gme.ogg
sound/scmod/lastunic/dialogs/lastunic_8/hq1.ogg
sound/scmod/lastunic/dialogs/lastunic_8/mc.ogg
sound/scmod/lastunic/dialogs/lastunic_8/me.ogg
sound/scmod/lastunic/dialogs/lastunic_8/me1.ogg
sound/scmod/lastunic/dialogs/lastunic_8/messag.ogg
sound/scmod/lastunic/dialogs/lastunic_8/mexi.ogg
sound/scmod/lastunic/dialogs/lastunic_8/mm2.ogg
sound/scmod/lastunic/dialogs/lastunic_8/mrat.ogg
sound/scmod/lastunic/dialogs/lastunic_8/trd.ogg
sound/scmod/lastunic/dialogs/lastunic_8/unictalk1.ogg
sound/scmod/lastunic/garompatheme_intro.ogg
sound/scmod/lastunic/garompatheme_loop.ogg
sound/scmod/lastunic/garompatheme_outro.ogg
sound/weapons/629_shells_land.wav
sound/weapons/ak100_magin.wav
sound/weapons/ak100_magout.wav
sound/weapons/ak100_safety.wav
sound/weapons/de_deploy.wav
sound/weapons/egon_draw.wav
sound/weapons/foley_grabmag.wav
sound/weapons/lastunic/357/357_fire2.wav
sound/weapons/lastunic/357/357_shot1.wav
sound/weapons/lastunic/ak47/ak47-1.wav
sound/weapons/lastunic/awp/awp1.wav
sound/weapons/lastunic/deagle/deagle-1.wav
sound/weapons/lastunic/elite/elite-1.wav
sound/weapons/lastunic/shotgun/shotgun_dbl_fire7.wav
sound/weapons/lastunic/shotgun/shotgun_fire6.wav
sound/weapons/lastunic/uzi/shoot1.wav
sound/weapons/m82_cock.wav
sound/weapons/m82_magin.wav
sound/weapons/m82_magout.wav
sound/weapons/mp5k_boltback.wav
sound/weapons/mp5k_boltslap.wav
sound/weapons/mp5k_magin.wav
sound/weapons/mp5k_magout.wav
sound/weapons/mp5k_slamtogether.wav
sound/weapons/mp5k_toakimbo.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sound/weapons/stinger_reload.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
