// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/canyonbk.tga
gfx/env/canyondn.tga
gfx/env/canyonft.tga
gfx/env/canyonlf.tga
gfx/env/canyonrt.tga
gfx/env/canyonup.tga
lastunicfull.wad
models/lastunic/apachend.mdl
models/lastunic/bullngs.mdl
models/lastunic/gonomefresh.mdl
models/lastunic/headcrabh.mdl
models/lastunic/houndoneye.mdl
models/lastunic/hwdesertunic.mdl
models/lastunic/hwsku.mdl
models/lastunic/hwzomb.mdl
models/lastunic/massndesert.mdl
models/lastunic/protoleech.mdl
models/lastunic/shark.mdl
models/lastunic/unicarcher.mdl
models/lastunic/weapons/357old/p_357.mdl
models/lastunic/weapons/357old/v_357.mdl
models/lastunic/weapons/357old/w_357.mdl
models/lastunic/weapons/ak47black/p_9mmar.mdl
models/lastunic/weapons/ak47black/v_9mmar.mdl
models/lastunic/weapons/ak47black/w_9mmar.mdl
models/lastunic/weapons/ak47black/w_mp5_clip.mdl
models/lastunic/weapons/awpcamo/p_m40a1.mdl
models/lastunic/weapons/awpcamo/v_m40a1.mdl
models/lastunic/weapons/awpcamo/w_m40a1.mdl
models/lastunic/weapons/deaglecamo/p_desert_eagle.mdl
models/lastunic/weapons/deaglecamo/v_desert_eagle.mdl
models/lastunic/weapons/deaglecamo/w_desert_eagle.mdl
models/lastunic/weapons/grenadem61/p_grenade.mdl
models/lastunic/weapons/grenadem61/v_grenade.mdl
models/lastunic/weapons/grenadem61/w_grenade.mdl
models/lastunic/weapons/m16camo/p_m16.mdl
models/lastunic/weapons/m16camo/v_m16a2.mdl
models/lastunic/weapons/m16camo/w_m16.mdl
models/lastunic/weapons/minigunblack/p_minigunidle.mdl
models/lastunic/weapons/minigunblack/p_minigunspin.mdl
models/lastunic/weapons/minigunblack/v_minigun.mdl
models/lastunic/weapons/minigunblack/w_minigun.mdl
models/lastunic/weapons/pkm/p_saw.mdl
models/lastunic/weapons/pkm/v_saw.mdl
models/lastunic/weapons/pkm/w_saw.mdl
models/lastunic/weapons/pkm/w_saw_clip.mdl
models/lastunic/weapons/rpgrocketgrey.mdl
models/lastunic/weapons/shock/p_shock.mdl
models/lastunic/weapons/shock/v_shock.mdl
models/lastunic/weapons/shock/w_shock.mdl
models/lastunic/weapons/shock/w_shock_rifle.mdl
models/lastunic/weapons/usp/p_9mmhandgun.mdl
models/lastunic/weapons/usp/v_9mmhandgun.mdl
models/lastunic/weapons/usp/w_9mmhandgun.mdl
models/lastunic/weapons/w_357ammobox.mdl
models/lastunic/weapons/w_chainammo.mdl
models/lastunic/weapons/w_gaussammo.mdl
models/lastunic/weapons/w_rpgammogrey.mdl
models/lastunic/weapons/w_shotbox.mdl
models/lastunic/zombiegmhl2.mdl
models/lastunic/zombiegrunt.mdl
models/lastunic/zombiegrunt2.mdl
models/lastunic/zombiehl2b.mdl
models/lastunic/zombietec.mdl
models/sa13/big_mom.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/p_akimbomp5k.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_med.mdl
models/sa13/p_mine.mdl
models/sa13/p_mp5k.mdl
models/sa13/p_rpgrey.mdl
models/sa13/p_sawedoff.mdl
models/sa13/p_scythe.mdl
models/sa13/pit_drone.mdl
models/sa13/sas.mdl
models/sa13/strooper.mdl
models/sa13/v_akimbomp5k.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_med.mdl
models/sa13/v_mine.mdl
models/sa13/v_rpgrey.mdl
models/sa13/v_sawedoff.mdl
models/sa13/v_scythe.mdl
models/sa13/w_akimbomp5k.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_med.mdl
models/sa13/w_mine.mdl
models/sa13/w_mp5k.mdl
models/sa13/w_rpgrey.mdl
models/sa13/w_sawedoff.mdl
models/sa13/w_scythe.mdl
models/sa13/zombie.mdl
sa13full.wad
sound/lastunic/ambience/alienalarme.ogg
sound/lastunic/ambience/aliencom1.ogg
sound/lastunic/ambience/aliencom6.ogg
sound/lastunic/ambience/bruitslointains.ogg
sound/lastunic/ambience/canon.ogg
sound/lastunic/ambience/cricket5.ogg
sound/lastunic/ambience/egout.ogg
sound/lastunic/ambience/fontaine.ogg
sound/lastunic/ambience/generique3.ogg
sound/lastunic/ambience/goutes_grotte.ogg
sound/lastunic/ambience/machine13.ogg
sound/lastunic/ambience/mg_10.ogg
sound/lastunic/ambience/mg_9.ogg
sound/lastunic/ambience/miuche3.ogg
sound/lastunic/ambience/rocketfire1.ogg
sound/lastunic/ambience/souffle.ogg
sound/lastunic/ambience/souffle1.ogg
sound/lastunic/ambience/vent2.ogg
sound/lastunic/ambience/ventg.ogg
sound/lastunic/ambience/ventr.ogg
sound/lastunic/ambience/wind1.ogg
sound/lastunic/zombie/claw_miss1.ogg
sound/lastunic/zombie/claw_miss2.ogg
sound/lastunic/zombie/claw_strike1.ogg
sound/lastunic/zombie/claw_strike2.ogg
sound/lastunic/zombie/claw_strike3.ogg
sound/sa13/ambience/alarmeu1.ogg
sound/sa13/ambience/arbre2.ogg
sound/sa13/ambience/arbre3.ogg
sound/sa13/ambience/grillons.ogg
sound/sa13/ambience/lan1shut.ogg
sound/sa13/ambience/sewer1.ogg
sound/sa13/ambience/xlmflap.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/weapons/reload2.wav
sound/sa13/weapons/saw_reload.wav
sound/sa13/weapons/sniper_reload_first_seq.wav
sound/sa13/weapons/sniper_reload_second_seq.wav
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scmod/lastunic/dialogs/lastunic_3/escape.ogg
sound/weapons/foley_grabmag.wav
sound/weapons/lastunic/357/357_fire2.wav
sound/weapons/lastunic/357/357_shot1.wav
sound/weapons/lastunic/ak47/ak47-1.wav
sound/weapons/lastunic/awp/awp1.wav
sound/weapons/lastunic/deagle/deagle-1.wav
sound/weapons/lastunic/elite/elite-1.wav
sound/weapons/lastunic/shotgun/shotgun_dbl_fire7.wav
sound/weapons/lastunic/shotgun/shotgun_fire6.wav
sound/weapons/lastunic/uzi/shoot1.wav
sound/weapons/mp5k_boltback.wav
sound/weapons/mp5k_boltslap.wav
sound/weapons/mp5k_magin.wav
sound/weapons/mp5k_magout.wav
sound/weapons/mp5k_slamtogether.wav
sound/weapons/mp5k_toakimbo.wav
sound/weapons/python/clipin.wav
sound/weapons/python/clipout.wav
sound/weapons/python/draw.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
