// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/desert06bk.tga
gfx/env/desert06dn.tga
gfx/env/desert06ft.tga
gfx/env/desert06lf.tga
gfx/env/desert06rt.tga
gfx/env/desert06up.tga
lastunicfull.wad
models/lastunic/bullngs.mdl
models/lastunic/doomguy.mdl
models/lastunic/gonomefresh.mdl
models/lastunic/headcrabf.mdl
models/lastunic/headcrabh.mdl
models/lastunic/headcrabselect.mdl
models/lastunic/hwsku.mdl
models/lastunic/hwzomb.mdl
models/lastunic/massnbundes.mdl
models/lastunic/massndesert.mdl
models/lastunic/massnngru.mdl
models/lastunic/props/ansat6.mdl
models/lastunic/props/grandgenerateur.mdl
models/lastunic/props/grillemur.mdl
models/lastunic/props/hammer01.mdl
models/lastunic/props/hammer01_gun.mdl
models/lastunic/props/hummer.mdl
models/lastunic/props/pallet_with_bags2.mdl
models/lastunic/props/palmier5.mdl
models/lastunic/props/palmier8.mdl
models/lastunic/props/plante.mdl
models/lastunic/props/plante4.mdl
models/lastunic/props/plotbeton.mdl
models/lastunic/protoleech.mdl
models/lastunic/weapons/357normal/p_357.mdl
models/lastunic/weapons/357normal/v_357.mdl
models/lastunic/weapons/357normal/w_357.mdl
models/lastunic/weapons/berettawhite/p_9mmhandgun.mdl
models/lastunic/weapons/berettawhite/v_9mmhandgun.mdl
models/lastunic/weapons/berettawhite/w_9mmhandgun.mdl
models/lastunic/weapons/deaglecamo/p_desert_eagle.mdl
models/lastunic/weapons/deaglecamo/v_desert_eagle.mdl
models/lastunic/weapons/deaglecamo/w_desert_eagle.mdl
models/lastunic/weapons/grenadem61/p_grenade.mdl
models/lastunic/weapons/grenadem61/v_grenade.mdl
models/lastunic/weapons/grenadem61/w_grenade.mdl
models/lastunic/weapons/minigunblack/p_minigunidle.mdl
models/lastunic/weapons/minigunblack/p_minigunspin.mdl
models/lastunic/weapons/minigunblack/v_minigun.mdl
models/lastunic/weapons/minigunblack/w_minigun.mdl
models/lastunic/weapons/mp5camo/p_9mmar.mdl
models/lastunic/weapons/mp5camo/v_9mmar.mdl
models/lastunic/weapons/mp5camo/w_9mmar.mdl
models/lastunic/weapons/shock/p_shock.mdl
models/lastunic/weapons/shock/v_shock.mdl
models/lastunic/weapons/shock/w_shock.mdl
models/lastunic/weapons/shock/w_shock_rifle.mdl
models/lastunic/weapons/sniper/p_m40a1.mdl
models/lastunic/weapons/sniper/v_m40a1.mdl
models/lastunic/weapons/sniper/w_m40a1.mdl
models/lastunic/weapons/w_357ammobox.mdl
models/lastunic/weapons/w_chainammo.mdl
models/lastunic/weapons/w_gaussammo.mdl
models/lastunic/weapons/w_shotbox.mdl
models/lastunic/zombiegrunt.mdl
models/lastunic/zombietec.mdl
models/sa13/big_mom.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/ng_boys.mdl
models/sa13/ngt_boys.mdl
models/sa13/p_benelli.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_med.mdl
models/sa13/p_mine.mdl
models/sa13/p_scythe.mdl
models/sa13/sas.mdl
models/sa13/strooper.mdl
models/sa13/v_benelli.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_med.mdl
models/sa13/v_mine.mdl
models/sa13/v_scythe.mdl
models/sa13/w_benelli.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_med.mdl
models/sa13/w_mine.mdl
models/sa13/w_scythe.mdl
models/sa13/zombie.mdl
sa13full.wad
sound/ambience/wind4.wav
sound/lastunic/ambience/alarm3.ogg
sound/lastunic/ambience/bip3.ogg
sound/lastunic/ambience/cricket5.ogg
sound/lastunic/ambience/crickets.ogg
sound/lastunic/ambience/def.ogg
sound/lastunic/ambience/egout.ogg
sound/lastunic/ambience/explosionloin.ogg
sound/lastunic/ambience/fly.ogg
sound/lastunic/ambience/generique1.ogg
sound/lastunic/ambience/goutte.ogg
sound/lastunic/ambience/mg_10.ogg
sound/lastunic/ambience/rocketfire1.ogg
sound/lastunic/ambience/souffle.ogg
sound/lastunic/ambience/souffle1.ogg
sound/lastunic/ambience/vente.ogg
sound/lastunic/ambience/ventg.ogg
sound/lastunic/ambience/wind1.ogg
sound/lastunic/zombie/claw_miss1.ogg
sound/lastunic/zombie/claw_miss2.ogg
sound/lastunic/zombie/claw_strike1.ogg
sound/lastunic/zombie/claw_strike2.ogg
sound/lastunic/zombie/claw_strike3.ogg
sound/sa13/ambience/alarm.ogg
sound/sa13/ambience/bip4.ogg
sound/sa13/ambience/eau1.ogg
sound/sa13/ambience/faucon2.ogg
sound/sa13/ambience/frog2.ogg
sound/sa13/ambience/grillons.ogg
sound/sa13/ambience/machines.ogg
sound/sa13/ambience/machines4.ogg
sound/sa13/ambience/sewer1.ogg
sound/sa13/ambience/underwater.ogg
sound/sa13/ambience/venta.ogg
sound/sa13/ambience/ventc.ogg
sound/sa13/ambience/ventd.ogg
sound/sa13/ambience/water1.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scmod/lastunic/dialogs/lastunic_1/doomstory.ogg
sound/scmod/lastunic/dialogs/lastunic_1/gg.ogg
sound/scmod/lastunic/dialogs/lastunic_1/objectives.ogg
sound/scmod/lastunic/dialogs/lastunic_1/tunneltxt.ogg
sound/weapons/lastunic/357/357_fire2.wav
sound/weapons/lastunic/357/357_shot1.wav
sound/weapons/lastunic/ak47/ak47-1.wav
sound/weapons/lastunic/awp/awp1.wav
sound/weapons/lastunic/deagle/deagle-1.wav
sound/weapons/lastunic/elite/elite-1.wav
sound/weapons/lastunic/shotgun/shotgun_dbl_fire7.wav
sound/weapons/lastunic/shotgun/shotgun_fire6.wav
sound/weapons/lastunic/uzi/shoot1.wav
sound/weapons/m3_pump.wav
sound/weapons/m9_drawcock.wav
sound/weapons/m9_pickup.wav
sound/weapons/m9_slideback.wav
sound/weapons/m9_sliderelease.wav
sound/weapons/mp5_safety.wav
sound/weapons/python/clipin.wav
sound/weapons/python/clipout.wav
sound/weapons/python/draw.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
