// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/havbk.tga
gfx/env/havdn.tga
gfx/env/havft.tga
gfx/env/havlf.tga
gfx/env/havrt.tga
gfx/env/havup.tga
lastunicfull.wad
models/lastunic/araignee.mdl
models/lastunic/gonomefresh.mdl
models/lastunic/headcrab_fast.mdl
models/lastunic/headcrabh.mdl
models/lastunic/headcrabselect.mdl
models/lastunic/hwdesertunic.mdl
models/lastunic/hwdesertunic3.mdl
models/lastunic/props/antensatvieil.mdl
models/lastunic/props/antsat3.mdl
models/lastunic/props/antsatpied.mdl
models/lastunic/props/antsatpourrie.mdl
models/lastunic/props/campe2.mdl
models/lastunic/props/canape.mdl
models/lastunic/props/clim2.mdl
models/lastunic/props/clim3.mdl
models/lastunic/props/cuisinemonte.mdl
models/lastunic/props/deressing.mdl
models/lastunic/props/fontainebrique.mdl
models/lastunic/props/lingecorde.mdl
models/lastunic/props/lingecorde2.mdl
models/lastunic/props/mercedes2.mdl
models/lastunic/props/palm08.mdl
models/lastunic/props/palmier5.mdl
models/lastunic/props/palmier8.mdl
models/lastunic/props/plante.mdl
models/lastunic/props/plante2.mdl
models/lastunic/props/plante4.mdl
models/lastunic/props/transfo.mdl
models/lastunic/props/vanvert.mdl
models/lastunic/props/vanvert2.mdl
models/lastunic/sentry_0.mdl
models/lastunic/shark.mdl
models/lastunic/weapons/357long/p_357.mdl
models/lastunic/weapons/357long/v_357.mdl
models/lastunic/weapons/357long/w_357.mdl
models/lastunic/weapons/barrett/p_m40a1.mdl
models/lastunic/weapons/barrett/v_m40a1.mdl
models/lastunic/weapons/barrett/w_m40a1.mdl
models/lastunic/weapons/barrett/w_m40a1clip.mdl
models/lastunic/weapons/blueegon/p_egon.mdl
models/lastunic/weapons/blueegon/v_egon.mdl
models/lastunic/weapons/blueegon/w_egon.mdl
models/lastunic/weapons/deaglecamo/p_desert_eagle.mdl
models/lastunic/weapons/deaglecamo/v_desert_eagle.mdl
models/lastunic/weapons/deaglecamo/w_desert_eagle.mdl
models/lastunic/weapons/glock19/p_9mmhandgun.mdl
models/lastunic/weapons/glock19/v_9mmhandgun.mdl
models/lastunic/weapons/glock19/w_9mmhandgun.mdl
models/lastunic/weapons/grenadergd/p_grenade.mdl
models/lastunic/weapons/grenadergd/v_grenade.mdl
models/lastunic/weapons/grenadergd/w_grenade.mdl
models/lastunic/weapons/mac10camo/p_2uzis.mdl
models/lastunic/weapons/mac10camo/p_2uzis_gold.mdl
models/lastunic/weapons/mac10camo/p_uzi.mdl
models/lastunic/weapons/mac10camo/p_uzi_gold.mdl
models/lastunic/weapons/mac10camo/v_uzi.mdl
models/lastunic/weapons/mac10camo/w_2uzis.mdl
models/lastunic/weapons/mac10camo/w_2uzis_gold.mdl
models/lastunic/weapons/mac10camo/w_uzi.mdl
models/lastunic/weapons/mac10camo/w_uzi_clip.mdl
models/lastunic/weapons/mac10camo/w_uzi_gold.mdl
models/lastunic/weapons/minigunblack/p_minigunidle.mdl
models/lastunic/weapons/minigunblack/p_minigunspin.mdl
models/lastunic/weapons/minigunblack/v_minigun.mdl
models/lastunic/weapons/minigunblack/w_minigun.mdl
models/lastunic/weapons/pkm/p_saw.mdl
models/lastunic/weapons/pkm/v_saw.mdl
models/lastunic/weapons/pkm/w_saw.mdl
models/lastunic/weapons/pkm/w_saw_clip.mdl
models/lastunic/weapons/satchelcamo/p_satchel.mdl
models/lastunic/weapons/satchelcamo/p_satchel_radio.mdl
models/lastunic/weapons/satchelcamo/v_satchel.mdl
models/lastunic/weapons/satchelcamo/v_satchel_radio.mdl
models/lastunic/weapons/satchelcamo/w_satchel.mdl
models/lastunic/weapons/shock/p_shock.mdl
models/lastunic/weapons/shock/v_shock.mdl
models/lastunic/weapons/shock/w_shock.mdl
models/lastunic/weapons/shock/w_shock_rifle.mdl
models/lastunic/weapons/snarkdesert/p_squeak.mdl
models/lastunic/weapons/snarkdesert/v_squeak.mdl
models/lastunic/weapons/snarkdesert/w_sqknest.mdl
models/lastunic/weapons/snarkdesert/w_squeak.mdl
models/lastunic/weapons/spascamo/p_shotgun.mdl
models/lastunic/weapons/spascamo/v_shotgun.mdl
models/lastunic/weapons/spascamo/w_shotgun.mdl
models/lastunic/weapons/w_357ammobox.mdl
models/lastunic/weapons/w_chainammo.mdl
models/lastunic/weapons/w_gaussammo.mdl
models/lastunic/weapons/w_rpgammocamo.mdl
models/lastunic/weapons/w_shotboxbig.mdl
models/lastunic/wolf.mdl
models/lastunic/zombie10.mdl
models/lastunic/zombie18.mdl
models/lastunic/zombie21.mdl
models/lastunic/zombiecoupe.mdl
models/lastunic/zombiegirlcuite.mdl
models/lastunic/zombiegmhl2.mdl
models/lastunic/zombiegrunt.mdl
models/lastunic/zombiegrunt2.mdl
models/lastunic/zombiehl2b.mdl
models/lastunic/zombietec.mdl
models/sa13/big_mom.mdl
models/sa13/elite.mdl
models/sa13/grenade.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/icky.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/ng_boys.mdl
models/sa13/p_akm.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_med.mdl
models/sa13/p_mine.mdl
models/sa13/p_rpgcamo.mdl
models/sa13/p_scythe.mdl
models/sa13/strooper.mdl
models/sa13/v_akm.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_med.mdl
models/sa13/v_mine.mdl
models/sa13/v_rpgcamo.mdl
models/sa13/v_scythe.mdl
models/sa13/w_akm.mdl
models/sa13/w_akm_clip.mdl
models/sa13/w_argrenade.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_med.mdl
models/sa13/w_mine.mdl
models/sa13/w_rpgcamo.mdl
models/sa13/w_scythe.mdl
models/sa13/zombie.mdl
sa13full.wad
sound/lastunic/ambience/canon.ogg
sound/lastunic/ambience/cricket5.ogg
sound/lastunic/ambience/crickets.ogg
sound/lastunic/ambience/eau3.ogg
sound/lastunic/ambience/generique5.ogg
sound/lastunic/ambience/goutes_grotte.ogg
sound/lastunic/ambience/goutte.ogg
sound/lastunic/ambience/h3.ogg
sound/lastunic/ambience/mg20.ogg
sound/lastunic/ambience/mg_10.ogg
sound/lastunic/ambience/mg_9.ogg
sound/lastunic/ambience/miuche3.ogg
sound/lastunic/ambience/mouche.ogg
sound/lastunic/ambience/portecri.ogg
sound/lastunic/ambience/rocketfire1.ogg
sound/lastunic/ambience/souffle.ogg
sound/lastunic/ambience/souffle1.ogg
sound/lastunic/ambience/vente.ogg
sound/lastunic/ambience/ventf.ogg
sound/lastunic/ambience/ventg.ogg
sound/lastunic/ambience/ventr.ogg
sound/lastunic/ambience/wind1.ogg
sound/lastunic/zombie/claw_miss1.ogg
sound/lastunic/zombie/claw_miss2.ogg
sound/lastunic/zombie/claw_strike1.ogg
sound/lastunic/zombie/claw_strike2.ogg
sound/lastunic/zombie/claw_strike3.ogg
sound/sa13/ambience/birds2.ogg
sound/sa13/ambience/eau1.ogg
sound/sa13/ambience/faucon.ogg
sound/sa13/ambience/faucon2.ogg
sound/sa13/ambience/gegene.ogg
sound/sa13/ambience/goutte1.ogg
sound/sa13/ambience/grillons.ogg
sound/sa13/ambience/h2.ogg
sound/sa13/ambience/lan1shut.ogg
sound/sa13/ambience/sewer1.ogg
sound/sa13/ambience/vag.ogg
sound/sa13/ambience/ventb.ogg
sound/sa13/ambience/ventc.ogg
sound/sa13/ambience/water1.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scmod/lastunic/dialogs/lastunic_5/mes.ogg
sound/scmod/lastunic/dialogs/lastunic_5/mesp.ogg
sound/scmod/lastunic/dialogs/lastunic_5/mp.ogg
sound/weapons/AK-101/boltpull.wav
sound/weapons/AK-101/gp25_reload.wav
sound/weapons/AK-101/magin.wav
sound/weapons/AK-101/magout.wav
sound/weapons/egon_draw.wav
sound/weapons/lastunic/357/357_fire2.wav
sound/weapons/lastunic/357/357_shot1.wav
sound/weapons/lastunic/ak47/ak47-1.wav
sound/weapons/lastunic/awp/awp1.wav
sound/weapons/lastunic/deagle/deagle-1.wav
sound/weapons/lastunic/elite/elite-1.wav
sound/weapons/lastunic/shotgun/shotgun_dbl_fire7.wav
sound/weapons/lastunic/shotgun/shotgun_fire6.wav
sound/weapons/lastunic/uzi/shoot1.wav
sound/weapons/m82_cock.wav
sound/weapons/m82_magin.wav
sound/weapons/m82_magout.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
