// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/crashsitebk.tga
gfx/env/crashsitedn.tga
gfx/env/crashsiteft.tga
gfx/env/crashsitelf.tga
gfx/env/crashsitert.tga
gfx/env/crashsiteup.tga
lastunicfull.wad
models/lastunic/apachedesert.mdl
models/lastunic/bullngs.mdl
models/lastunic/gonomefresh.mdl
models/lastunic/headcrabf.mdl
models/lastunic/headcrabh.mdl
models/lastunic/headcrabselect.mdl
models/lastunic/houndoneye.mdl
models/lastunic/hwsku.mdl
models/lastunic/hwzomb.mdl
models/lastunic/massndesert.mdl
models/lastunic/protoleech.mdl
models/lastunic/riky.mdl
models/lastunic/rikyt.mdl
models/lastunic/shark.mdl
models/lastunic/unicarcher.mdl
models/lastunic/weapons/357normal/p_357.mdl
models/lastunic/weapons/357normal/v_357.mdl
models/lastunic/weapons/357normal/w_357.mdl
models/lastunic/weapons/awpcamo/p_m40a1.mdl
models/lastunic/weapons/awpcamo/v_m40a1.mdl
models/lastunic/weapons/awpcamo/w_m40a1.mdl
models/lastunic/weapons/berettawhite/p_9mmhandgun.mdl
models/lastunic/weapons/berettawhite/v_9mmhandgun.mdl
models/lastunic/weapons/berettawhite/w_9mmhandgun.mdl
models/lastunic/weapons/deaglecamo/p_desert_eagle.mdl
models/lastunic/weapons/deaglecamo/v_desert_eagle.mdl
models/lastunic/weapons/deaglecamo/w_desert_eagle.mdl
models/lastunic/weapons/grenadem61/p_grenade.mdl
models/lastunic/weapons/grenadem61/v_grenade.mdl
models/lastunic/weapons/grenadem61/w_grenade.mdl
models/lastunic/weapons/mac10camo/p_2uzis.mdl
models/lastunic/weapons/mac10camo/p_2uzis_gold.mdl
models/lastunic/weapons/mac10camo/p_uzi.mdl
models/lastunic/weapons/mac10camo/p_uzi_gold.mdl
models/lastunic/weapons/mac10camo/v_uzi.mdl
models/lastunic/weapons/mac10camo/w_2uzis.mdl
models/lastunic/weapons/mac10camo/w_2uzis_gold.mdl
models/lastunic/weapons/mac10camo/w_uzi.mdl
models/lastunic/weapons/mac10camo/w_uzi_clip.mdl
models/lastunic/weapons/mac10camo/w_uzi_gold.mdl
models/lastunic/weapons/minigunblack/p_minigunidle.mdl
models/lastunic/weapons/minigunblack/p_minigunspin.mdl
models/lastunic/weapons/minigunblack/v_minigun.mdl
models/lastunic/weapons/minigunblack/w_minigun.mdl
models/lastunic/weapons/mp5camo/p_9mmar.mdl
models/lastunic/weapons/mp5camo/v_9mmar.mdl
models/lastunic/weapons/mp5camo/w_9mmar.mdl
models/lastunic/weapons/shock/p_shock.mdl
models/lastunic/weapons/shock/v_shock.mdl
models/lastunic/weapons/shock/w_shock.mdl
models/lastunic/weapons/shock/w_shock_rifle.mdl
models/lastunic/weapons/w_357ammobox.mdl
models/lastunic/weapons/w_chainammo.mdl
models/lastunic/weapons/w_gaussammo.mdl
models/lastunic/weapons/w_rpgammocamo.mdl
models/lastunic/weapons/w_shotbox.mdl
models/lastunic/zombie21.mdl
models/lastunic/zombiecoupe.mdl
models/lastunic/zombiegrunt.mdl
models/lastunic/zombiegrunt2.mdl
models/lastunic/zombiehl2b.mdl
models/lastunic/zombiemutant.mdl
models/lastunic/zombietec.mdl
models/sa13/big_mom.mdl
models/sa13/dady.mdl
models/sa13/dadyt.mdl
models/sa13/grenade.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/icky.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/ng_boys.mdl
models/sa13/p_akm.mdl
models/sa13/p_benelli.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_med.mdl
models/sa13/p_mine.mdl
models/sa13/p_rpgcamo.mdl
models/sa13/p_scythe.mdl
models/sa13/pit_drone.mdl
models/sa13/sas.mdl
models/sa13/strooper.mdl
models/sa13/tropical.mdl
models/sa13/v_akm.mdl
models/sa13/v_benelli.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_med.mdl
models/sa13/v_mine.mdl
models/sa13/v_rpgcamo.mdl
models/sa13/v_scythe.mdl
models/sa13/w_akm.mdl
models/sa13/w_akm_clip.mdl
models/sa13/w_argrenade.mdl
models/sa13/w_benelli.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_med.mdl
models/sa13/w_mine.mdl
models/sa13/w_rpgcamo.mdl
models/sa13/w_scythe.mdl
models/sa13/zombie.mdl
sa13full.wad
sound/lastunic/ambience/alarma.ogg
sound/lastunic/ambience/aliencom15.ogg
sound/lastunic/ambience/aliencom18.ogg
sound/lastunic/ambience/aliencom3.ogg
sound/lastunic/ambience/alieneffet2.ogg
sound/lastunic/ambience/alrm13.ogg
sound/lastunic/ambience/crickets.ogg
sound/lastunic/ambience/eau3.ogg
sound/lastunic/ambience/egout.ogg
sound/lastunic/ambience/enalien.ogg
sound/lastunic/ambience/fly.ogg
sound/lastunic/ambience/fontaine.ogg
sound/lastunic/ambience/generique2.ogg
sound/lastunic/ambience/mg_10.ogg
sound/lastunic/ambience/mg_6.ogg
sound/lastunic/ambience/rocketfire1.ogg
sound/lastunic/ambience/souffle.ogg
sound/lastunic/ambience/souffle1.ogg
sound/lastunic/ambience/vent2.ogg
sound/lastunic/ambience/vente.ogg
sound/lastunic/ambience/ventf.ogg
sound/lastunic/ambience/venth.ogg
sound/lastunic/ambience/wind1.ogg
sound/lastunic/zombie/claw_miss1.ogg
sound/lastunic/zombie/claw_miss2.ogg
sound/lastunic/zombie/claw_strike1.ogg
sound/lastunic/zombie/claw_strike2.ogg
sound/lastunic/zombie/claw_strike3.ogg
sound/sa13/ambience/alarmx.ogg
sound/sa13/ambience/ascen.ogg
sound/sa13/ambience/eau1.ogg
sound/sa13/ambience/gegene.ogg
sound/sa13/ambience/machines3.ogg
sound/sa13/ambience/underwater.ogg
sound/sa13/ambience/vag.ogg
sound/sa13/ambience/water1.ogg
sound/sa13/ambience/waterpump.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/weapons/AK-101/boltpull.wav
sound/weapons/AK-101/gp25_reload.wav
sound/weapons/AK-101/magin.wav
sound/weapons/AK-101/magout.wav
sound/weapons/lastunic/357/357_fire2.wav
sound/weapons/lastunic/357/357_shot1.wav
sound/weapons/lastunic/ak47/ak47-1.wav
sound/weapons/lastunic/awp/awp1.wav
sound/weapons/lastunic/deagle/deagle-1.wav
sound/weapons/lastunic/elite/elite-1.wav
sound/weapons/lastunic/shotgun/shotgun_dbl_fire7.wav
sound/weapons/lastunic/shotgun/shotgun_fire6.wav
sound/weapons/lastunic/uzi/shoot1.wav
sound/weapons/m3_pump.wav
sound/weapons/m9_drawcock.wav
sound/weapons/m9_pickup.wav
sound/weapons/m9_slideback.wav
sound/weapons/m9_sliderelease.wav
sound/weapons/mp5_safety.wav
sound/weapons/python/clipin.wav
sound/weapons/python/clipout.wav
sound/weapons/python/draw.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
