// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/havbk.tga
gfx/env/havdn.tga
gfx/env/havft.tga
gfx/env/havlf.tga
gfx/env/havrt.tga
gfx/env/havup.tga
lastunicfull.wad
models/lastunic/agrunt.mdl
models/lastunic/agruntf.mdl
models/lastunic/apachesn.mdl
models/lastunic/headcrab_fast.mdl
models/lastunic/headcrabh.mdl
models/lastunic/hwdesertunic3.mdl
models/lastunic/islave4.mdl
models/lastunic/islavemodify.mdl
models/lastunic/piranha.mdl
models/lastunic/props/antsatpied.mdl
models/lastunic/props/apc_desert.mdl
models/lastunic/props/bmpdesert.mdl
models/lastunic/props/bradley.mdl
models/lastunic/props/btr.mdl
models/lastunic/props/cc_lab_thermostat_01.mdl
models/lastunic/props/containment_cabinet.mdl
models/lastunic/props/serveur6.mdl
models/lastunic/props/supercomputer01.mdl
models/lastunic/sentry_0.mdl
models/lastunic/weapons/357long/p_357.mdl
models/lastunic/weapons/357long/v_357.mdl
models/lastunic/weapons/357long/w_357.mdl
models/lastunic/weapons/barrett/p_m40a1.mdl
models/lastunic/weapons/barrett/v_m40a1.mdl
models/lastunic/weapons/barrett/w_m40a1.mdl
models/lastunic/weapons/barrett/w_m40a1clip.mdl
models/lastunic/weapons/blueegon/p_egon.mdl
models/lastunic/weapons/blueegon/v_egon.mdl
models/lastunic/weapons/blueegon/w_egon.mdl
models/lastunic/weapons/deaglegold/p_desert_eagle.mdl
models/lastunic/weapons/deaglegold/v_desert_eagle.mdl
models/lastunic/weapons/deaglegold/w_desert_eagle.mdl
models/lastunic/weapons/glock19/p_9mmhandgun.mdl
models/lastunic/weapons/glock19/v_9mmhandgun.mdl
models/lastunic/weapons/glock19/w_9mmhandgun.mdl
models/lastunic/weapons/grenadergd/p_grenade.mdl
models/lastunic/weapons/grenadergd/v_grenade.mdl
models/lastunic/weapons/grenadergd/w_grenade.mdl
models/lastunic/weapons/m16camo/p_m16.mdl
models/lastunic/weapons/m16camo/v_m16a2.mdl
models/lastunic/weapons/m16camo/w_m16.mdl
models/lastunic/weapons/minigunblack/p_minigunidle.mdl
models/lastunic/weapons/minigunblack/p_minigunspin.mdl
models/lastunic/weapons/minigunblack/v_minigun.mdl
models/lastunic/weapons/minigunblack/w_minigun.mdl
models/lastunic/weapons/rpg/p_rpg.mdl
models/lastunic/weapons/rpg/rpgrocket.mdl
models/lastunic/weapons/rpg/v_rpg.mdl
models/lastunic/weapons/rpg/w_rpg.mdl
models/lastunic/weapons/rpg/w_rpgammo.mdl
models/lastunic/weapons/satchelcamo/p_satchel.mdl
models/lastunic/weapons/satchelcamo/p_satchel_radio.mdl
models/lastunic/weapons/satchelcamo/v_satchel.mdl
models/lastunic/weapons/satchelcamo/v_satchel_radio.mdl
models/lastunic/weapons/satchelcamo/w_satchel.mdl
models/lastunic/weapons/sawcamo/p_saw.mdl
models/lastunic/weapons/sawcamo/v_saw.mdl
models/lastunic/weapons/sawcamo/w_saw.mdl
models/lastunic/weapons/sawcamo/w_saw_clip.mdl
models/lastunic/weapons/shock/p_shock.mdl
models/lastunic/weapons/shock/v_shock.mdl
models/lastunic/weapons/shock/w_shock.mdl
models/lastunic/weapons/shock/w_shock_rifle.mdl
models/lastunic/weapons/snarkdesert/p_squeak.mdl
models/lastunic/weapons/snarkdesert/v_squeak.mdl
models/lastunic/weapons/snarkdesert/w_sqknest.mdl
models/lastunic/weapons/snarkdesert/w_squeak.mdl
models/lastunic/weapons/w_chainammo.mdl
models/lastunic/weapons/w_deagle_ammo.mdl
models/lastunic/weapons/w_gaussammo.mdl
models/lastunic/weapons/w_shotboxbig.mdl
models/lastunic/zombiehl2b.mdl
models/lastunic/zombietec.mdl
models/sa13/big_mom.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/p_akimbotmp.mdl
models/sa13/p_akimbotmpg.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_gaussb.mdl
models/sa13/p_med.mdl
models/sa13/p_mine.mdl
models/sa13/p_neostead.mdl
models/sa13/p_scythe.mdl
models/sa13/p_tmp.mdl
models/sa13/sas.mdl
models/sa13/strooper.mdl
models/sa13/v_akimbomp5k.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_gaussb.mdl
models/sa13/v_med.mdl
models/sa13/v_mine.mdl
models/sa13/v_neostead.mdl
models/sa13/v_scythe.mdl
models/sa13/w_akimbotmp.mdl
models/sa13/w_akimbotmpg.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_gaussb.mdl
models/sa13/w_med.mdl
models/sa13/w_mine.mdl
models/sa13/w_neostead.mdl
models/sa13/w_scythe.mdl
models/sa13/w_tmp.mdl
models/sa13/zombie.mdl
sa13full.wad
sound/lastunic/ambience/aliencom.ogg
sound/lastunic/ambience/aliencom1.ogg
sound/lastunic/ambience/aliencom11.ogg
sound/lastunic/ambience/aliencom13.ogg
sound/lastunic/ambience/aliencom14.ogg
sound/lastunic/ambience/aliencom16.ogg
sound/lastunic/ambience/aliencom2.ogg
sound/lastunic/ambience/aliencom24.ogg
sound/lastunic/ambience/aliencom27.ogg
sound/lastunic/ambience/aliencom4.ogg
sound/lastunic/ambience/alieneffet1.ogg
sound/lastunic/ambience/alieneffet3.ogg
sound/lastunic/ambience/bip1.ogg
sound/lastunic/ambience/canon.ogg
sound/lastunic/ambience/cricket5.ogg
sound/lastunic/ambience/crickets.ogg
sound/lastunic/ambience/generique7.ogg
sound/lastunic/ambience/generique8.ogg
sound/lastunic/ambience/goutes_grotte.ogg
sound/lastunic/ambience/goutte.ogg
sound/lastunic/ambience/grince.ogg
sound/lastunic/ambience/mg20.ogg
sound/lastunic/ambience/mg_3.ogg
sound/lastunic/ambience/mg_6.ogg
sound/lastunic/ambience/rocketfire1.ogg
sound/lastunic/ambience/ventf.ogg
sound/lastunic/ambience/venth.ogg
sound/lastunic/ambience/wind1.ogg
sound/lastunic/zombie/claw_miss1.ogg
sound/lastunic/zombie/claw_miss2.ogg
sound/lastunic/zombie/claw_strike1.ogg
sound/lastunic/zombie/claw_strike2.ogg
sound/lastunic/zombie/claw_strike3.ogg
sound/sa13/ambience/alarmeu1.ogg
sound/sa13/ambience/comp3.ogg
sound/sa13/ambience/gegene.ogg
sound/sa13/ambience/goutte1.ogg
sound/sa13/ambience/machines3.ogg
sound/sa13/ambience/underwater.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scmod/lastunic/dialogs/lastunic_6/mesa.ogg
sound/weapons/de_deploy.wav
sound/weapons/egon_draw.wav
sound/weapons/foley_grabmag.wav
sound/weapons/lastunic/357/357_fire2.wav
sound/weapons/lastunic/357/357_shot1.wav
sound/weapons/lastunic/ak47/ak47-1.wav
sound/weapons/lastunic/awp/awp1.wav
sound/weapons/lastunic/deagle/deagle-1.wav
sound/weapons/lastunic/elite/elite-1.wav
sound/weapons/lastunic/shotgun/shotgun_dbl_fire7.wav
sound/weapons/lastunic/shotgun/shotgun_fire6.wav
sound/weapons/lastunic/uzi/shoot1.wav
sound/weapons/m82_cock.wav
sound/weapons/m82_magin.wav
sound/weapons/m82_magout.wav
sound/weapons/mp5k_boltback.wav
sound/weapons/mp5k_boltslap.wav
sound/weapons/mp5k_magin.wav
sound/weapons/mp5k_magout.wav
sound/weapons/mp5k_slamtogether.wav
sound/weapons/mp5k_toakimbo.wav
sound/weapons/stinger_reload.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
