// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

CrazyD.wad
F40.wad
LifesEnd.wad
zeditor.wad
models/LifesEnd/alt_gordon.mdl
models/LifesEnd/alt_gordont.mdl
models/LifesEnd/alt_scientist.mdl
models/LifesEnd/alt_scientist01.mdl
models/LifesEnd/alt_scientist02.mdl
models/LifesEnd/alt_scientist03.mdl
models/LifesEnd/alt_scientist04.mdl
models/LifesEnd/alt_scientist05.mdl
models/LifesEnd/alt_scientist06.mdl
models/LifesEnd/alt_scientist07.mdl
models/LifesEnd/alt_scientistT.mdl
models/LifesEnd/CmdSeq.wc
models/LifesEnd/GameCfg.wc
models/LifesEnd/gordon.mdl
models/LifesEnd/hotdog.mdl
models/LifesEnd/hotdogT.mdl
models/LifesEnd/hurt_scientist.mdl
models/LifesEnd/hurt_scientist01.mdl
models/LifesEnd/hurt_scientist02.mdl
models/LifesEnd/hurt_scientist03.mdl
models/LifesEnd/hurt_scientist04.mdl
models/LifesEnd/hurt_scientist05.mdl
models/LifesEnd/hurt_scientist06.mdl
models/LifesEnd/hurt_scientist07.mdl
models/LifesEnd/hurt_scientistT.mdl
models/LifesEnd/kingpin.mdl
models/LifesEnd/krunchi-coffee.mdl
models/LifesEnd/office-coffee.mdl
models/LifesEnd/office-coffeeT.mdl
models/LifesEnd/player.mdl
models/LifesEnd/playert.mdl
models/LifesEnd/qmeal.mdl
models/LifesEnd/soda-pop.mdl
models/LifesEnd/soda-popT.mdl
gfx/env/vlcnobk.tga
gfx/env/vlcnodn.tga
gfx/env/vlcnoft.tga
gfx/env/vlcnolf.tga
gfx/env/vlcnort.tga
gfx/env/vlcnoup.tga
sound/LifesEnd/FT_FX1.wav
sound/LifesEnd/FTsurface.wav
sound/LifesEnd/mrfreeman.wav
sound/LifesEnd/sentences.txt
sound/LifesEnd/ambience/fluorescent.wav
sound/LifesEnd/ambience/FT_tr_exit.wav
sound/LifesEnd/ambience/ft_tramleave.wav
sound/LifesEnd/ambience/op4_11.wav
sound/LifesEnd/ambience/zelda.wav
sound/LifesEnd/barney/ba_duty.wav
sound/LifesEnd/barney/ba_pissme.wav
sound/LifesEnd/barney/c1a0_ba_headdown.wav
sound/LifesEnd/barney/c1a0_ba_hevno.wav
sound/LifesEnd/barney/ft_gearup.wav
sound/LifesEnd/barney/FTshit.wav
sound/LifesEnd/barney/heybuddy.wav
sound/LifesEnd/barney/howdy.wav
sound/LifesEnd/barney/icanhear.wav
sound/LifesEnd/barney/mrfreeman.wav
sound/LifesEnd/barney/openfire.wav
sound/LifesEnd/bitsnbobs/cascade.wav
sound/LifesEnd/bitsnbobs/ft_resi_corridor.wav
sound/LifesEnd/bitsnbobs/se_gongstart.wav
sound/LifesEnd/buttons/bell1.wav
sound/LifesEnd/plats/ttrain2.wav
sound/LifesEnd/plats/ttrain7.wav
sound/LifesEnd/scientist/ahfreeman.wav
sound/LifesEnd/scientist/c1a0_sci_dis16a.wav
sound/LifesEnd/scientist/c1a4_sci_rocket.wav
sound/LifesEnd/scientist/d_sci_gm.wav
sound/LifesEnd/scientist/excuse.wav
sound/LifesEnd/scientist/exellentteam.wav
sound/LifesEnd/scientist/freeman.wav
sound/LifesEnd/scientist/freemanalive.wav
sound/LifesEnd/scientist/ft_alive.wav
sound/LifesEnd/scientist/FT_card.wav
sound/LifesEnd/scientist/FT_scidis1.wav
sound/LifesEnd/scientist/ft_scisave.wav
sound/LifesEnd/scientist/FT_worry.wav
sound/LifesEnd/scientist/hellofreeman.wav
sound/LifesEnd/scientist/inmesstoo.wav
sound/LifesEnd/scientist/leadtheway.wav
sound/LifesEnd/scientist/letsgo.wav
sound/LifesEnd/scientist/of1a6_sc01.wav
sound/LifesEnd/scientist/okgetout.wav
sound/LifesEnd/scientist/sc_accident2.wav
sound/LifesEnd/scientist/sc_yard_box3.wav
sound/LifesEnd/scientist/sci_busy.wav
sound/LifesEnd/scientist/stop3.wav
sound/LifesEnd/vox/levels.wav