// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

CrazyD.wad
F40.wad
LifesEnd.wad
zeditor.wad
models/LifesEnd/alt_gordon.mdl
models/LifesEnd/alt_gordont.mdl
models/LifesEnd/alt_scientist.mdl
models/LifesEnd/alt_scientist01.mdl
models/LifesEnd/alt_scientist02.mdl
models/LifesEnd/alt_scientist03.mdl
models/LifesEnd/alt_scientist04.mdl
models/LifesEnd/alt_scientist05.mdl
models/LifesEnd/alt_scientist06.mdl
models/LifesEnd/alt_scientist07.mdl
models/LifesEnd/alt_scientistT.mdl
models/LifesEnd/CmdSeq.wc
models/LifesEnd/GameCfg.wc
models/LifesEnd/gordon.mdl
models/LifesEnd/hotdog.mdl
models/LifesEnd/hotdogT.mdl
models/LifesEnd/hurt_scientist.mdl
models/LifesEnd/hurt_scientist01.mdl
models/LifesEnd/hurt_scientist02.mdl
models/LifesEnd/hurt_scientist03.mdl
models/LifesEnd/hurt_scientist04.mdl
models/LifesEnd/hurt_scientist05.mdl
models/LifesEnd/hurt_scientist06.mdl
models/LifesEnd/hurt_scientist07.mdl
models/LifesEnd/hurt_scientistT.mdl
models/LifesEnd/kingpin.mdl
models/LifesEnd/krunchi-coffee.mdl
models/LifesEnd/office-coffee.mdl
models/LifesEnd/office-coffeeT.mdl
models/LifesEnd/player.mdl
models/LifesEnd/playert.mdl
models/LifesEnd/qmeal.mdl
models/LifesEnd/soda-pop.mdl
models/LifesEnd/soda-popT.mdl
gfx/env/vlcnobk.tga
gfx/env/vlcnodn.tga
gfx/env/vlcnoft.tga
gfx/env/vlcnolf.tga
gfx/env/vlcnort.tga
gfx/env/vlcnoup.tga
sound/LifesEnd/FT_FX1.wav
sound/LifesEnd/FTsurface.wav
sound/LifesEnd/mrfreeman.wav
sound/LifesEnd/sentences.txt
sound/LifesEnd/ambience/fluorescent.wav
sound/LifesEnd/ambience/FT_tr_exit.wav
sound/LifesEnd/ambience/ft_tramleave.wav
sound/LifesEnd/ambience/op4_11.wav
sound/LifesEnd/ambience/zelda.wav
sound/LifesEnd/barney/ba_duty.wav
sound/LifesEnd/barney/ba_pissme.wav
sound/LifesEnd/barney/c1a0_ba_headdown.wav
sound/LifesEnd/barney/c1a0_ba_hevno.wav
sound/LifesEnd/barney/ft_gearup.wav
sound/LifesEnd/barney/FTshit.wav
sound/LifesEnd/barney/heybuddy.wav
sound/LifesEnd/barney/howdy.wav
sound/LifesEnd/barney/icanhear.wav
sound/LifesEnd/barney/mrfreeman.wav
sound/LifesEnd/barney/openfire.wav
sound/LifesEnd/bitsnbobs/cascade.wav
sound/LifesEnd/bitsnbobs/ft_resi_corridor.wav
sound/LifesEnd/bitsnbobs/se_gongstart.wav
sound/LifesEnd/buttons/bell1.wav
sound/LifesEnd/plats/ttrain2.wav
sound/LifesEnd/plats/ttrain7.wav
sound/LifesEnd/scientist/ahfreeman.wav
sound/LifesEnd/scientist/c1a0_sci_dis16a.wav
sound/LifesEnd/scientist/c1a4_sci_rocket.wav
sound/LifesEnd/scientist/d_sci_gm.wav
sound/LifesEnd/scientist/excuse.wav
sound/LifesEnd/scientist/exellentteam.wav
sound/LifesEnd/scientist/freeman.wav
sound/LifesEnd/scientist/freemanalive.wav
sound/LifesEnd/scientist/ft_alive.wav
sound/LifesEnd/scientist/FT_card.wav
sound/LifesEnd/scientist/FT_scidis1.wav
sound/LifesEnd/scientist/ft_scisave.wav
sound/LifesEnd/scientist/FT_worry.wav
sound/LifesEnd/scientist/hellofreeman.wav
sound/LifesEnd/scientist/inmesstoo.wav
sound/LifesEnd/scientist/leadtheway.wav
sound/LifesEnd/scientist/letsgo.wav
sound/LifesEnd/scientist/of1a6_sc01.wav
sound/LifesEnd/scientist/okgetout.wav
sound/LifesEnd/scientist/sc_accident2.wav
sound/LifesEnd/scientist/sc_yard_box3.wav
sound/LifesEnd/scientist/sci_busy.wav
sound/LifesEnd/scientist/stop3.wav
sound/LifesEnd/vox/levels.wav

//opfor + svencoop classic weapons plugins
models/valve/sd/p_2uzis.mdl
models/valve/sd/p_2uzis_gold.mdl
models/valve/sd/p_bgrap.mdl
models/valve/sd/p_desert_eagle.mdl
models/valve/sd/p_displacer.mdl
models/valve/sd/p_glock.mdl
models/valve/sd/p_m16.mdl
models/valve/sd/p_m40a1.mdl
models/valve/sd/p_minigunidle.mdl
models/valve/sd/p_minigunspin.mdl
models/valve/sd/p_pipe_wrench.mdl
models/valve/sd/p_saw.mdl
models/valve/sd/p_shock.mdl
models/valve/sd/p_spore_launcher.mdl
models/valve/sd/p_uzi.mdl
models/valve/sd/p_uzi_gold.mdl

models/valve/sd/v_357.mdl

models/valve/sd/v_bgrap.mdl
models/valve/sd/v_desert_eagle.mdl
models/valve/sd/v_displacer.mdl
models/valve/sd/v_m16a2.mdl
models/valve/sd/v_m40a1.mdl
models/valve/sd/v_minigun.mdl
models/valve/sd/v_pipe_wrench.mdl
models/valve/sd/v_saw.mdl
models/valve/sd/v_shock.mdl
models/valve/sd/v_spore_launcher.mdl
models/valve/sd/v_uzi.mdl

models/valve/sd/w_2uzis.mdl
models/valve/sd/w_2uzis_gold.mdl
models/valve/sd/w_bgrap.mdl
models/valve/sd/w_desert_eagle.mdl
models/valve/sd/w_displacer.mdl
models/valve/sd/w_m16.mdl
models/valve/sd/w_m40a1.mdl
models/valve/sd/w_m40a1clip.mdl
models/valve/sd/w_minigun.mdl
models/valve/sd/w_pipe_wrench.mdl
models/valve/sd/w_saw.mdl
models/valve/sd/w_saw_clip.mdl
models/valve/sd/w_shock.mdl
models/valve/sd/w_shock_rifle.mdl
models/valve/sd/w_spore_launcher.mdl
models/valve/sd/w_uzi.mdl
models/valve/sd/w_uzi_clip.mdl
models/valve/sd/w_uzi_gold.mdl

models/valve/sd/saw_shell.mdl
models/valve/sd/shell.mdl

sprites/hl_weapons/weapon_hlpython.txt
sprites/hl_weapons/weapon_ofeagle.txt
sprites/hl_weapons/weapon_ofm249.txt
sprites/hl_weapons/weapon_ofshockrifle.txt
sprites/hl_weapons/weapon_ofsniperrifle.txt

sound/hlclassic/weapons/desert_eagle_reload.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav