// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

sprites/opfor/weapon_knife.spr
sprites/opfor/weapon_knife.txt
gfx/env/cliff2bk.bmp
gfx/env/cliff2bk.tga
gfx/env/cliff2dn.bmp
gfx/env/cliff2dn.tga
gfx/env/cliff2ft.bmp
gfx/env/cliff2ft.tga
gfx/env/cliff2lf.bmp
gfx/env/cliff2lf.tga
gfx/env/cliff2rt.bmp
gfx/env/cliff2rt.tga
gfx/env/cliff2up.bmp
gfx/env/cliff2up.tga
gfx/env/hackbk.bmp
gfx/env/hackbk.tga
gfx/env/hackdn.bmp
gfx/env/hackdn.tga
gfx/env/hackft.bmp
gfx/env/hackft.tga
gfx/env/hacklf.bmp
gfx/env/hacklf.tga
gfx/env/hackrt.bmp
gfx/env/hackrt.tga
gfx/env/hackup.bmp
gfx/env/hackup.tga
gfx/env/sky_blu_bk.bmp
gfx/env/sky_blu_bk.tga
gfx/env/sky_blu_dn.bmp
gfx/env/sky_blu_dn.tga
gfx/env/sky_blu_ft.bmp
gfx/env/sky_blu_ft.tga
gfx/env/sky_blu_lf.bmp
gfx/env/sky_blu_lf.tga
gfx/env/sky_blu_rt.bmp
gfx/env/sky_blu_rt.tga
gfx/env/sky_blu_up.bmp
gfx/env/sky_blu_up.tga