// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

blackops.wad
gfx/env/desert_nitebk.tga
gfx/env/desert_nitedn.tga
gfx/env/desert_niteft.tga
gfx/env/desert_nitelf.tga
gfx/env/desert_nitert.tga
gfx/env/desert_niteup.tga
gfx/env/metro_nitebk.tga
gfx/env/metro_nitedn.tga
gfx/env/metro_niteft.tga
gfx/env/metro_nitelf.tga
gfx/env/metro_nitert.tga
gfx/env/metro_niteup.tga
maps/ops_club.bsp
maps/ops_ctown.bsp
maps/ops_ep.bsp
maps/ops_escape.bsp
maps/ops_hq.bsp
maps/ops_industry.bsp
maps/ops_intro.bsp
maps/ops_jail.bsp
maps/ops_sewer.bsp
maps/ops_street.bsp
maps/ops_subway.bsp
maps/ops_wareh.bsp
models/blackops/barney.mdl
models/blackops/bigbluetruck.mdl
models/blackops/bullsquid.mdl
models/blackops/couch1.mdl
models/blackops/couch3.mdl
models/blackops/couch4.mdl
models/blackops/crossbow_bolt.mdl
models/blackops/gman.mdl
models/blackops/grenade.mdl
models/blackops/hassassin.mdl
models/blackops/hgrunt.mdl
models/blackops/houndeye.mdl
models/blackops/islave.mdl
models/blackops/massn.mdl
models/blackops/misc/omegared.mdl
models/blackops/misc/project.mdl
models/blackops/original/p_357.mdl
models/blackops/original/p_9mmar.mdl
models/blackops/original/p_crossbow.mdl
models/blackops/original/p_crowbar.mdl
models/blackops/original/p_grenade.mdl
models/blackops/original/p_rpg.mdl
models/blackops/original/p_shotgun.mdl
models/blackops/original/v_357.mdl
models/blackops/original/v_9mmar.mdl
models/blackops/original/v_9mmhandgun.mdl
models/blackops/original/v_crossbow.mdl
models/blackops/original/v_crowbar.mdl
models/blackops/original/v_grenade.mdl
models/blackops/original/v_medkit.mdl
models/blackops/original/v_rpg.mdl
models/blackops/original/v_shotgun.mdl
models/blackops/original/w_357.mdl
models/blackops/original/w_357ammo.mdl
models/blackops/original/w_357ammobox.mdl
models/blackops/original/w_9mmar.mdl
models/blackops/original/w_9mmarclip.mdl
models/blackops/original/w_9mmhandgun.mdl
models/blackops/original/w_argrenade.mdl
models/blackops/original/w_battery.mdl
models/blackops/original/w_crossbow.mdl
models/blackops/original/w_crossbow_clip.mdl
models/blackops/original/w_crowbar.mdl
models/blackops/original/w_grenade.mdl
models/blackops/original/w_pipe_wrench.mdl
models/blackops/original/w_rpg.mdl
models/blackops/original/w_rpgammo.mdl
models/blackops/original/w_shotbox.mdl
models/blackops/original/w_shotgun.mdl
models/blackops/original/w_suit.mdl
models/blackops/p_357.mdl
models/blackops/p_9mmar.mdl
models/blackops/p_crossbow.mdl
models/blackops/p_crowbar.mdl
models/blackops/p_grenade.mdl
models/blackops/p_m16.mdl
models/blackops/p_medkit.mdl
models/blackops/p_rpg.mdl
models/blackops/p_shotgun.mdl
models/blackops/rpgrocket.mdl
models/blackops/rustcar3.mdl
models/blackops/sat_globe.mdl
models/blackops/scientist.mdl
models/blackops/seat1.mdl
models/blackops/shell.mdl
models/blackops/shotgunshell.mdl
models/blackops/tablelamp.mdl
models/blackops/tool_box.mdl
models/blackops/v_357.mdl
models/blackops/v_9mmar.mdl
models/blackops/v_9mmhandgun.mdl
models/blackops/v_crossbow.mdl
models/blackops/v_crowbar.mdl
models/blackops/v_grenade.mdl
models/blackops/v_m16a2.mdl
models/blackops/v_medkit.mdl
models/blackops/v_rpg.mdl
models/blackops/v_shotgun.mdl
models/blackops/w_357.mdl
models/blackops/w_357ammo.mdl
models/blackops/w_357ammobox.mdl
models/blackops/w_9mmar.mdl
models/blackops/w_9mmarclip.mdl
models/blackops/w_9mmhandgun.mdl
models/blackops/w_argrenade.mdl
models/blackops/w_battery.mdl
models/blackops/w_crossbow.mdl
models/blackops/w_crossbow_clip.mdl
models/blackops/w_crowbar.mdl
models/blackops/w_grenade.mdl
models/blackops/w_m16.mdl
models/blackops/w_medkit.mdl
models/blackops/w_pipe_wrench.mdl
models/blackops/w_pmedkit.mdl
models/blackops/w_rpg.mdl
models/blackops/w_rpgammo.mdl
models/blackops/w_shotbox.mdl
models/blackops/w_shotgun.mdl
models/blackops/w_suit.mdl
models/blackops/zombie.mdl
models/player/massn_black/massn_black.bmp
models/player/massn_black/massn_black.mdl
models/player/massn_camo/massn_camo.bmp
models/player/massn_camo/massn_camo.mdl
models/player/massn_grey/massn_grey.bmp
models/player/massn_grey/massn_grey.mdl
models/player/massn_nvg/massn_nvg.bmp
models/player/massn_nvg/massn_nvg.mdl
models/player/splintercell/splintercell.bmp
models/player/splintercell/splintercell.mdl
models/player/splintercell_red/splintercell_red.bmp
models/player/splintercell_red/splintercell_red.mdl
sound/blackops/ambience/axisscore.wav
sound/blackops/ambience/burn_small.wav
sound/blackops/ambience/busyfon.wav
sound/blackops/ambience/buttons.wav
sound/blackops/ambience/car_alarm.wav
sound/blackops/ambience/clock.wav
sound/blackops/ambience/coin.wav
sound/blackops/ambience/com_use.wav
sound/blackops/ambience/d-tone.wav
sound/blackops/ambience/deadend.wav
sound/blackops/ambience/dr_punch1.wav
sound/blackops/ambience/dr_punch2.wav
sound/blackops/ambience/flicker.wav
sound/blackops/ambience/fluorescent.wav
sound/blackops/ambience/forklift.wav
sound/blackops/ambience/horn.wav
sound/blackops/ambience/keycard.wav
sound/blackops/ambience/keypickup.wav
sound/blackops/ambience/lift_run.wav
sound/blackops/ambience/lift_start.wav
sound/blackops/ambience/lift_stop.wav
sound/blackops/ambience/mtl_break.wav
sound/blackops/ambience/night2.wav
sound/blackops/ambience/notegrab.wav
sound/blackops/ambience/nuke_explode.wav
sound/blackops/ambience/nuke_ticking.wav
sound/blackops/ambience/passby.wav
sound/blackops/ambience/phone1.wav
sound/blackops/ambience/phone2.wav
sound/blackops/ambience/phone_msg.wav
sound/blackops/ambience/ring.wav
sound/blackops/ambience/shot.wav
sound/blackops/ambience/singledrip.wav
sound/blackops/ambience/squeakyflr1.wav
sound/blackops/ambience/squeakyflr2.wav
sound/blackops/ambience/squeakywin.wav
sound/blackops/ambience/thunder.wav
sound/blackops/ambience/thunder2.wav
sound/blackops/ambience/thunder3.wav
sound/blackops/ambience/tr_passby.wav
sound/blackops/ambience/wall_break.wav
sound/blackops/ambience/wdimpact.wav
sound/blackops/ambience/wdimpact2.wav
sound/blackops/ambience/wdimpact3.wav
sound/blackops/ambience/zippo.wav
sound/blackops/ambience/zippo_close.wav
sound/blackops/buttons/button2.wav
sound/blackops/buttons/button7.wav
sound/blackops/buttons/button8.wav
sound/blackops/common/wpn_hudoff.wav
sound/blackops/common/wpn_hudon.wav
sound/blackops/common/wpn_moveselect.wav
sound/blackops/common/wpn_select.wav
sound/blackops/doors/doormove1.wav
sound/blackops/doors/doormove10.wav
sound/blackops/doors/doorstop1.wav
sound/blackops/doors/elev_dr1.wav
sound/blackops/hgrunt/gr_mgun1.wav
sound/blackops/hgrunt/gr_mgun2.wav
sound/blackops/items/gunpickup2.wav
sound/blackops/items/vest_pickup.wav
sound/blackops/misc/checkpoint_close.wav
sound/blackops/misc/checkpoint_pulse.wav
sound/blackops/misc/checkpoint_survival.wav
sound/blackops/ops/cleanup.wav
sound/blackops/ops_materials.txt
sound/blackops/player/pl_dirt1.wav
sound/blackops/player/pl_dirt2.wav
sound/blackops/player/pl_dirt3.wav
sound/blackops/player/pl_dirt4.wav
sound/blackops/player/pl_grate1.wav
sound/blackops/player/pl_grate2.wav
sound/blackops/player/pl_grate3.wav
sound/blackops/player/pl_grate4.wav
sound/blackops/player/pl_metal1.wav
sound/blackops/player/pl_metal2.wav
sound/blackops/player/pl_metal3.wav
sound/blackops/player/pl_metal4.wav
sound/blackops/player/pl_slosh1.wav
sound/blackops/player/pl_slosh2.wav
sound/blackops/player/pl_slosh3.wav
sound/blackops/player/pl_slosh4.wav
sound/blackops/player/pl_step1.wav
sound/blackops/player/pl_step2.wav
sound/blackops/player/pl_step3.wav
sound/blackops/player/pl_step4.wav
sound/blackops/player/pl_tile1.wav
sound/blackops/player/pl_tile2.wav
sound/blackops/player/pl_tile3.wav
sound/blackops/player/pl_tile4.wav
sound/blackops/player/pl_tile5.wav
sound/blackops/weapons/dbarrel1.wav
sound/blackops/weapons/hks1.wav
sound/blackops/weapons/hks2.wav
sound/blackops/weapons/hks3.wav
sound/blackops/weapons/pl_gun3.wav
sound/blackops/weapons/sbarrel1.wav
sound/blackops/weapons/scock1.wav
sound/weapons/629_shells_land.wav
sound/weapons/g3_boltback.wav
sound/weapons/g3_boltforward.wav
sound/weapons/g3_magin.wav
sound/weapons/g3_magout.wav
sound/weapons/hks_clic1.wav
sound/weapons/m4a1_boltpull.wav
sound/weapons/m4a1_clipin.wav
sound/weapons/m4a1_clipout.wav
sound/weapons/m4a1_deploy.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sprites/blackops/csi.spr
sprites/blackops/dv_a.spr
sprites/blackops/dv_b.spr
sprites/blackops/dv_blck.spr
sprites/blackops/dv_c.spr
sprites/blackops/dv_cellblcka.spr
sprites/blackops/dv_noweshp_a.spr
sprites/blackops/dv_noweshp_bl.spr
sprites/blackops/level_change_ops.spr
sprites/blackops/ops_omega.spr
sprites/blackops/ops_omegab.spr
sprites/blackops/prk_levl.spr
sprites/blackops/rain.spr
sprites/blackops/usable.spr
