portalhouse.wad

gfx/env/c1a3bk.tga
gfx/env/c1a3dn.tga
gfx/env/c1a3ft.tga
gfx/env/c1a3lf.tga
gfx/env/c1a3rt.tga
gfx/env/c1a3up.tga
gfx/env/dawnbk.tga
gfx/env/dawndn.tga
gfx/env/dawnft.tga
gfx/env/dawnlf.tga
gfx/env/dawnrt.tga
gfx/env/dawnup.tga
gfx/env/xen_skybluebk.png
gfx/env/xen_skybluebk.tga
gfx/env/xen_skybluedn.png
gfx/env/xen_skybluedn.tga
gfx/env/xen_skyblueft.png
gfx/env/xen_skyblueft.tga
gfx/env/xen_skybluelf.png
gfx/env/xen_skybluelf.tga
gfx/env/xen_skybluert.png
gfx/env/xen_skybluert.tga
gfx/env/xen_skyblueup.png
gfx/env/xen_skyblueup.tga

maps/portal_house_A3.cfg
maps/portal_house_A3_climax.cfg
maps/portal_house_A3_climax_motd.txt
maps/portal_house_A3_motd.txt

models/portal_house/blmsa_skin/GameCfg.wc
models/portal_house/blmsa_skin/v_9mmar.mdl
models/portal_house/blmsa_skin/v_9mmar_hl.mdl
models/portal_house/blmsa_skin/v_357.mdl
models/portal_house/blmsa_skin/v_crossbow.mdl
models/portal_house/blmsa_skin/v_egon.mdl
models/portal_house/blmsa_skin/v_gauss.mdl
models/portal_house/blmsa_skin/v_grenade.mdl
models/portal_house/blmsa_skin/v_m16a.mdl
models/portal_house/blmsa_skin/v_m16a2.mdl
models/portal_house/blmsa_skin/v_pipe_wrench.mdl
models/portal_house/blmsa_skin/v_plasmagun.mdl
models/portal_house/blmsa_skin/v_rpg.mdl
models/portal_house/blmsa_skin/v_shotgun.mdl
models/portal_house/blmsa_skin/v_shotgun_twocannon.mdl
models/portal_house/blmsa_skin/v_spore_launcher.mdl
models/portal_house/blmsa_skin/v_squeak.mdl
models/portal_house/blmsa_skin/v_toad.mdl
models/portal_house/blmsa_skin/v_uzi.mdl
models/portal_house/bshift_skin/GameCfg.wc
models/portal_house/bshift_skin/v_9mmar.mdl
models/portal_house/bshift_skin/v_357.mdl
models/portal_house/bshift_skin/v_768mmvulcan.mdl
models/portal_house/bshift_skin/v_crossbow.mdl
models/portal_house/bshift_skin/v_crowbar.mdl
models/portal_house/bshift_skin/v_desert_eagle.mdl
models/portal_house/bshift_skin/v_grenade.mdl
models/portal_house/bshift_skin/v_medkit.mdl
models/portal_house/bshift_skin/v_minigun.mdl
models/portal_house/bshift_skin/v_p904.mdl
models/portal_house/bshift_skin/v_satchel.mdl
models/portal_house/bshift_skin/v_satchel_radio.mdl
models/portal_house/bshift_skin/v_shotgun.mdl
models/portal_house/bshift_skin/v_shotgun2.mdl
models/portal_house/bshift_skin/v_tripmine.mdl
models/portal_house/bshift_skin/v_uzi.mdl
models/portal_house/opfor_skin/GameCfg.wc
models/portal_house/opfor_skin/v_9mmar.mdl
models/portal_house/opfor_skin/v_9mmhandgun.mdl
models/portal_house/opfor_skin/v_768mmvulcan.mdl
models/portal_house/opfor_skin/v_crowbar.mdl
models/portal_house/opfor_skin/v_desert_eagle.mdl
models/portal_house/opfor_skin/v_grenade.mdl
models/portal_house/opfor_skin/v_m16a2.mdl
models/portal_house/opfor_skin/v_m40a1.mdl
models/portal_house/opfor_skin/v_rpg.mdl
models/portal_house/opfor_skin/v_saw.mdl
models/portal_house/opfor_skin/v_shotgun.mdl
models/portal_house/opfor_skin/v_spore_launcher.mdl
models/portal_house/opfor_skin/v_squeak.mdl
models/portal_house/opfor_skin/v_uzi.mdl
models/portal_house/sforce_skin/GameCfg.wc
models/portal_house/sforce_skin/v_9mmberetta.mdl
models/portal_house/sforce_skin/v_9mm41a.mdl
models/portal_house/sforce_skin/v_grenade.mdl
models/portal_house/sforce_skin/v_pipe_wrench.mdl
models/portal_house/sforce_skin/v_plasmagun.mdl
models/portal_house/sforce_skin/v_rpg.mdl
models/portal_house/sforce_skin/v_saw.mdl
models/portal_house/sforce_skin/v_sawdoff.mdl
models/portal_house/sforce_skin/v_toad.mdl
models/portal_house/sforce_skin/v_uzi.mdl
models/portal_house/5ton.mdl
models/portal_house/adrian.mdl
models/portal_house/archer.mdl
models/portal_house/baby_panter.mdl
models/portal_house/bagger.mdl
models/portal_house/bateria.mdl
models/portal_house/breather.mdl
models/portal_house/c_core.mdl
models/portal_house/dead_barney.mdl
models/portal_house/DecayCristals.mdl
models/portal_house/Eduard.mdl
models/portal_house/floater.mdl
models/portal_house/flyer.mdl
models/portal_house/flyer_gibs.mdl
models/portal_house/forja.mdl
models/portal_house/friendly.mdl
models/portal_house/GameCfg.wc
models/portal_house/giant.mdl
models/portal_house/gibs_mineral_med.mdl
models/portal_house/gonome.mdl
models/portal_house/gorg.mdl
models/portal_house/gus.mdl
models/portal_house/hassassin.mdl
models/portal_house/hev_barney.mdl
models/portal_house/hev_barniel.mdl
models/portal_house/hev_bgman.mdl
models/portal_house/hev_sci.mdl
models/portal_house/hev_spforce.mdl
models/portal_house/hev_spfsci.mdl
models/portal_house/hw_spforce.mdl
models/portal_house/jbarney.mdl
models/portal_house/jet.mdl
models/portal_house/kate.mdl
models/portal_house/loadergib.mdl
models/portal_house/mag_lamp.mdl
models/portal_house/monarcus.mdl
models/portal_house/ngrunt.mdl
models/portal_house/obj_chair.mdl
models/portal_house/p_9mmar.mdl
models/portal_house/p_9mmberetta.mdl
models/portal_house/p_768mmvulcan.mdl
models/portal_house/p_knife.mdl
models/portal_house/p_m16a2.mdl
models/portal_house/p_p904.mdl
models/portal_house/p_plasmagun.mdl
models/portal_house/p_sawedoff.mdl
models/portal_house/p_shotgun.mdl
models/portal_house/panther.mdl
models/portal_house/pit_worm_up.mdl
models/portal_house/probe.mdl
models/portal_house/probeboss.mdl
models/portal_house/race.mdl
models/portal_house/reactor.mdl
models/portal_house/robolaser.mdl
models/portal_house/robolaser_largegibs.mdl
models/portal_house/rollo_cables.mdl
models/portal_house/scientist_rosenberg.mdl
models/portal_house/sentry.mdl
models/portal_house/sky_build.mdl
models/portal_house/sky_clouds.mdl
models/portal_house/sky_xen.mdl
models/portal_house/spforce.mdl
models/portal_house/sphere.mdl
models/portal_house/sslave.mdl
models/portal_house/terror.mdl
models/portal_house/toad_nest.mdl
models/portal_house/toadgibs.mdl
models/portal_house/train.mdl
models/portal_house/triturador.mdl
models/portal_house/truck_research.mdl
models/portal_house/v_9mmar.mdl
models/portal_house/v_9mmberetta.mdl
models/portal_house/v_9mmm41a.mdl
models/portal_house/v_768mmvulcan.mdl
models/portal_house/v_c4.mdl
models/portal_house/v_c4package.mdl
models/portal_house/v_Hgun.mdl
models/portal_house/v_knife.mdl
models/portal_house/v_p904.mdl
models/portal_house/v_plasmagun.mdl
models/portal_house/v_sawedoff.mdl
models/portal_house/v_shotgun.mdl
models/portal_house/valemoth.mdl
models/portal_house/vehicle02.mdl
models/portal_house/w_9mmar.mdl
models/portal_house/w_9mmberetta.mdl
models/portal_house/w_768ammo.mdl
models/portal_house/w_battery_supercharge.mdl
models/portal_house/w_bsuit.mdl
models/portal_house/w_helm.mdl
models/portal_house/w_knife.mdl
models/portal_house/w_p904.mdl
models/portal_house/w_plasmaclip.mdl
models/portal_house/w_plasmagun.mdl
models/portal_house/w_rpgnuclearclip.mdl
models/portal_house/w_sawedoff.mdl
models/portal_house/w_shotgun.mdl
models/portal_house/w_spfsuit.mdl
models/portal_house/w_sqknest.mdl
models/portal_house/w_suit.mdl
models/portal_house/w_toad.mdl
models/portal_house/w_tsuit.mdl
models/portal_house/w_vulcan.mdl
models/portal_house/w_xenmedkit.mdl
models/portal_house/xenocrab.mdl
models/portal_house/xenogrunt.mdl
models/portal_house/Xonxt.mdl
models/portal_house/xtbssilverground.mdl
models/portal_house/zgrunt.mdl
models/portal_house/zhwgrunt.mdl
models/portal_house/zmassn.mdl

scripts/maps/portal_house/monsters/monster_female_jumper.as
scripts/maps/portal_house/monsters/monster_race.as
scripts/maps/portal_house/p_entity.as
scripts/maps/portal_house/ph_shot.as
scripts/maps/portal_house/portal_house.as
scripts/maps/portal_house/portal_house_register.as
scripts/maps/portal_house/weapon_9mmm41a.as
scripts/maps/portal_house/weapon_beretta.as
scripts/maps/portal_house/weapon_dl44blaster.as
scripts/maps/portal_house/weapon_e11blaster.as
scripts/maps/portal_house/weapon_knife.as
scripts/maps/portal_house/weapon_mp5hl.as
scripts/maps/portal_house/weapon_ofshockrifle.as
scripts/maps/portal_house/weapon_p904.as
scripts/maps/portal_house/weapon_plasmagun.as
scripts/maps/portal_house/weapon_sawedoff.as
scripts/maps/portal_house/weapon_shotgunhl.as
scripts/maps/portal_house/weapon_t21blaster.as
scripts/maps/portal_house/weapon_vulcan.as

sound/portal_house/archer/arch_alert1.wav
sound/portal_house/archer/arch_alert2.wav
sound/portal_house/archer/arch_attack1.wav
sound/portal_house/archer/arch_attack2.wav
sound/portal_house/archer/arch_bite1.wav
sound/portal_house/archer/arch_bite2.wav
sound/portal_house/archer/arch_die1.wav
sound/portal_house/archer/arch_die2.wav
sound/portal_house/archer/arch_die3.wav
sound/portal_house/archer/arch_idle1.wav
sound/portal_house/archer/arch_idle2.wav
sound/portal_house/archer/arch_idle3.wav
sound/portal_house/archer/arch_pain1.wav
sound/portal_house/archer/arch_pain2.wav
sound/portal_house/archer/arch_pain3.wav
sound/portal_house/archer/arch_pain4.wav
sound/portal_house/ba_holo/tr_holo_4jumps.wav
sound/portal_house/ba_holo/tr_holo_armor.wav
sound/portal_house/ba_holo/tr_holo_button.wav
sound/portal_house/ba_holo/tr_holo_charger.wav
sound/portal_house/ba_holo/tr_holo_commencing.wav
sound/portal_house/ba_holo/tr_holo_move.wav
sound/portal_house/ba_holo/tr_holo_usetrain.wav
sound/portal_house/baby_panther/bp_alert1.wav
sound/portal_house/baby_panther/bp_alert2.wav
sound/portal_house/baby_panther/bp_attack1.wav
sound/portal_house/baby_panther/bp_attack2.wav
sound/portal_house/baby_panther/bp_attack3.wav
sound/portal_house/baby_panther/bp_die1.wav
sound/portal_house/baby_panther/bp_die2.wav
sound/portal_house/baby_panther/bp_headbite.wav
sound/portal_house/baby_panther/bp_idle1.wav
sound/portal_house/baby_panther/bp_idle2.wav
sound/portal_house/baby_panther/bp_idle3.wav
sound/portal_house/baby_panther/bp_idle4.wav
sound/portal_house/baby_panther/bp_idle5.wav
sound/portal_house/baby_panther/bp_pain1.wav
sound/portal_house/baby_panther/bp_pain2.wav
sound/portal_house/baby_panther/bp_pain3.wav
sound/portal_house/barney/a401-c2a4_ba_alive.wav
sound/portal_house/barney/a408-ba_generic0.wav
sound/portal_house/barney/a409-ba_docprotect3.wav
sound/portal_house/barney/a412-ba_ht06_07.wav
sound/portal_house/barney/a414-ba_mad1.wav
sound/portal_house/barney/a417-ba_shot1.wav
sound/portal_house/barney/a419-ba_ht06_01.wav
sound/portal_house/barney/ba_ht01_02.wav
sound/portal_house/barney/ba_ht01_03.wav
sound/portal_house/barney/ba_ht01_05.wav
sound/portal_house/barney/ba_ht06_03.wav
sound/portal_house/barney/ba_ht06_03_alt.wav
sound/portal_house/barney/ba_ht06_04.wav
sound/portal_house/barney/ba_ht06_09.wav
sound/portal_house/barney/ba_ht06_11.wav
sound/portal_house/barney/ba_ht07_01.wav
sound/portal_house/barney/ba_ht07_02.wav
sound/portal_house/barney/ba_ht07_03.wav
sound/portal_house/barney/ba_ht07_04.wav
sound/portal_house/barney/ba_ht07_06.wav
sound/portal_house/barney/ba_ht07_07.wav
sound/portal_house/barney/ba_ht07_08.wav
sound/portal_house/barney/ba_ht07_10.wav
sound/portal_house/barney/ba_ht07_11.wav
sound/portal_house/barney/ba_ht07_13.wav
sound/portal_house/barney/ba_ht07_14.wav
sound/portal_house/barney/ba_ht07_15.wav
sound/portal_house/barney/ba_ht07_17.wav
sound/portal_house/barney/ba_needhelp1.wav
sound/portal_house/barney/ba_ok1.wav
sound/portal_house/barney/ba_overhere.wav
sound/portal_house/barney/ba_pain1.wav
sound/portal_house/barney/ba_pain2.wav
sound/portal_house/barney/ba_pain3.wav
sound/portal_house/barney/ba_pok1.wav
sound/portal_house/barney/ba_power3.wav
sound/portal_house/barney/ba_security2_range2.wav
sound/portal_house/barney/micro_ba_2zomb.wav
sound/portal_house/barney/micro_ba_ht06_03_alt.wav
sound/portal_house/barney/micro_ba_ht06_11.wav
sound/portal_house/barney/micro_ba_ht07_06.wav
sound/portal_house/barney/micro_ba_ht07_10.wav
sound/portal_house/barney/micro_ba_ht07_14.wav
sound/portal_house/barney/micro_ba_pok1.wav
sound/portal_house/barney/micro_seeya.wav
sound/portal_house/barniel/_comma.wav
sound/portal_house/barniel/357_shot1.wav
sound/portal_house/barniel/aimforhead.wav
sound/portal_house/barniel/badfeeling.wav
sound/portal_house/barniel/bequiet.wav
sound/portal_house/barniel/bn_another.wav
sound/portal_house/barniel/bn_attack1.wav
sound/portal_house/barniel/bn_attack2.wav
sound/portal_house/barniel/bn_becarefull.wav
sound/portal_house/barniel/bn_bring.wav
sound/portal_house/barniel/bn_carefull.wav
sound/portal_house/barniel/bn_close.wav
sound/portal_house/barniel/bn_die1.wav
sound/portal_house/barniel/bn_dontdothat.wav
sound/portal_house/barniel/bn_dontmake.wav
sound/portal_house/barniel/bn_endline.wav
sound/portal_house/barniel/bn_firepl.wav
sound/portal_house/barniel/bn_friends.wav
sound/portal_house/barniel/bn_gotone.wav
sound/portal_house/barniel/bn_iwish.wav
sound/portal_house/barniel/bn_onelessh.wav
sound/portal_house/barniel/bn_pain1.wav
sound/portal_house/barniel/bn_pain2.wav
sound/portal_house/barniel/bn_pain3.wav
sound/portal_house/barniel/bn_post.wav
sound/portal_house/barniel/bn_seethat.wav
sound/portal_house/barniel/bn_somuch.wav
sound/portal_house/barniel/bn_stepoff.wav
sound/portal_house/barniel/bn_tomb.wav
sound/portal_house/barniel/bn_uwish.wav
sound/portal_house/barniel/bn_whatyou.wav
sound/portal_house/barniel/diegreenthing.wav
sound/portal_house/barniel/dontagree.wav
sound/portal_house/barniel/dontknow.wav
sound/portal_house/barniel/drinktopside.wav
sound/portal_house/barniel/hearsomething.wav
sound/portal_house/barniel/hevno.wav
sound/portal_house/barniel/hi.wav
sound/portal_house/barniel/hitbad.wav
sound/portal_house/barniel/hoyes.wav
sound/portal_house/barniel/humm.wav
sound/portal_house/barniel/imhit.wav
sound/portal_house/barniel/movietv.wav
sound/portal_house/barniel/nosir.wav
sound/portal_house/barniel/notatall.wav
sound/portal_house/barniel/openfire.wav
sound/portal_house/barniel/rightway.wav
sound/portal_house/barniel/seelater.wav
sound/portal_house/barniel/seeya.wav
sound/portal_house/barniel/seeyoulater.wav
sound/portal_house/barniel/slimything.wav
sound/portal_house/barniel/somethingmoves.wav
sound/portal_house/barniel/stop1.wav
sound/portal_house/barniel/teamup1.wav
sound/portal_house/barniel/teamup2.wav
sound/portal_house/barniel/thinking.wav
sound/portal_house/barniel/waitin.wav
sound/portal_house/barniel/whatsgoingon.wav
sound/portal_house/barniel/yesbarn.wav
sound/portal_house/barniel/yessir.wav
sound/portal_house/barniel/youneedmedic.wav
sound/portal_house/bloater/bloater_die1.wav
sound/portal_house/bloater/bloater_idle1.wav
sound/portal_house/bloater/bloater_idle2.wav
sound/portal_house/bloater/bloater_idle3.wav
sound/portal_house/bloater/bloater_idle4.wav
sound/portal_house/bloater/bloater_pain1.wav
sound/portal_house/bloater/bloater_pain2.wav
sound/portal_house/bloater/bloater_pain3.wav
sound/portal_house/buttons/button1.wav
sound/portal_house/buttons/com_use.wav
sound/portal_house/buttons/GameCfg.wc
sound/portal_house/buttons/switch01.wav
sound/portal_house/drill/add11.wav
sound/portal_house/drill/firstroom01.wav
sound/portal_house/drill/intro02.wav
sound/portal_house/drill/squad01.wav
sound/portal_house/fast_zombie/breathe_loop1.wav
sound/portal_house/fast_zombie/fz_alert_close1.wav
sound/portal_house/fast_zombie/fz_alert_far1.wav
sound/portal_house/fast_zombie/fz_frenzy1.wav
sound/portal_house/fast_zombie/fz_scream1.wav
sound/portal_house/fast_zombie/gurgle_loop1.wav
sound/portal_house/fast_zombie/idle1.wav
sound/portal_house/fast_zombie/idle2.wav
sound/portal_house/fast_zombie/idle3.wav
sound/portal_house/fast_zombie/leap1.wav
sound/portal_house/fast_zombie/wake1.wav
sound/portal_house/fast_zombie/zo_alert30.wav
sound/portal_house/friendly/friendly_alert1.wav
sound/portal_house/friendly/friendly_alert2.wav
sound/portal_house/friendly/friendly_alert3.wav
sound/portal_house/friendly/friendly_attack1.wav
sound/portal_house/friendly/friendly_attack2.wav
sound/portal_house/friendly/friendly_die1.wav
sound/portal_house/friendly/friendly_idle1.wav
sound/portal_house/friendly/friendly_idle2.wav
sound/portal_house/friendly/friendly_idle3.wav
sound/portal_house/friendly/friendly_idle4.wav
sound/portal_house/friendly/friendly_pain1.wav
sound/portal_house/fvox/get_m249saw.wav
sound/portal_house/fvox/get_plasmagon.wav
sound/portal_house/gman/flash.wav
sound/portal_house/gman/GameCfg.wc
sound/portal_house/gman/gman_again.wav
sound/portal_house/gman/gman_climax_c01.wav
sound/portal_house/gman/gman_convenient.wav
sound/portal_house/gman/gman_entity-cont.wav
sound/portal_house/gman/gman_fulltalk.wav
sound/portal_house/gman/gman_getbackhere.wav
sound/portal_house/gman/gman_good-work.wav
sound/portal_house/gman/gman_great-deal.wav
sound/portal_house/gman/gman_huff.wav
sound/portal_house/gman/gman_inflexible-world.wav
sound/portal_house/gman/gman_laugh01.wav
sound/portal_house/gman/gman_men-world.wav
sound/portal_house/gman/gman_motthistime.wav
sound/portal_house/gman/gman_ohno.wav
sound/portal_house/gman/gman_oldtimes.wav
sound/portal_house/gman/gman_suit.wav
sound/portal_house/gman/gman_thatsalifornow.wav
sound/portal_house/gman/gman_gman_wake-up.wav
sound/portal_house/gman/gman_you-want.wav
sound/portal_house/gman/handdryer.wav
sound/portal_house/hassault/assault_alert1.wav
sound/portal_house/hassault/assault_alert2.wav
sound/portal_house/hassault/assault_die1.wav
sound/portal_house/hassault/assault_die2.wav
sound/portal_house/hassault/assault_die3.wav
sound/portal_house/hassault/assault_pain1.wav
sound/portal_house/hassault/assault_pain2.wav
sound/portal_house/hassault/assault_pain3.wav
sound/portal_house/hgrunt/alt_soldier04.wav
sound/portal_house/hgrunt/alt_soldier06.wav
sound/portal_house/hgrunt/alt_soldier07.wav
sound/portal_house/hgrunt/alt_soldier08.wav
sound/portal_house/hgrunt/alt_soldier09.wav
sound/portal_house/hgrunt/apache_select.wav
sound/portal_house/hgrunt/bombpl.wav
sound/portal_house/hgrunt/bootcamp0.wav
sound/portal_house/hgrunt/c2a3_hg_laugh.wav
sound/portal_house/hgrunt/colette_use0.wav
sound/portal_house/hgrunt/com_followcom.wav
sound/portal_house/hgrunt/com_getinpos.wav
sound/portal_house/hgrunt/funny_scream.wav
sound/portal_house/hgrunt/GameCfg.wc
sound/portal_house/hgrunt/hg_got_boveda.wav
sound/portal_house/hgrunt/ht05_halfway.wav
sound/portal_house/hgrunt/ht07_dontknow.wav
sound/portal_house/hgrunt/ht07_tracking.wav
sound/portal_house/hgrunt/terwin.wav
sound/portal_house/items/GameCfg.wc
sound/portal_house/items/gunpickup4.wav
sound/portal_house/items/medcarge5.wav
sound/portal_house/items/weapondrop1.wav
sound/portal_house/kate/_comma.wav
sound/portal_house/kate/aimforhead.wav
sound/portal_house/kate/anotherdown.wav
sound/portal_house/kate/badfelling.wav
sound/portal_house/kate/becarefull.wav
sound/portal_house/kate/bequiet.wav
sound/portal_house/kate/bigeye.wav
sound/portal_house/kate/bringitone.wav
sound/portal_house/kate/close.wav
sound/portal_house/kate/correctway.wav
sound/portal_house/kate/cupoftie.wav
sound/portal_house/kate/didntwantthis.wav
sound/portal_house/kate/didseeshot.wav
sound/portal_house/kate/dieslimy.wav
sound/portal_house/kate/dinnerend.wav
sound/portal_house/kate/dontagree.wav
sound/portal_house/kate/dontdothat.wav
sound/portal_house/kate/dontdothis.wav
sound/portal_house/kate/dontknow.wav
sound/portal_house/kate/dontwantlive.wav
sound/portal_house/kate/freebarney.wav
sound/portal_house/kate/friendslikeyou.wav
sound/portal_house/kate/gotanother.wav
sound/portal_house/kate/gotone.wav
sound/portal_house/kate/hearsomething.wav
sound/portal_house/kate/hevno.wav
sound/portal_house/kate/hi.wav
sound/portal_house/kate/hitbad.wav
sound/portal_house/kate/hitbad2.wav
sound/portal_house/kate/hoyes.wav
sound/portal_house/kate/hummm.wav
sound/portal_house/kate/iamkate.wav
sound/portal_house/kate/ka_attack1.wav
sound/portal_house/kate/ka_attack2.wav
sound/portal_house/kate/ka_die1.wav
sound/portal_house/kate/ka_pain1.wav
sound/portal_house/kate/ka_pain2.wav
sound/portal_house/kate/muchmore.wav
sound/portal_house/kate/notatall.wav
sound/portal_house/kate/oneless.wav
sound/portal_house/kate/openfire.wav
sound/portal_house/kate/resquedatlast.wav
sound/portal_house/kate/seelater.wav
sound/portal_house/kate/seeyoulater.wav
sound/portal_house/kate/somethingmove.wav
sound/portal_house/kate/staypost.wav
sound/portal_house/kate/stepoff.wav
sound/portal_house/kate/stop1.wav
sound/portal_house/kate/teamup1.wav
sound/portal_house/kate/teamup2.wav
sound/portal_house/kate/thinking.wav
sound/portal_house/kate/waithere.wav
sound/portal_house/kate/waithere2.wav
sound/portal_house/kate/welcome.wav
sound/portal_house/kate/whatgoingon.wav
sound/portal_house/kate/whatgoingon2.wav
sound/portal_house/kate/whatyoudoing.wav
sound/portal_house/kate/yesbarn.wav
sound/portal_house/kate/youaredead.wav
sound/portal_house/kate/youneedmedic.wav
sound/portal_house/kate/youwish.wav
sound/portal_house/keller/dk_01_cascade.wav
sound/portal_house/keller/dk_01_survived.wav
sound/portal_house/keller/dk_05_mustseal.wav
sound/portal_house/keller/dk_05_needguard.wav
sound/portal_house/keller/dk_05_onceorbit.wav
sound/portal_house/keller/dk_05_otherside.wav
sound/portal_house/keller/dk_07_online.wav
sound/portal_house/keller/dk_11_goodwork.wav
sound/portal_house/keller/dk_12_cautious.wav
sound/portal_house/keller/dk_12_critical1.wav
sound/portal_house/keller/dk_12_deploy1.wav
sound/portal_house/keller/dk_12_dontcare.wav
sound/portal_house/keller/dk_12_followme.wav
sound/portal_house/keller/dk_12_wedidit.wav
sound/portal_house/keller/dk_12_whenstart.wav
sound/portal_house/panther/p_alert1.wav
sound/portal_house/panther/p_alert2.wav
sound/portal_house/panther/p_alert3.wav
sound/portal_house/panther/p_die1.wav
sound/portal_house/panther/p_die2.wav
sound/portal_house/panther/p_idle1.wav
sound/portal_house/panther/p_idle2.wav
sound/portal_house/panther/p_idle3.wav
sound/portal_house/panther/p_pain1.wav
sound/portal_house/panther/p_pain2.wav
sound/portal_house/player/kick.wav
sound/portal_house/player/pl_step1.wav
sound/portal_house/player/pl_step2.wav
sound/portal_house/player/pl_step3.wav
sound/portal_house/player/pl_step4.wav
sound/portal_house/player/pl_tile1.wav
sound/portal_house/player/pl_tile2.wav
sound/portal_house/player/pl_tile3.wav
sound/portal_house/player/pl_tile4.wav
sound/portal_house/player/pl_tile5.wav
sound/portal_house/player/punch.wav
sound/portal_house/probe/activate1.wav
sound/portal_house/probe/activate2.wav
sound/portal_house/probe/activate3.wav
sound/portal_house/probe/active.wav
sound/portal_house/probe/blowup.wva
sound/portal_house/probe/calclp2.wav
sound/portal_house/probe/falcoff.wav
sound/portal_house/probe/GameCfg.wc
sound/portal_house/probe/probealarm.wav
sound/portal_house/probe/shriek.wav
sound/portal_house/race/GameCfg.wc
sound/portal_house/race/race_alert1.wav
sound/portal_house/race/race_alert2.wav
sound/portal_house/race/race_die1.wav
sound/portal_house/race/race_die2.wav
sound/portal_house/race/race_idle1.wav
sound/portal_house/race/race_idle2.wav
sound/portal_house/race/race_idle3.wav
sound/portal_house/race/race_idle4.wav
sound/portal_house/race/race_pain1.wav
sound/portal_house/race/race_pain2.wav
sound/portal_house/race/race_pain3.wav
sound/portal_house/race/race_pain4.wav
sound/portal_house/race/race_pain5.wav
sound/portal_house/race/ufo_blast.wav
sound/portal_house/race/ufo_ejected.wav
sound/portal_house/race/ufo_runover.wav
sound/portal_house/race/ufo_select.wav
sound/portal_house/race/ufo_weapon.wav
sound/portal_house/rosenberg/ro_01_callhelp.wav
sound/portal_house/rosenberg/ro_01_chargers.wav
sound/portal_house/rosenberg/ro_01_danger.wav
sound/portal_house/rosenberg/ro_01_leaving.wav
sound/portal_house/rosenberg/ro_01_letsgo.wav
sound/portal_house/rosenberg/ro_01_spectrom.wav
sound/portal_house/rosenberg/ro_01_survived.wav
sound/portal_house/rosenberg/ro_02_careful.wav
sound/portal_house/rosenberg/ro_02_despite.wav
sound/portal_house/rosenberg/ro_03_aligned.wav
sound/portal_house/rosenberg/ro_03_inside.wav
sound/portal_house/rosenberg/ro_03_keller.wav
sound/portal_house/rosenberg/ro_03_notalign.wav
sound/portal_house/rosenberg/ro_03_perfect.wav
sound/portal_house/rosenberg/ro_03_senddown.wav
sound/portal_house/rosenberg/ro_03_surface.wav
sound/portal_house/rosenberg/ro_03_waithere.wav
sound/portal_house/rosenberg/ro_04_aligned.wav
sound/portal_house/rosenberg/ro_calhoun2.wav
sound/portal_house/rosenberg/ro_yard_rose1.wav
sound/portal_house/scientist/a402-c3a2_sci_5surv.wav
sound/portal_house/scientist/a407-c3a2_sci_straws.wav
sound/portal_house/scientist/a410-sc_canals3.wav
sound/portal_house/scientist/a415-of3a2_sc01.wav
sound/portal_house/scientist/a416-dangerous.wav
sound/portal_house/scientist/c3a1_sci_done.wav
sound/portal_house/scientist/c3a2_sci_2glu.wav
sound/portal_house/scientist/c3a2_sci_forever.wav
sound/portal_house/scientist/d01_sci02_door.wav
sound/portal_house/scientist/d01_sci03_reregister.wav
sound/portal_house/scientist/d01_sci06_dontmove.wav
sound/portal_house/scientist/d01_sci15_onschedule.wav
sound/portal_house/scientist/d06_sci01_lambdalabs.wav
sound/portal_house/scientist/d08_sci03_trackers.wav
sound/portal_house/scientist/d08_sci04_ceilinghatch.wav
sound/portal_house/scientist/d08_sci05_osprey.wav
sound/portal_house/scientist/GameCfg.wc
sound/portal_house/scientist/mcro_d08_sci05_osprey.wav
sound/portal_house/scientist/ot08_resetthestage.wav
sound/portal_house/scientist/sc_hello0.wav
sound/portal_house/scientist/sc_power1.wav
sound/portal_house/scientist/sc_stop3.wav
sound/portal_house/scientist/sc_tele_xen1.wav
sound/portal_house/scientist/sc_yard_box2.wav
sound/portal_house/scientist/sc_yard_box4.wav
sound/portal_house/scientist/sci_a3_position.wav
sound/portal_house/scientist/sci_phone01.wav
sound/portal_house/scientist/sci_portopen.wav
sound/portal_house/scientist/sunsets.wav
sound/portal_house/scientist/xet6_portal_begin.wav
sound/portal_house/sforce/spf_reload1.wav
sound/portal_house/sforce/spf_reload2.wav
sound/portal_house/sforce/spf_reload3.wav
sound/portal_house/sphere/GameCfg.wc
sound/portal_house/sphere/sph_alert1.wav
sound/portal_house/sphere/sph_idle1.wav
sound/portal_house/sphere/sph_sph_idle2.wav
sound/portal_house/sphere/sph_motor1.wav
sound/portal_house/sphere/sph_pain1.wav
sound/portal_house/stukabat/stkb_deploy1.wav
sound/portal_house/stukabat/stkb_deploy2.wav
sound/portal_house/stukabat/stkb_die1.wav
sound/portal_house/stukabat/stkb_fire1.wav
sound/portal_house/stukabat/stkb_fire2.wav
sound/portal_house/stukabat/stkb_flying1.wav
sound/portal_house/stukabat/stkb_idle1.wav
sound/portal_house/stukabat/stkb_idletpick1.wav
sound/portal_house/stukabat/stkb_idletpick2.wav
sound/portal_house/toad/toad_blast1.wav
sound/portal_house/toad/toad_deploy1.wav
sound/portal_house/toad/toad_die1.wav
sound/portal_house/toad/toad_hunt1.wav
sound/portal_house/toad/toad_hunt2.wav
sound/portal_house/toad/toad_hunt3.wav
sound/portal_house/toad/toadloop.wav
sound/portal_house/toad/toadspinup.wav
sound/portal_house/turret/click1.wav
sound/portal_house/turret/shoot2.wav
sound/portal_house/turret/shoot3.wav
sound/portal_house/turret/tu_active.wav
sound/portal_house/turret/tu_active2.wav
sound/portal_house/turret/tu_alarm.wav
sound/portal_house/turret/tu_alert.wav
sound/portal_house/turret/tu_deploy.wav
sound/portal_house/turret/tu_die.wav
sound/portal_house/turret/tu_die2.wav
sound/portal_house/turret/tu_di3.wav
sound/portal_house/turret/tu_fire1.wav
sound/portal_house/turret/tu_ping.wav
sound/portal_house/turret/tu_retract.wav
sound/portal_house/turret/tu_search.wav
sound/portal_house/turret/tu_spindown.wav
sound/portal_house/turret/tu_spinup.wav
sound/portal_house/vox/attention_team01.wav
sound/portal_house/vox/attention_team02.wav
sound/portal_house/vox/attention_team03.wav
sound/portal_house/vox/attention_team04.wav
sound/portal_house/vox/c1a2_1.wav
sound/portal_house/vox/c1a2_4.wav
sound/portal_house/vox/c1a2_7.wav
sound/portal_house/vox/c1a3_0.wav
sound/portal_house/vox/c2a4_3.wav
sound/portal_house/vox/c2a4_9.wav
sound/portal_house/vox/end01.wav
sound/portal_house/vox/end02.wav
sound/portal_house/vox/f_confirmcivilstatus_1_spkr.wav
sound/portal_house/vox/fprison_restrictorsdisengaged.wav
sound/portal_house/vox/GameCfg.wc
sound/portal_house/vox/item_rdy.wav
sound/portal_house/vox/next_level01.wav
sound/portal_house/vox/next_level02.wav
sound/portal_house/vox/portal_up.wav
sound/portal_house/vox/radio01.wav
sound/portal_house/vox/radio02.wav
sound/portal_house/vox/shield_activated.wav
sound/portal_house/vox/shield_ready.wav
sound/portal_house/vox/start_sector_b.wav
sound/portal_house/vox/start_sector_c.wav
sound/portal_house/vox/start_sector_d.wav
sound/portal_house/vox/ten_seconds.wav
sound/portal_house/vox/three minutes.wav
sound/portal_house/vox/vox_end.wav
sound/portal_house/vox/warning01.wav
sound/portal_house/weapons/beretta_fire1.wav
sound/portal_house/weapons/c4_beep1.wav
sound/portal_house/weapons/c4_click.wav
sound/portal_house/weapons/clipinsert1.wav
sound/portal_house/weapons/cliprelease1.wav
sound/portal_house/weapons/disruptor.wav
sound/portal_house/weapons/doub_barrel1.wav
sound/portal_house/weapons/explosion_large.wav
sound/portal_house/weapons/fire_both1.wav
sound/portal_house/weapons/fire_both2.wav
sound/portal_house/weapons/fire_minigun01.wav
sound/portal_house/weapons/GameCfg.wc
sound/portal_house/weapons/gr_mgun1.wav
sound/portal_house/weapons/gr_mp5gun1.wav
sound/portal_house/weapons/hks1.wav
sound/portal_house/weapons/hks2.wav
sound/portal_house/weapons/hks3.wav
sound/portal_house/weapons/horngun_down.wav
sound/portal_house/weapons/horngun_draw.wav
sound/portal_house/weapons/horngun_idle1.wav
sound/portal_house/weapons/horngun_idle2.wav
sound/portal_house/weapons/m16burst.wav
sound/portal_house/weapons/m41a_3round.wav
sound/portal_house/weapons/m41a_single.wav
sound/portal_house/weapons/m41aglauncher.wav
sound/portal_house/weapons/m41aglauncher2.wav
sound/portal_house/weapons/mp5_hks1.wav
sound/portal_house/weapons/mp5_hks2.wav
sound/portal_house/weapons/mp5_hks3.wav
sound/portal_house/weapons/p904_reload1.wav
sound/portal_house/weapons/p904_reload2.wav
sound/portal_house/weapons/plasma_re.wav
sound/portal_house/weapons/plasma1.wav
sound/portal_house/weapons/plasma2.wav
sound/portal_house/weapons/sawedoff_fire.wav
sound/portal_house/weapons/sawedoff_pump.wav
sound/portal_house/weapons/sawedoff_reload1.wav
sound/portal_house/weapons/sawedoff_reload2.wav
sound/portal_house/weapons/sbarrel1.wav
sound/portal_house/weapons/scock1.wav
sound/portal_house/weapons/shoot_barrel1.wav
sound/portal_house/weapons/shoot_cock1.wav
sound/portal_house/weapons/shoot1.wav
sound/portal_house/weapons/shoot2.wav
sound/portal_house/weapons/shoot3.wav
sound/portal_house/weapons/sniper_fire.wav
sound/portal_house/zgrunt/fire_zgrunt.wav
sound/portal_house/zgrunt/grenade_zgrunt.wav
sound/portal_house/zgrunt/incoming_zgrunt.wav
sound/portal_house/zgrunt/saw_reload2op.wav
sound/portal_house/zgrunt/saw_reloadop.wav
sound/portal_house/zgrunt/take_zgrunt.wav
sound/portal_house/zgrunt/zg_die1.wav
sound/portal_house/zgrunt/zg_die2.wav
sound/portal_house/zgrunt/zg_di3.wav
sound/portal_house/zgrunt/zg_pain1.wav
sound/portal_house/zgrunt/zg_pain2.wav
sound/portal_house/zgrunt/zg_pain3.wav
sound/portal_house/zgrunt/zg_pain4.wav
sound/portal_house/a_teleport.wav
sound/portal_house/air_raid.wav
sound/portal_house/alarm.wav
sound/portal_house/alienflying.wav
sound/portal_house/alienflying02.wav
sound/portal_house/alienflying03.wav
sound/portal_house/alienflying04.wav
sound/portal_house/alienwave.wav
sound/portal_house/Arrival Of The Race.mp3
sound/portal_house/B3_00002.wav
sound/portal_house/beep_car.wav
sound/portal_house/beepclear.wav
sound/portal_house/BM_team.wav
sound/portal_house/break-floor.wav
sound/portal_house/c0a0_tr_arrive.wav
sound/portal_house/carhorn.wav
sound/portal_house/clistal.wav
sound/portal_house/CmdSeq.wc
sound/portal_house/crate_scrape1.wav
sound/portal_house/crate_scrape2.wav
sound/portal_house/crunch.wav
sound/portal_house/crusher_minerals.wav
sound/portal_house/emergency_power_off.wav
sound/portal_house/explosion_aflock01.wav
sound/portal_house/explosion01.wav
sound/portal_house/fisure.wav
sound/portal_house/flareidle.wav
sound/portal_house/flush.wav
sound/portal_house/GameCfg.wc
sound/portal_house/genoff1.wav
sound/portal_house/hahaha.wav
sound/portal_house/healingpond1.wav
sound/portal_house/IceLaunch.wav
sound/portal_house/item_armorves.txt
sound/portal_house/item_box.txt
sound/portal_house/item_xenmedic.txt
sound/portal_house/jeep_door.wav
sound/portal_house/jeep_drive.wav
sound/portal_house/jeep_start.wav
sound/portal_house/jetflyby2.wav
sound/portal_house/jetflyby3.wav
sound/portal_house/jisin.wav
sound/portal_house/laser.wav
sound/portal_house/Launch1.wav
sound/portal_house/mantadie1.wav
sound/portal_house/mech_rumble.wav
sound/portal_house/monster_archer.txt
sound/portal_house/monster_babypanther.txt
sound/portal_house/monster_barney.txt
sound/portal_house/monster_barniel.txt
sound/portal_house/monster_bloater.txt
sound/portal_house/monster_bodyguard.txt
sound/portal_house/monster_ftzombie.txt
sound/portal_house/monster_hevbarney.txt
sound/portal_house/monster_hevsci.txt
sound/portal_house/monster_hgrunt.txt
sound/portal_house/monster_houndeye.txt
sound/portal_house/monster_hwgrunt.txt
sound/portal_house/monster_kate.txt
sound/portal_house/monster_manta.txt
sound/portal_house/monster_panther.txt
sound/portal_house/monster_pitworm.txt
sound/portal_house/monster_race.txt
sound/portal_house/monster_robolaser.txt
sound/portal_house/monster_scientist.txt
sound/portal_house/monster_sforce.txt
sound/portal_house/monster_spfsci.txt
sound/portal_house/monster_turret.txt
sound/portal_house/monster_ufo.txt
sound/portal_house/monster_valemoth.txt
sound/portal_house/monster_zgrunt.txt
sound/portal_house/monster_zgruntsaw.txt
sound/portal_house/music - hl2_song32.mp3
sound/portal_house/music - inside Submarine.mp3
sound/portal_house/music - OpposingForce05.mp3
sound/portal_house/music - ruminations.mp3
sound/portal_house/news63.mp3
sound/portal_house/nuclearstrikelaunch.wav
sound/portal_house/nuke_explode.wav
sound/portal_house/pcv_vest.wav
sound/portal_house/phone_msg.wav
sound/portal_house/phone_Ring.wav
sound/portal_house/phone1.wav
sound/portal_house/phone2.wav
sound/portal_house/pico.wav
sound/portal_house/radio.wav
sound/portal_house/rc_step1.wav
sound/portal_house/RTCORE_00015.wav
sound/portal_house/RTCORE_00019.wav
sound/portal_house/RTCORE_00025.wav
sound/portal_house/RTCORE_00033.wav
sound/portal_house/RTCORE_00039.wav
sound/portal_house/rumble.wav
sound/portal_house/run1.wav
sound/portal_house/Sc2 -We Stand Ready.mp3
sound/portal_house/secret.wav
sound/portal_house/set.wav
sound/portal_house/SF_team.wav
sound/portal_house/sf1.wav
sound/portal_house/sf5.wav
sound/portal_house/shoot_chaos1.wav
sound/portal_house/skid.wav
sound/portal_house/slosh-mass.wav
sound/portal_house/sonicbangfar1.wav
sound/portal_house/sound_climax.txt
sound/portal_house/sound_global_A1.txt
sound/portal_house/sound_global_A2.txt
sound/portal_house/sound_global_A4.txt
sound/portal_house/sound_global_B.txt
sound/portal_house/sound_global_C.txt
sound/portal_house/sound_global_D.txt
sound/portal_house/speeder.wav
sound/portal_house/static.wav
sound/portal_house/steps_atst.wav
sound/portal_house/terrain_runble1.wav
sound/portal_house/tor_intro.wav
sound/portal_house/truck_stop.wav
sound/portal_house/ufo.wav
sound/portal_house/ufo_bgm.wav
sound/portal_house/ufo_on.wav
sound/portal_house/ufobeam.wav
sound/portal_house/ufobeam2.wav
sound/portal_house/underwater.wav
sound/portal_house/valve_xen01.wav
sound/portal_house/warpstart1.wav
sound/portal_house/warpstart2.wav
sound/portal_house/xenjetlight1.wav
sound/portal_house/xenop4music_once.mp3
sound/portal_house/xensound0.wav
sound/portal_house/xensound1.wav
sound/portal_house/xet6_portal_begin.wav

sprites/portal_house/hud_of/640hud1of.spr
sprites/portal_house/hud_of/640hud2of.spr
sprites/portal_house/hud_of/640hud3of.spr
sprites/portal_house/hud_of/640hud4of.spr
sprites/portal_house/hud_of/640hud5of.spr
sprites/portal_house/hud_of/640hud6of.spr
sprites/portal_house/hud_of/640hud7of.spr
sprites/portal_house/hud_of/640hudof01.spr
sprites/portal_house/hud_of/640hudof02.spr
sprites/portal_house/hud_of/640hudof03.spr
sprites/portal_house/hud_of/640hudof04.spr
sprites/portal_house/hud_of/640hudsc2of.spr
sprites/portal_house/hud_of/640hudscof.spr
sprites/portal_house/hud_of/640shl1of.spr
sprites/portal_house/hud_of/640shl2of.spr
sprites/portal_house/hud_of/640shl3of.spr
sprites/portal_house/hud_of/640shl4of.spr
sprites/portal_house/hud_of/crosshairsof.spr
sprites/portal_house/hud_of/ofch1.spr
sprites/portal_house/hud_of/weapon_9mmar.txt
sprites/portal_house/hud_of/weapon_crowbar.txt
sprites/portal_house/hud_of/weapon_eagle.txt
sprites/portal_house/hud_of/weapon_grapple.txt
sprites/portal_house/hud_of/weapon_handgrenade.txt
sprites/portal_house/hud_of/weapon_knife.txt
sprites/portal_house/hud_of/weapon_m16.txt
sprites/portal_house/hud_of/weapon_m249.txt
sprites/portal_house/hud_of/weapon_ofshockrifle.txt
sprites/portal_house/hud_of/weapon_rpg.txt
sprites/portal_house/hud_of/weapon_shockrifle.txt
sprites/portal_house/hud_of/weapon_shotgun.txt
sprites/portal_house/hud_of/weapon_snark.txt
sprites/portal_house/hud_of/weapon_sniperrifle.txt
sprites/portal_house/hud_of/weapon_sporelauncher.txt
sprites/portal_house/hud_of/weapon_uzi.txt
sprites/portal_house/hud_of/weapon_uziakimbo.txt
sprites/portal_house/hud_of/weapon_vulcan.txt
sprites/portal_house/hud_sc/weapon_snark.txt
sprites/portal_house/hud_sf/640hud1sf.spr
sprites/portal_house/hud_sf/640hud2sf.spr
sprites/portal_house/hud_sf/640hud3sf.spr
sprites/portal_house/hud_sf/640hud4sf.spr
sprites/portal_house/hud_sf/640hud5sf.spr
sprites/portal_house/hud_sf/640hud6sf.spr
sprites/portal_house/hud_sf/640hud7sf.spr
sprites/portal_house/hud_sf/640hudof01_dispsf.spr
sprites/portal_house/hud_sf/640hudof01sf.spr
sprites/portal_house/hud_sf/640hudof02_dispsf.spr
sprites/portal_house/hud_sf/640hudof02sf.spr
sprites/portal_house/hud_sf/640hudscsf.spr
sprites/portal_house/hud_sf/640shl1sf.spr
sprites/portal_house/hud_sf/640shl2sf.spr
sprites/portal_house/hud_sf/640shl3sf.spr
sprites/portal_house/hud_sf/640shl4sf.spr
sprites/portal_house/hud_sf/crosshairssf.spr
sprites/portal_house/hud_sf/sfch1.spr
sprites/portal_house/hud_sf/weapon_9mmm41a.txt
sprites/portal_house/hud_sf/weapon_beretta.txt
sprites/portal_house/hud_sf/weapon_displacer.txt
sprites/portal_house/hud_sf/weapon_eagle.txt
sprites/portal_house/hud_sf/weapon_handgrenade.txt
sprites/portal_house/hud_sf/weapon_hornetgun.txt
sprites/portal_house/hud_sf/weapon_m16.txt
sprites/portal_house/hud_sf/weapon_m249.txt
sprites/portal_house/hud_sf/weapon_plasmagun.txt
sprites/portal_house/hud_sf/weapon_rpg.txt
sprites/portal_house/hud_sf/weapon_sawedoff.txt
sprites/portal_house/hud_sf/weapon_shotgun.txt
sprites/portal_house/hud_sf/weapon_snark.txt
sprites/portal_house/hud_sf/weapon_uzi.txt
sprites/portal_house/hud_sf/weapon_uziakimbo.txt
sprites/portal_house/640hud1.spr
sprites/portal_house/640hud4.spr
sprites/portal_house/640hudas1.spr
sprites/portal_house/640hudas3.spr
sprites/portal_house/640hudas4.spr
sprites/portal_house/640hudas6.spr
sprites/portal_house/640hudas7.spr
sprites/portal_house/640hudof03.spr
sprites/portal_house/640hudof04.spr
sprites/portal_house/640hudpv2.spr
sprites/portal_house/640hudpv5.spr
sprites/portal_house/640hudsc2.spr
sprites/portal_house/640shl1.spr
sprites/portal_house/640shl2.spr
sprites/portal_house/640shl3.spr
sprites/portal_house/640shl4.spr
sprites/portal_house/ammo.spr
sprites/portal_house/blasterimpact.spr
sprites/portal_house/car_track01.spr
sprites/portal_house/crosshairsas.spr
sprites/portal_house/cshoot.spr
sprites/portal_house/cum.spr
sprites/portal_house/expB1.spr
sprites/portal_house/GameCfg.wc
sprites/portal_house/ph_sector_A1.spr
sprites/portal_house/ph_sector_A2.spr
sprites/portal_house/ph_sector_A3.spr
sprites/portal_house/ph_sector_A4.spr
sprites/portal_house/ph_sector_B.spr
sprites/portal_house/ph_sector_C.spr
sprites/portal_house/ph_sector_D.spr
sprites/portal_house/plasma.spr
sprites/portal_house/plasmasmall.spr
sprites/portal_house/poner.spr
sprites/portal_house/power_up.spr
sprites/portal_house/sentry_01.spr
sprites/portal_house/sentry_02.spr
sprites/portal_house/sentry_03.spr
sprites/portal_house/sentry_04.spr
sprites/portal_house/talk.spr
sprites/portal_house/target.spr
sprites/portal_house/tools.spr
sprites/portal_house/usable.spr
sprites/portal_house/usar.spr
sprites/portal_house/valve_rot.spr
sprites/portal_house/weapon_9mmm41a.txt
sprites/portal_house/weapon_beretta.txt
sprites/portal_house/weapon_honetgundual.txt
sprites/portal_house/weapon_knife.txt
sprites/portal_house/weapon_mp5hl.txt
sprites/portal_house/weapon_p904.txt
sprites/portal_house/weapon_plasmagun.txt
sprites/portal_house/weapon_sawedoff.txt
sprites/portal_house/weapon_shotgunhl.txt
sprites/portal_house/weapon_vulcan.txt
sprites/portal_house/xonxt.spr