events/muzzle_ins2_DSG.txt
events/muzzle_ins2_DSG2.txt
maps/ragemap2022_readme.txt
maps/ragemap2022b.cfg
maps/ragemap2022b.res
maps/ragemap2022b.txt
models/bridge/vollight3.mdl
models/gruntmodels/arch1.mdl
models/gruntmodels/arch2.mdl
models/gruntmodels/bigstairs.mdl
models/gruntmodels/blackskeleton.mdl
models/gruntmodels/cc_Trees_kadka.mdl
models/gruntmodels/cliff.mdl
models/gruntmodels/cliff2.mdl
models/gruntmodels/cliff4.mdl
models/gruntmodels/controller.mdl
models/gruntmodels/deadrock.mdl
models/gruntmodels/gem.mdl
models/gruntmodels/ghost.mdl
models/gruntmodels/mountains.mdl
models/gruntmodels/pillar.mdl
models/gruntmodels/pillar2.mdl
models/gruntmodels/rocky.mdl
models/gruntmodels/skysphere.mdl
models/gruntmodels/stairs.mdl
models/gruntmodels/stairs2.mdl
models/gruntmodels/stat.mdl
models/gruntmodels/stat2.mdl
models/gruntmodels/table.mdl
models/gruntmodels/taogmountain.mdl
models/gruntmodels/tree1.mdl
models/gruntmodels/tree2.mdl
models/gruntmodels/tree3.mdl
models/gruntmodels/wood_fence.mdl
models/ragemap2022/hezus/balloon_fullbright.mdl
models/ragemap2022/hezus/dev_apache.mdl
models/ragemap2022/hezus/gaussammo.mdl
models/ragemap2022/hezus/p_displacer_blue.mdl
models/ragemap2022/hezus/p_displacer_green.mdl
models/ragemap2022/hezus/p_displacer_red.mdl
models/ragemap2022/hezus/p_displacer_yellow.mdl
models/ragemap2022/hezus/v_displacer_blue.mdl
models/ragemap2022/hezus/v_displacer_green.mdl
models/ragemap2022/hezus/v_displacer_red.mdl
models/ragemap2022/hezus/v_displacer_yellow.mdl
models/ragemap2022/hezus/w_displacer_blue.mdl
models/ragemap2022/hezus/w_displacer_green.mdl
models/ragemap2022/hezus/w_displacer_red.mdl
models/ragemap2022/hezus/w_displacer_yellow.mdl
models/ragemap2022/p_slugger.mdl
models/ragemap2022/v_slugger.mdl
models/ragemap2022/w_slugger.mdl
scripts/ragemap2022/CustomHUD.as
scripts/ragemap2022/ragemap2022.as
scripts/ragemap2022/ragemap2022b.as
scripts/weapon_custom/v9/attack.as
scripts/weapon_custom/v9/monster_custom.as
scripts/weapon_custom/v9/MonsterCustomBase.as
scripts/weapon_custom/v9/utils.as
scripts/weapon_custom/v9/weapon_custom.as
scripts/weapon_custom/v9/WeaponCustomBase.as
scripts/weapon_test.as
sound/gruntsounds/dangerisgone.wav
sound/gruntsounds/dangerishere.wav
sound/gruntsounds/dangersoon.ogg
sound/gruntsounds/dangerstart.wav
sound/gruntsounds/dead1.ogg
sound/gruntsounds/dead2.ogg
sound/gruntsounds/dead3.ogg
sound/gruntsounds/dead4.ogg
sound/gruntsounds/dead5.ogg
sound/gruntsounds/dead6.ogg
sound/gruntsounds/dead7.ogg
sound/gruntsounds/dead8.ogg
sound/gruntsounds/escaped.ogg
sound/gruntsounds/gemreturned1.ogg
sound/gruntsounds/gemreturned2.ogg
sound/gruntsounds/gemreturned3.ogg
sound/gruntsounds/gemreturned4.ogg
sound/gruntsounds/gemreturned5.ogg
sound/gruntsounds/gemreturned6.ogg
sound/gruntsounds/gemreturned7.ogg
sound/gruntsounds/gemsound1.ogg
sound/gruntsounds/gemsound2.ogg
sound/gruntsounds/intro1.ogg
sound/gruntsounds/intro2.ogg
sound/gruntsounds/intro3.ogg
sound/gruntsounds/mock2.ogg
sound/gruntsounds/order1.ogg
sound/gruntsounds/order2.ogg
sound/gruntsounds/order3.ogg
sound/gruntsounds/taogfrustrated.ogg
sound/gruntsounds/teleport.ogg
sound/gruntsounds/teleporting.ogg
sound/gruntsounds/WestmarchOST.wav
sound/gruntsounds/wind2.wav
sound/ragemap2022/dragons_legend_loop.ogg
sound/ragemap2022/dsbell.ogg
sound/ragemap2022/dsblst.ogg
sound/ragemap2022/dsflame.ogg
sound/ragemap2022/dsgong.ogg
sound/ragemap2022/dssndfdb.ogg
sound/ragemap2022/dsstnmov.ogg
sound/ragemap2022/dsstnmov2.ogg
sound/ragemap2022/dsstnstp.ogg
sound/ragemap2022/dstlprt.ogg
sound/ragemap2022/foe_hub.ogg
sound/ragemap2022/hezus/beyourself.mp3
sound/ragemap2022/mk_frenship.ogg
sound/ragemap2022/slugger_close.ogg
sound/ragemap2022/slugger_eject.ogg
sound/ragemap2022/slugger_empty.ogg
sound/ragemap2022/slugger_grab.ogg
sound/ragemap2022/slugger_ins1.ogg
sound/ragemap2022/slugger_ins2.ogg
sound/ragemap2022/slugger_open.ogg
sound/ragemap2022/slugger_sboth.ogg
sound/ragemap2022/slugger_shoot.ogg
sprites/ragemap2022/dsflameb.spr
sprites/ragemap2022/dsflameg.spr
sprites/ragemap2022/dsflamer.spr
sprites/ragemap2022/dsflm.spr
sprites/ragemap2022/dsgameover.spr
sprites/ragemap2022/dsportal.spr
sprites/ragemap2022/gruntsprites/backpack.spr
sprites/ragemap2022/gruntsprites/eye.spr
sprites/ragemap2022/weapon_slugger.txt
sprites/ragemap2022/wpn.spr
