// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

rl_.wad

gfx/env/voidhorizonbk.tga
gfx/env/voidhorizondn.tga
gfx/env/voidhorizonft.tga
gfx/env/voidhorizonlf.tga
gfx/env/voidhorizonrt.tga
gfx/env/voidhorizonup.tga
gfx/env/pdawnbk.tga
gfx/env/pdawndn.tga
gfx/env/pdawnft.tga
gfx/env/pdawnlf.tga
gfx/env/pdawnrt.tga
gfx/env/pdawnup.tga

models/player/cl_scientist1/cl_scientist1.mdl
models/player/cl_scientist2/cl_scientist2.mdl
models/player/cl_scientist3/cl_scientist3.mdl
models/player/cl_scientist4/cl_scientist4.mdl
models/player/cl_scientist5/cl_scientist5.mdl
models/player/cl_scientist6/cl_scientist6.mdl

models/residuallife/weapons/v_9mmar.mdl
models/residuallife/weapons/v_9mmhandgun.mdl
models/residuallife/weapons/v_357.mdl
models/residuallife/weapons/v_crossbow.mdl
models/residuallife/weapons/v_crowbar.mdl
models/residuallife/weapons/v_desert_eagle2.mdl
models/residuallife/weapons/v_egon.mdl
models/residuallife/weapons/v_gauss.mdl
models/residuallife/weapons/v_gaussAR.mdl
models/residuallife/weapons/v_grenade.mdl
models/residuallife/weapons/v_handgrenade.mdl
models/residuallife/weapons/v_hgun.mdl
models/residuallife/weapons/v_m16a2.mdl
models/residuallife/weapons/v_medkit.mdl
models/residuallife/weapons/v_rpg.mdl
models/residuallife/weapons/v_satchel.mdl
models/residuallife/weapons/v_satchel_radio.mdl
models/residuallife/weapons/v_shotgun.mdl
models/residuallife/weapons/v_squeak2.mdl
models/residuallife/weapons/v_tripmine.mdl
models/residuallife/weapons/w_golden.mdl
models/residuallife/weapons/w_goldent.mdl

models/residuallife/aworker.mdl
models/residuallife/aworker01.mdl
models/residuallife/aworker02.mdl
models/residuallife/baby_icky.mdl
models/residuallife/barney.mdl
models/residuallife/barney.mdl
models/residuallife/barney01.mdl
models/residuallife/barney02.mdl
models/residuallife/barney03.mdl
models/residuallife/barney04.mdl
models/residuallife/barney05.mdl
models/residuallife/barney06.mdl
models/residuallife/barney07.mdl
models/residuallife/barneyt.mdl
models/residuallife/civ_scientist_.mdl
models/residuallife/cleansuit_scientist.mdl
models/residuallife/dead_barney.mdl
models/residuallife/dead_barney01.mdl
models/residuallife/dissected_headcrab.mdl
models/residuallife/food_tray.mdl
models/residuallife/gonome.mdl
models/residuallife/hassassin.mdl
models/residuallife/hgrunt_opfor.mdl
models/residuallife/hgrunt_opfor01.mdl
models/residuallife/hgrunt_opfor02.mdl
models/residuallife/hgrunt_opfor03.mdl
models/residuallife/hunter.mdl
models/residuallife/icky.mdl
models/residuallife/leech.mdl
models/residuallife/loader2.mdl
models/residuallife/massn.mdl
models/residuallife/nihilanth.mdl
models/residuallife/nuke_warhead.mdl
models/residuallife/rbarrel.mdl
models/residuallife/rustygibs.mdl
models/residuallife/scientist.mdl
models/residuallife/scientist01.mdl
models/residuallife/scientist02.mdl
models/residuallife/scientist03.mdl
models/residuallife/scientist04.mdl
models/residuallife/scientist05.mdl
models/residuallife/scientist06.mdl
models/residuallife/scientist07.mdl
models/residuallife/scientist08.mdl
models/residuallife/scientist09.mdl
models/residuallife/scientist10.mdl
models/residuallife/skeleton2_.mdl
models/residuallife/sl_dead.mdl
models/residuallife/sohn.mdl
models/residuallife/tool_box.mdl
models/residuallife/w_bloodly_9mmAR.mdl
models/residuallife/w_bloodly_shotgun.mdl
models/residuallife/w_bloodly_shotgunt.mdl
models/residuallife/w_desert_eagle.mdl
models/residuallife/w_suit.mdl
models/residuallife/xboss.mdl
models/residuallife/xen_rockgib_med.mdl
models/residuallife/xenocrab.mdl
models/residuallife/zgrunt.mdl
models/residuallife/zgrunt01.mdl
models/residuallife/zgrunt02.mdl

sound/residuallife/ambience/alienflyby2.wav
sound/residuallife/ambience/mch_warn.wav
sound/residuallife/ambience/ru3xyz_shaft.wav
sound/residuallife/barney/ba_ht06_01.wav
sound/residuallife/barney/ba_late.wav
sound/residuallife/barney/ba_security1_door1.wav
sound/residuallife/barney/ba_security1_door2.wav
sound/residuallife/barney/ba_security2_admin.wav
sound/residuallife/barney/ba_security2_desk0.wav
sound/residuallife/barney/ba_security2_range2.wav
sound/residuallife/barney/s02ba_hello.wav
sound/residuallife/barney/s02ba_pl_door.wav
sound/residuallife/barney/sk02_ba_headdown.wav
sound/residuallife/debris/a_teleport.wav
sound/residuallife/fgrunt/ok03b_fg01.wav
sound/residuallife/fvox/inject1.wav
sound/residuallife/gman/gman_intro_talk0.wav
sound/residuallife/gman/intro_gman_tulk1a.wav
sound/residuallife/gman/intro_gman_tulk1b.wav
sound/residuallife/media/Half-Life09.mp3
sound/residuallife/media/Half-Life15.mp3
sound/residuallife/music/jhhh.wav
sound/residuallife/music/ppharphir_nohim.wav
sound/residuallife/ngrunt/ng_idle0.wav
sound/residuallife/ngrunt/ng_idle1.wav
sound/residuallife/ngrunt/ng_idle2.wav
sound/residuallife/ngrunt/ng_idle3.wav
sound/residuallife/ngrunt/ng_minesp2.wav
sound/residuallife/radio/of1a2_rd01.wav
sound/residuallife/scientist/dk01_sci_talk.wav
sound/residuallife/scientist/rl02_sci01_lambdalabs.wav
sound/residuallife/scientist/ro_xen_call1.wav
sound/residuallife/scientist/ro_xen_call2.wav
sound/residuallife/scientist/sc_crazer.wav
sound/residuallife/scientist/sc_helloh.wav
sound/residuallife/scientist/sci_busy.wav
sound/residuallife/scientist/sci_outhere.wav
sound/residuallife/scientist/sci_portopen.wav
sound/residuallife/scientist/stop3.wav
sound/residuallife/tride/ba_tram8.wav
sound/residuallife/war_snd/air_raid.wav
sound/residuallife/weapons/nuke_tick.wav
sound/residuallife/weapons/sniper_fire.wav
sound/residuallife/residual_global.txt
sound/residuallife/residual_global_sniper.txt
sound/residuallife/residual_materials.txt
sound/residuallife/residual_sentences_.txt
sound/residuallife/zgrunt_soundlist.txt

//server

models/residuallife/weapons/sd/v_9mmar.mdl
models/residuallife/weapons/sd/v_9mmhandgun.mdl
models/residuallife/weapons/sd/v_357.mdl
models/residuallife/weapons/sd/v_chub.mdl
models/residuallife/weapons/sd/v_crossbow.mdl
models/residuallife/weapons/sd/v_crowbar.mdl
models/residuallife/weapons/sd/v_desert_eagle.mdl
models/residuallife/weapons/sd/v_desert_eagle2.mdl
models/residuallife/weapons/sd/v_displacer.mdl
models/residuallife/weapons/sd/v_egon.mdl
models/residuallife/weapons/sd/v_gauss.mdl
models/residuallife/weapons/sd/v_gaussAR.mdl
models/residuallife/weapons/sd/v_grenade.mdl
models/residuallife/weapons/sd/v_hgun.mdl
models/residuallife/weapons/sd/v_m40a1.mdl
models/residuallife/weapons/sd/v_medkit.mdl
models/residuallife/weapons/sd/v_pipe_wrench.mdl
models/residuallife/weapons/sd/v_rpg.mdl
models/residuallife/weapons/sd/v_satchel.mdl
models/residuallife/weapons/sd/v_satchel_radio.mdl
models/residuallife/weapons/sd/v_saw.mdl
models/residuallife/weapons/sd/v_shotgun.mdl
models/residuallife/weapons/sd/v_spore_launcher.mdl
models/residuallife/weapons/sd/v_tripmine.mdl
models/residuallife/weapons/sd/v_uzi.mdl

//opfor + svencoop classic weapons plugins
models/valve/sd/p_2uzis.mdl
models/valve/sd/p_2uzis_gold.mdl
models/valve/sd/p_bgrap.mdl
models/valve/sd/p_desert_eagle.mdl
models/valve/sd/p_displacer.mdl
models/valve/sd/p_glock.mdl
models/valve/sd/p_m16.mdl
models/valve/sd/p_m40a1.mdl
models/valve/sd/p_minigunidle.mdl
models/valve/sd/p_minigunspin.mdl
models/valve/sd/p_pipe_wrench.mdl
models/valve/sd/p_saw.mdl
models/valve/sd/p_shock.mdl
models/valve/sd/p_spore_launcher.mdl
models/valve/sd/p_uzi.mdl
models/valve/sd/p_uzi_gold.mdl

models/valve/sd/v_shock.mdl

models/valve/sd/w_2uzis.mdl
models/valve/sd/w_2uzis_gold.mdl
models/valve/sd/w_bgrap.mdl
models/valve/sd/w_desert_eagle.mdl
models/valve/sd/w_displacer.mdl
models/valve/sd/w_m16.mdl
models/valve/sd/w_m40a1.mdl
models/valve/sd/w_m40a1clip.mdl
models/valve/sd/w_minigun.mdl
models/valve/sd/w_pipe_wrench.mdl
models/valve/sd/w_saw.mdl
models/valve/sd/w_saw_clip.mdl
models/valve/sd/w_shock.mdl
models/valve/sd/w_shock_rifle.mdl
models/valve/sd/w_spore_launcher.mdl
models/valve/sd/w_uzi.mdl
models/valve/sd/w_uzi_clip.mdl
models/valve/sd/w_uzi_gold.mdl

models/valve/sd/saw_shell.mdl
models/valve/sd/shell.mdl

sprites/hl_weapons/weapon_hlpython.txt
sprites/hl_weapons/weapon_ofeagle.txt
sprites/hl_weapons/weapon_ofm249.txt
sprites/hl_weapons/weapon_ofshockrifle.txt
sprites/hl_weapons/weapon_ofsniperrifle.txt

sound/hlclassic/weapons/desert_eagle_reload.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav