// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/inletduskbk.tga
gfx/env/inletduskdn.tga
gfx/env/inletduskft.tga
gfx/env/inletdusklf.tga
gfx/env/inletduskrt.tga
gfx/env/inletduskup.tga
models/sa13/agrunt.mdl
models/sa13/agruntf.mdl
models/sa13/apache.mdl
models/sa13/baby_voltigore.mdl
models/sa13/bd.mdl
models/sa13/big_mom.mdl
models/sa13/bullsquid.mdl
models/sa13/controller.mdl
models/sa13/garg.mdl
models/sa13/gevaudan.mdl
models/sa13/grenade.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/icky.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/ngapache.mdl
models/sa13/ngt_boys.mdl
models/sa13/p_357.mdl
models/sa13/p_57.mdl
models/sa13/p_akimbotmp.mdl
models/sa13/p_akimbotmpg.mdl
models/sa13/p_akm.mdl
models/sa13/p_aw50.mdl
models/sa13/p_c4.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_deagle.mdl
models/sa13/p_dminigunidle.mdl
models/sa13/p_dminigunspin.mdl
models/sa13/p_egony.mdl
models/sa13/p_fn2000.mdl
models/sa13/p_laser.mdl
models/sa13/p_m61.mdl
models/sa13/p_med.mdl
models/sa13/p_mgun.mdl
models/sa13/p_mine.mdl
models/sa13/p_pancor.mdl
models/sa13/p_radio.mdl
models/sa13/p_scythe.mdl
models/sa13/p_shlrpg.mdl
models/sa13/p_tmp.mdl
models/sa13/panchem.mdl
models/sa13/perche.mdl
models/sa13/pit_drone.mdl
models/sa13/ru.mdl
models/sa13/ru2.mdl
models/sa13/sas.mdl
models/sa13/strooper.mdl
models/sa13/tentacle.mdl
models/sa13/tropical.mdl
models/sa13/v_357.mdl
models/sa13/v_57.mdl
models/sa13/v_akimbotmp.mdl
models/sa13/v_akm.mdl
models/sa13/v_aw50.mdl
models/sa13/v_c4.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_deagle.mdl
models/sa13/v_dminigun.mdl
models/sa13/v_egony.mdl
models/sa13/v_fn2000.mdl
models/sa13/v_laser.mdl
models/sa13/v_m61.mdl
models/sa13/v_med.mdl
models/sa13/v_mgun.mdl
models/sa13/v_mine.mdl
models/sa13/v_pancor.mdl
models/sa13/v_radio.mdl
models/sa13/v_scythe.mdl
models/sa13/v_shlrpg.mdl
models/sa13/voltigore.mdl
models/sa13/w_357.mdl
models/sa13/w_57.mdl
models/sa13/w_akimbotmp.mdl
models/sa13/w_akimbotmpg.mdl
models/sa13/w_akm.mdl
models/sa13/w_akm_clip.mdl
models/sa13/w_ARgrenade.mdl
models/sa13/w_aw50.mdl
models/sa13/w_c4.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_deagle.mdl
models/sa13/w_dminigun.mdl
models/sa13/w_egony.mdl
models/sa13/w_fn2000.mdl
models/sa13/w_laser.mdl
models/sa13/w_m61.mdl
models/sa13/w_med.mdl
models/sa13/w_mgun.mdl
models/sa13/w_mine.mdl
models/sa13/w_pancor.mdl
models/sa13/w_rpgammo.mdl
models/sa13/w_saw_clip.mdl
models/sa13/w_scythe.mdl
models/sa13/w_shlrpg.mdl
models/sa13/w_tmp.mdl
models/sa13/zombie.mdl
sa13full.wad
sound/sa13/ambience/alarmeu.ogg
sound/sa13/ambience/alrm6.ogg
sound/sa13/ambience/alrm7.ogg
sound/sa13/ambience/alrm8.ogg
sound/sa13/ambience/alrm9.ogg
sound/sa13/ambience/alrme5.ogg
sound/sa13/ambience/birds1.ogg
sound/sa13/ambience/birds10.ogg
sound/sa13/ambience/birds11.ogg
sound/sa13/ambience/birds2.ogg
sound/sa13/ambience/birds3.ogg
sound/sa13/ambience/birds4.ogg
sound/sa13/ambience/birds5.ogg
sound/sa13/ambience/birds6.ogg
sound/sa13/ambience/birds7.ogg
sound/sa13/ambience/birds8.ogg
sound/sa13/ambience/birds9.ogg
sound/sa13/ambience/faucon.ogg
sound/sa13/ambience/faucon2.ogg
sound/sa13/ambience/frog.ogg
sound/sa13/ambience/frog2.ogg
sound/sa13/ambience/h2.ogg
sound/sa13/ambience/lan1shut.ogg
sound/sa13/ambience/machines.ogg
sound/sa13/ambience/machines3.ogg
sound/sa13/ambience/sewer1.ogg
sound/sa13/ambience/turbine.ogg
sound/sa13/ambience/venta.ogg
sound/sa13/ambience/ventb.ogg
sound/sa13/ambience/ventc.ogg
sound/sa13/ambience/ventd.ogg
sound/sa13/ambience/water1.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/war2.ogg
sound/sa13/weapons/357_reload1.wav
sound/sa13/weapons/357_shot1.wav
sound/sa13/weapons/357_shot2.wav
sound/sa13/weapons/explode4.WAV
sound/sa13/weapons/gauss2.wav
sound/sa13/weapons/hks1.wav
sound/sa13/weapons/hks2.wav
sound/sa13/weapons/hks3.wav
sound/sa13/weapons/pl_gun3.wav
sound/sa13/weapons/reload1.wav
sound/sa13/weapons/reload2.wav
sound/sa13/weapons/reload3.wav
sound/sa13/weapons/ric1.wav
sound/sa13/weapons/ric2.wav
sound/sa13/weapons/ric3.wav
sound/sa13/weapons/ric4.wav
sound/sa13/weapons/ric5.wav
sound/sa13/weapons/ric6.wav
sound/sa13/weapons/rocketfire1.wav
sound/sa13/weapons/saw_fire1.wav
sound/sa13/weapons/saw_fire2.wav
sound/sa13/weapons/saw_fire3.wav
sound/sa13/weapons/saw_reload.wav
sound/sa13/weapons/saw_reload2.wav
sound/sa13/weapons/sbarrel1.wav
sound/sa13/weapons/sniper_bolt1.wav
sound/sa13/weapons/sniper_bolt2.wav
sound/sa13/weapons/sniper_fire.wav
sound/sa13/weapons/sniper_miss.wav
sound/sa13/weapons/sniper_reload3.wav
sound/sa13/weapons/sniper_reload_first_seq.wav
sound/sa13/weapons/sniper_reload_second_seq.wav
sound/sa13/weapons/sniper_zoom.wav
sound/sa13/weapons/sshell1.wav
sound/sa13/weapons/sshell2.wav
sound/sa13/weapons/sshell3.wav
sound/sa13/weapons/uzi/fire_both1.wav
sound/sa13/weapons/uzi/fire_both2.wav
sound/sa13/weapons/uzi/reload1.wav
sound/sa13/weapons/uzi/reload2.wav
sound/sa13/weapons/uzi/reload3.wav
sound/sa13/weapons/uzi/reload_left1.wav
sound/sa13/weapons/uzi/reload_left2.wav
sound/sa13/weapons/uzi/reload_right1.wav
sound/sa13/weapons/uzi/reload_right2.wav
sound/sa13/weapons/uzi/shoot1.wav
sound/sa13/weapons/uzi/shoot2.wav
sound/sa13/weapons/uzi/shoot3.wav
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scmod/sa13/dialogs/sa13gth/1pilotcrash_r.ogg
sound/scmod/sa13/dialogs/sa13gth/2medic_r.ogg
sound/weapons/629_shells_land.wav
sound/weapons/AK-101/boltpull.wav
sound/weapons/AK-101/gp25_reload.wav
sound/weapons/AK-101/magin.wav
sound/weapons/AK-101/magout.wav
sound/weapons/CS/awp_clipin.wav
sound/weapons/CS/awp_clipout.wav
sound/weapons/CS/boltdown.wav
sound/weapons/CS/boltpull1.wav
sound/weapons/CS/boltup.wav
sound/weapons/cs16/fiveseven_clipin.wav
sound/weapons/cs16/fiveseven_clipout.wav
sound/weapons/cs16/fiveseven_slidepull.wav
sound/weapons/cs16/fiveseven_sliderelease.wav
sound/weapons/de_deploy.wav
sound/weapons/f2k_magin.wav
sound/weapons/f2k_magout.wav
sound/weapons/glock18-1.wav
sound/weapons/janus7xmas/janus7xmas_clipin1.wav
sound/weapons/janus7xmas/janus7xmas_clipin2.wav
sound/weapons/janus7xmas/janus7xmas_clipin3.wav
sound/weapons/janus7xmas/janus7xmas_clipout1.wav
sound/weapons/janus7xmas/janus7xmas_clipout2.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
sprites/sa13/3dm_palm_01.spr
sprites/sa13/3dm_palm_02.spr
sprites/sa13/3dm_palm_03.spr
sprites/sa13/ghostfish5.spr
sprites/sa13/nm_tree2.spr
sprites/sa13/nm_tree6.spr
sprites/sa13/pine2.spr
sprites/sa13/thwtree1.spr
