// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/mars1bk.tga
gfx/env/mars1dn.tga
gfx/env/mars1ft.tga
gfx/env/mars1lf.tga
gfx/env/mars1rt.tga
gfx/env/mars1up.tga
models/sa13/agrunt.mdl
models/sa13/agruntf.mdl
models/sa13/apache.mdl
models/sa13/baby_voltigore.mdl
models/sa13/big_mom.mdl
models/sa13/bullsquid.mdl
models/sa13/controller.mdl
models/sa13/garg.mdl
models/sa13/grenade.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/icky.mdl
models/sa13/islave.mdl
models/sa13/massn.mdl
models/sa13/ngt_boys.mdl
models/sa13/p_357.mdl
models/sa13/p_akimbomp5k.mdl
models/sa13/p_akm.mdl
models/sa13/p_beretta.mdl
models/sa13/p_c4.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_dminigunidle.mdl
models/sa13/p_dminigunspin.mdl
models/sa13/p_egony.mdl
models/sa13/p_g3sg1.mdl
models/sa13/p_gaussb.mdl
models/sa13/p_hegr.mdl
models/sa13/p_med.mdl
models/sa13/p_mgun.mdl
models/sa13/p_mine.mdl
models/sa13/p_mp5k.mdl
models/sa13/p_radio.mdl
models/sa13/p_rpgcamo.mdl
models/sa13/p_scopedspas.mdl
models/sa13/p_scythe.mdl
models/sa13/p_tar21.mdl
models/sa13/p_usp45.mdl
models/sa13/panchem.mdl
models/sa13/pit_drone.mdl
models/sa13/strooper.mdl
models/sa13/tentacle.mdl
models/sa13/v_357.mdl
models/sa13/v_akimbomp5k.mdl
models/sa13/v_akm.mdl
models/sa13/v_beretta.mdl
models/sa13/v_c4.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_dminigun.mdl
models/sa13/v_egony.mdl
models/sa13/v_g3sg1.mdl
models/sa13/v_gaussb.mdl
models/sa13/v_hegr.mdl
models/sa13/v_med.mdl
models/sa13/v_mgun.mdl
models/sa13/v_mine.mdl
models/sa13/v_radio.mdl
models/sa13/v_rpgcamo.mdl
models/sa13/v_scopedspas.mdl
models/sa13/v_scythe.mdl
models/sa13/v_tar21.mdl
models/sa13/v_usp45.mdl
models/sa13/voltigore.mdl
models/sa13/w_357.mdl
models/sa13/w_akimbomp5k.mdl
models/sa13/w_akm.mdl
models/sa13/w_akm_clip.mdl
models/sa13/w_ARgrenade.mdl
models/sa13/w_beretta.mdl
models/sa13/w_c4.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_dminigun.mdl
models/sa13/w_egony.mdl
models/sa13/w_g3sg1.mdl
models/sa13/w_gaussb.mdl
models/sa13/w_hegr.mdl
models/sa13/w_med.mdl
models/sa13/w_mgun.mdl
models/sa13/w_mine.mdl
models/sa13/w_mp5k.mdl
models/sa13/w_rpgammo.mdl
models/sa13/w_rpgcamo.mdl
models/sa13/w_saw_clip.mdl
models/sa13/w_scopedspas.mdl
models/sa13/w_scythe.mdl
models/sa13/w_tar21.mdl
models/sa13/w_usp45.mdl
models/sa13/zombie.mdl
sa13full.wad
sound/custom_weapons/tar21/tar21_boltpull.wav
sound/custom_weapons/tar21/tar21_clipin.wav
sound/custom_weapons/tar21/tar21_clipout.wav
sound/sa13/ambience/alarmeu.ogg
sound/sa13/ambience/alrm6.ogg
sound/sa13/ambience/alrm8.ogg
sound/sa13/ambience/departrocket.ogg
sound/sa13/ambience/envol.ogg
sound/sa13/ambience/h4.ogg
sound/sa13/ambience/lan1shut.ogg
sound/sa13/ambience/machines3.ogg
sound/sa13/ambience/pompstation.ogg
sound/sa13/ambience/predatorlaugh.ogg
sound/sa13/ambience/pvision.ogg
sound/sa13/ambience/rebip.ogg
sound/sa13/ambience/rocketpoussee.ogg
sound/sa13/ambience/venta.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/war1.ogg
sound/sa13/weapons/357_reload1.wav
sound/sa13/weapons/357_shot1.wav
sound/sa13/weapons/357_shot2.wav
sound/sa13/weapons/explode4.WAV
sound/sa13/weapons/gauss2.wav
sound/sa13/weapons/hks1.wav
sound/sa13/weapons/hks2.wav
sound/sa13/weapons/hks3.wav
sound/sa13/weapons/pl_gun3.wav
sound/sa13/weapons/reload1.wav
sound/sa13/weapons/reload2.wav
sound/sa13/weapons/reload3.wav
sound/sa13/weapons/ric1.wav
sound/sa13/weapons/ric2.wav
sound/sa13/weapons/ric3.wav
sound/sa13/weapons/ric4.wav
sound/sa13/weapons/ric5.wav
sound/sa13/weapons/ric6.wav
sound/sa13/weapons/rocketfire1.wav
sound/sa13/weapons/saw_fire1.wav
sound/sa13/weapons/saw_fire2.wav
sound/sa13/weapons/saw_fire3.wav
sound/sa13/weapons/saw_reload.wav
sound/sa13/weapons/saw_reload2.wav
sound/sa13/weapons/sbarrel1.wav
sound/sa13/weapons/sniper_bolt1.wav
sound/sa13/weapons/sniper_bolt2.wav
sound/sa13/weapons/sniper_fire.wav
sound/sa13/weapons/sniper_miss.wav
sound/sa13/weapons/sniper_reload3.wav
sound/sa13/weapons/sniper_reload_first_seq.wav
sound/sa13/weapons/sniper_reload_second_seq.wav
sound/sa13/weapons/sniper_zoom.wav
sound/sa13/weapons/sshell1.wav
sound/sa13/weapons/sshell2.wav
sound/sa13/weapons/sshell3.wav
sound/sa13/weapons/uzi/fire_both1.wav
sound/sa13/weapons/uzi/fire_both2.wav
sound/sa13/weapons/uzi/reload1.wav
sound/sa13/weapons/uzi/reload2.wav
sound/sa13/weapons/uzi/reload3.wav
sound/sa13/weapons/uzi/reload_left1.wav
sound/sa13/weapons/uzi/reload_left2.wav
sound/sa13/weapons/uzi/reload_right1.wav
sound/sa13/weapons/uzi/reload_right2.wav
sound/sa13/weapons/uzi/shoot1.wav
sound/sa13/weapons/uzi/shoot2.wav
sound/sa13/weapons/uzi/shoot3.wav
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scmod/sa13/dialogs/sa13e/1sven_r.ogg
sound/scmod/sa13/dialogs/sa13e/2sven_r.ogg
sound/scmod/sa13/dialogs/sa13e/3sven_r.ogg
sound/weapons/629_shells_land.wav
sound/weapons/AK-101/boltpull.wav
sound/weapons/AK-101/gp25_reload.wav
sound/weapons/AK-101/magin.wav
sound/weapons/AK-101/magout.wav
sound/weapons/foley_grabmag.wav
sound/weapons/glock18-1.wav
sound/weapons/janus7xmas/janus7xmas_clipin1.wav
sound/weapons/janus7xmas/janus7xmas_clipin2.wav
sound/weapons/janus7xmas/janus7xmas_clipin3.wav
sound/weapons/janus7xmas/janus7xmas_clipout1.wav
sound/weapons/janus7xmas/janus7xmas_clipout2.wav
sound/weapons/mp5k_boltback.wav
sound/weapons/mp5k_boltslap.wav
sound/weapons/mp5k_magin.wav
sound/weapons/mp5k_magout.wav
sound/weapons/mp5k_slamtogether.wav
sound/weapons/mp5k_toakimbo.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sound/weapons/sdraw.wav
sound/weapons/sPump.wav
sound/weapons/start_reload.wav
sound/weapons/uspmatch_magin.wav
sound/weapons/uspmatch_magout.wav
sound/weapons/uspmatch_sliderelease.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
