// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/de_stormbk.tga
gfx/env/de_stormdn.tga
gfx/env/de_stormft.tga
gfx/env/de_stormlf.tga
gfx/env/de_stormrt.tga
gfx/env/de_stormup.tga
models/escape_series/fast_zombie/zombie.mdl
models/escape_series/fast_zombie/zombie01.mdl
models/escape_series/fast_zombie/zombie02.mdl
models/escape_series/fast_zombie/zombie03.mdl
models/escape_series/fast_zombie/zombiet.mdl
models/sa13/agrunt.mdl
models/sa13/agruntf.mdl
models/sa13/apache.mdl
models/sa13/baby_voltigore.mdl
models/sa13/big_mom.mdl
models/sa13/bullsquid.mdl
models/sa13/controller.mdl
models/sa13/cthulhu.mdl
models/sa13/cultist.mdl
models/sa13/eldritchportal.mdl
models/sa13/garg.mdl
models/sa13/grenade.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/houndeye.mdl
models/sa13/hwgrunt.mdl
models/sa13/icky.mdl
models/sa13/massn.mdl
models/sa13/ngt_boys.mdl
models/sa13/p_357.mdl
models/sa13/p_57.mdl
models/sa13/p_akimbotmp.mdl
models/sa13/p_akimbotmpg.mdl
models/sa13/p_akm.mdl
models/sa13/p_barrett.mdl
models/sa13/p_bfg.mdl
models/sa13/p_c4.mdl
models/sa13/p_crossbow.mdl
models/sa13/p_deagle.mdl
models/sa13/p_dminigunidle.mdl
models/sa13/p_dminigunspin.mdl
models/sa13/p_egony.mdl
models/sa13/p_fn2000.mdl
models/sa13/p_laser.mdl
models/sa13/p_m61.mdl
models/sa13/p_med.mdl
models/sa13/p_mgun.mdl
models/sa13/p_mine.mdl
models/sa13/p_pancor.mdl
models/sa13/p_radio.mdl
models/sa13/p_scythe.mdl
models/sa13/p_segon.mdl
models/sa13/p_tmp.mdl
models/sa13/panchem.mdl
models/sa13/panchem2.mdl
models/sa13/pit_drone.mdl
models/sa13/spawn.mdl
models/sa13/strooper.mdl
models/sa13/tentacle.mdl
models/sa13/v_357.mdl
models/sa13/v_57.mdl
models/sa13/v_akimbotmp.mdl
models/sa13/v_akm.mdl
models/sa13/v_barrett.mdl
models/sa13/v_bfg.mdl
models/sa13/v_c4.mdl
models/sa13/v_crossbow.mdl
models/sa13/v_deagle.mdl
models/sa13/v_dminigun.mdl
models/sa13/v_egony.mdl
models/sa13/v_fn2000.mdl
models/sa13/v_laser.mdl
models/sa13/v_m61.mdl
models/sa13/v_med.mdl
models/sa13/v_mgun.mdl
models/sa13/v_mine.mdl
models/sa13/v_pancor.mdl
models/sa13/v_radio.mdl
models/sa13/v_scythe.mdl
models/sa13/v_segon.mdl
models/sa13/voltigore.mdl
models/sa13/w_357.mdl
models/sa13/w_57.mdl
models/sa13/w_akimbotmp.mdl
models/sa13/w_akimbotmpg.mdl
models/sa13/w_akm.mdl
models/sa13/w_akm_clip.mdl
models/sa13/w_ARgrenade.mdl
models/sa13/w_barrett.mdl
models/sa13/w_bfg.mdl
models/sa13/w_c4.mdl
models/sa13/w_crossbow.mdl
models/sa13/w_deagle.mdl
models/sa13/w_dminigun.mdl
models/sa13/w_egony.mdl
models/sa13/w_fn2000.mdl
models/sa13/w_laser.mdl
models/sa13/w_m61.mdl
models/sa13/w_med.mdl
models/sa13/w_mgun.mdl
models/sa13/w_mine.mdl
models/sa13/w_pancor.mdl
models/sa13/w_rpgammo.mdl
models/sa13/w_saw_clip.mdl
models/sa13/w_scythe.mdl
models/sa13/w_seal.mdl
models/sa13/w_segon.mdl
models/sa13/w_tmp.mdl
models/sa13/zombie.mdl
models/scmod/npcs/babygarg/Outerbeast.mdl
sa13full.wad
sound/sa13/ambience/machines.ogg
sound/sa13/ambience/machines2.ogg
sound/sa13/ambience/sewer1.ogg
sound/sa13/ambience/ventd.ogg
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.ogg
sound/sa13/pitdrone/pit_drone_alert2.ogg
sound/sa13/pitdrone/pit_drone_alert3.ogg
sound/sa13/pitdrone/pit_drone_die1.ogg
sound/sa13/pitdrone/pit_drone_die2.ogg
sound/sa13/pitdrone/pit_drone_die3.ogg
sound/sa13/pitdrone/pit_drone_eat.ogg
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.ogg
sound/sa13/voltigore/voltigore_attack_shock.ogg
sound/sa13/voltigore/voltigore_idle1.ogg
sound/sa13/weapons/357_reload1.wav
sound/sa13/weapons/357_shot1.wav
sound/sa13/weapons/357_shot2.wav
sound/sa13/weapons/explode4.WAV
sound/sa13/weapons/gauss2.wav
sound/sa13/weapons/hks1.wav
sound/sa13/weapons/hks2.wav
sound/sa13/weapons/hks3.wav
sound/sa13/weapons/pl_gun3.wav
sound/sa13/weapons/reload1.wav
sound/sa13/weapons/reload2.wav
sound/sa13/weapons/reload3.wav
sound/sa13/weapons/ric1.wav
sound/sa13/weapons/ric2.wav
sound/sa13/weapons/ric3.wav
sound/sa13/weapons/ric4.wav
sound/sa13/weapons/ric5.wav
sound/sa13/weapons/ric6.wav
sound/sa13/weapons/rocketfire1.wav
sound/sa13/weapons/saw_fire1.wav
sound/sa13/weapons/saw_fire2.wav
sound/sa13/weapons/saw_fire3.wav
sound/sa13/weapons/saw_reload.wav
sound/sa13/weapons/saw_reload2.wav
sound/sa13/weapons/sbarrel1.wav
sound/sa13/weapons/sniper_bolt1.wav
sound/sa13/weapons/sniper_bolt2.wav
sound/sa13/weapons/sniper_fire.wav
sound/sa13/weapons/sniper_miss.wav
sound/sa13/weapons/sniper_reload3.wav
sound/sa13/weapons/sniper_reload_first_seq.wav
sound/sa13/weapons/sniper_reload_second_seq.wav
sound/sa13/weapons/sniper_zoom.wav
sound/sa13/weapons/sshell1.wav
sound/sa13/weapons/sshell2.wav
sound/sa13/weapons/sshell3.wav
sound/sa13/weapons/uzi/fire_both1.wav
sound/sa13/weapons/uzi/fire_both2.wav
sound/sa13/weapons/uzi/reload1.wav
sound/sa13/weapons/uzi/reload2.wav
sound/sa13/weapons/uzi/reload3.wav
sound/sa13/weapons/uzi/reload_left1.wav
sound/sa13/weapons/uzi/reload_left2.wav
sound/sa13/weapons/uzi/reload_right1.wav
sound/sa13/weapons/uzi/reload_right2.wav
sound/sa13/weapons/uzi/shoot1.wav
sound/sa13/weapons/uzi/shoot2.wav
sound/sa13/weapons/uzi/shoot3.wav
sound/sa13/zombie/zo_alert10.ogg
sound/sa13/zombie/zo_alert20.ogg
sound/sa13/zombie/zo_attack1.ogg
sound/sa13/zombie/zo_idle1.ogg
sound/sa13/zombie/zo_idle2.ogg
sound/sa13/zombie/zo_idle3.ogg
sound/sa13/zombie/zo_idle4.ogg
sound/sa13/zombie/zo_pain1.ogg
sound/scmod/npcs/cthulhu/gar_alert1.wav
sound/scmod/npcs/cthulhu/gar_alert3.wav
sound/scmod/npcs/cthulhu/gar_attack1-alt.wav
sound/scmod/npcs/cthulhu/gar_attack2.wav
sound/scmod/npcs/cthulhu/gar_attack3.wav
sound/scmod/npcs/cthulhu/gar_breathe1.wav
sound/scmod/npcs/cthulhu/gar_breathe2.wav
sound/scmod/npcs/cthulhu/gar_breathe3.wav
sound/scmod/npcs/cthulhu/gar_pain1.wav
sound/scmod/npcs/cthulhu/gar_pain2.wav
sound/scmod/npcs/cultist/cu_alert5.wav
sound/scmod/npcs/cultist/cu_charge4.wav
sound/scmod/npcs/cultist/cu_charge5.wav
sound/scmod/sa13/boss_introsfx.ogg
sound/scmod/sa13/bossintro.ogg
sound/scmod/sa13/bossloop.ogg
sound/scmod/sa13/dialogs/sa13panchem/10art_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/11pilot_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/12sven_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/13sven_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/14sven_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/15cheer_e.ogg
sound/scmod/sa13/dialogs/sa13panchem/1sven_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/2cult.ogg
sound/scmod/sa13/dialogs/sa13panchem/2panchem.ogg
sound/scmod/sa13/dialogs/sa13panchem/3panchem.ogg
sound/scmod/sa13/dialogs/sa13panchem/4love_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/5love_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/6sven_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/7love_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/8sven_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/9pilot_r.ogg
sound/scmod/sa13/dialogs/sa13panchem/svenfog_r.ogg
sound/scmod/sa13/osprey_rotors.ogg
sound/weapons/629_shells_land.wav
sound/weapons/AK-101/boltpull.wav
sound/weapons/AK-101/gp25_reload.wav
sound/weapons/AK-101/magin.wav
sound/weapons/AK-101/magout.wav
sound/weapons/cs16/fiveseven_clipin.wav
sound/weapons/cs16/fiveseven_clipout.wav
sound/weapons/cs16/fiveseven_slidepull.wav
sound/weapons/cs16/fiveseven_sliderelease.wav
sound/weapons/de_deploy.wav
sound/weapons/f2k_magin.wav
sound/weapons/f2k_magout.wav
sound/weapons/glock18-1.wav
sound/weapons/janus7xmas/janus7xmas_clipin1.wav
sound/weapons/janus7xmas/janus7xmas_clipin2.wav
sound/weapons/janus7xmas/janus7xmas_clipin3.wav
sound/weapons/janus7xmas/janus7xmas_clipout1.wav
sound/weapons/janus7xmas/janus7xmas_clipout2.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sound/weapons/xbow_clipin.wav
sound/weapons/xbow_clipout.wav
sound/weapons/xbow_drawback.wav
