// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/mars2bk.tga
gfx/env/mars2dn.tga
gfx/env/mars2ft.tga
gfx/env/mars2lf.tga
gfx/env/mars2rt.tga
gfx/env/mars2up.tga
maps/zoology1.bsp
maps/zoology10.bsp
maps/zoology11.bsp
maps/zoology12pt2.bsp
maps/zoology13.bsp
maps/zoology14.bsp
maps/zoology15.bsp
maps/zoology16.bsp
maps/zoology2.bsp
maps/zoology3.bsp
maps/zoology4.bsp
maps/zoology5.bsp
maps/zoology5pt2.bsp
maps/zoology6.bsp
maps/zoology7.bsp
maps/zoology8.bsp
maps/zoology9.bsp
neilm.wad
sound/magnus/alien_move5.wav
sound/magnus/barney_shit.wav
sound/magnus/bigwarning.wav
sound/magnus/bug1.wav
sound/magnus/bug2.wav
sound/magnus/captain.wav
sound/magnus/caugh.wav
sound/magnus/computer5.wav
sound/magnus/distress1.wav
sound/magnus/ds_mon_amb1.wav
sound/magnus/ds_mon_amb2.wav
sound/magnus/ds_mon_amb3.wav
sound/magnus/dsmove.wav
sound/magnus/dsmove2.wav
sound/magnus/elev_hurt1.wav
sound/magnus/flyby3.wav
sound/magnus/forcefield_a.wav
sound/magnus/forcefield_b.wav
sound/magnus/gravy3_a.wav
sound/magnus/gravy3_b.wav
sound/magnus/gravy3_c.wav
sound/magnus/hascold.wav
sound/magnus/heart.wav
sound/magnus/intelli.wav
sound/magnus/lazer3.wav
sound/magnus/letsgo.wav
sound/magnus/onlyhope.wav
sound/magnus/pod.wav
sound/magnus/quake1_loop.wav
sound/magnus/quake2.wav
sound/magnus/rumble12.wav
sound/magnus/rumble6.wav
sound/magnus/toolate.wav
sound/magnus/toscared.wav
sound/magnus/whatthe.wav
sound/magnus/whoa.wav
sound/vox/alien_vox.wav
sound/vox/electrical.wav
sound/vox/gravity.wav
sound/vox/ship.wav
sound/vox/static.wav
sound/vox/wait.wav
sound/vox/zoological.wav
